<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Nyar.Binary.Onnx</RootNamespace>
    <AssemblyName>Nyar.Binary.Onnx</AssemblyName>
    <PackageId>Nyar.Binary.Onnx</PackageId>
          <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sonic.Standard.Data.Binary.csproj" />
    <ProjectReference Include="..\..\Nyar\Nyar.csproj" />
  </ItemGroup>
</Project>