<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <PackageId>Sonic.Standard.Compression</PackageId>
        <RootNamespace>Std.Compression</RootNamespace>
        <Description>Sonic 压缩标准库：Brotli、Deflate、Gzip 压缩/解压及流式读写器</Description>
        <Authors>Sonic Team</Authors>
        <Company>Sonic</Company>
        <Product>Sonic</Product>
        <PackageTags>sonic;compression;brotli;deflate;gzip;stream</PackageTags>
        <IsPackable>true</IsPackable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageOutputPath>..\..\packages</PackageOutputPath>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
    </PropertyGroup>
    <ItemGroup>
        <None Include="readme.md" Pack="true" PackagePath=""/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Sonic.Core\Sonic.Core.csproj" />
        <ProjectReference Include="..\Sonic.Standard\Sonic.Standard.csproj" />
            </ItemGroup>
</Project>