<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>Sonic.Tests</RootNamespace>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
            <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.15.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.15.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\projects\Sonic.Standard\Sonic.Standard.csproj"/>
        <ProjectReference Include="..\..\projects\Sonic.Standard.Data.Text\Sonic.Standard.Data.Text.csproj"/>
        <ProjectReference Include="..\..\projects\Sonic.SourceGenerator\Sonic.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>
