<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Nyar.Protocol.ZeroMQ</RootNamespace>
    <AssemblyName>Nyar.Protocol.ZeroMQ</AssemblyName>
        <Authors>nyar-vm</Authors>
    <Description>Acorn ZeroMQ 协议库，提供 ZeroMQ 协议的扫描、编码和解码功能</Description>
    <PackageProjectUrl>https://github.com/nyar-vm/Acorn.cs</PackageProjectUrl>
            <PackageReadmeFile>Readme.md</PackageReadmeFile>
          <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sonic.Standard.Data.Binary.csproj" />
      </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Readme.md" Pack="true" PackagePath="" />
      </ItemGroup>

</Project>


