<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <RootNamespace>Std.Template.Cms</RootNamespace>
        <AssemblyName>Sonic.Standard.Template.Cms</AssemblyName>
        <PackageId>Sonic.Standard.Template.Cms</PackageId>
        <Version>0.1.0</Version>
        <Authors>NyarVM</Authors>
        <Description>内容管理系统</Description>
        <PackageProjectUrl>https://github.com/nyar-vm/DejavuEngine</PackageProjectUrl>
        <RepositoryUrl>https://github.com/nyar-vm/DejavuEngine</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>template;cms</PackageTags>
            <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Dejavu\Dejavu.csproj"/>
    </ItemGroup>


  <ItemGroup>
        <Compile Remove="ContentManager.cs"/>
  </ItemGroup>
</Project>
