using System.Text;
using Hermes.Generator;

namespace Hermes.Plugin.GGScript;

public sealed class GGScriptGenerator : IGenerator
{
    public string Name => "ggscript";

    public string[] SupportedTargets => ["struct", "enum", "flags", "union", "service"];

    public GeneratorResult Generate(GeneratorContext context)
    {
        var errors = new List<string>();
        var warnings = new List<string>();
        var files = new List<GeneratedFile>();

        var outputPath = context.OutputPath;
        if (!Directory.Exists(outputPath)) Directory.CreateDirectory(outputPath);

        foreach (var classDef in context.Schema.Classes)
        {
            var content = GenerateStruct(classDef, context.Schema.Namespace, context.SchemaPath);
            var filePath = Path.Combine(outputPath, $"{classDef.Name}.ggs");
            files.Add(new GeneratedFile
            {
                Path = filePath, Content = content, Generator = Name, TypeName = classDef.Name
            });
        }

        foreach (var modelDef in context.Schema.Storages.SelectMany(s => s.Models))
        {
            var content = GenerateStruct(modelDef, context.Schema.Namespace, context.SchemaPath);
            var filePath = Path.Combine(outputPath, $"{modelDef.Name}.ggs");
            files.Add(new GeneratedFile
            {
                Path = filePath, Content = content, Generator = Name, TypeName = modelDef.Name
            });
        }

        foreach (var enumDef in context.Schema.Enums)
        {
            var content = GenerateEnum(enumDef, context.SchemaPath);
            var filePath = Path.Combine(outputPath, $"{enumDef.Name}.ggs");
            files.Add(new GeneratedFile
            {
                Path = filePath, Content = content, Generator = Name, TypeName = enumDef.Name
            });
        }

        foreach (var flagDef in context.Schema.Flags)
        {
            var content = GenerateFlags(flagDef, context.SchemaPath);
            var filePath = Path.Combine(outputPath, $"{flagDef.Name}.ggs");
            files.Add(new GeneratedFile
            {
                Path = filePath, Content = content, Generator = Name, TypeName = flagDef.Name
            });
        }

        foreach (var unionDef in context.Schema.Unions)
        {
            var content = GenerateUnion(unionDef, context.SchemaPath);
            var filePath = Path.Combine(outputPath, $"{unionDef.Name}.ggs");
            files.Add(new GeneratedFile
            {
                Path = filePath, Content = content, Generator = Name, TypeName = unionDef.Name
            });
        }

        foreach (var service in context.Schema.Services)
        {
            var content = GenerateService(service, context.SchemaPath);
            var filePath = Path.Combine(outputPath, $"{service.Name}.ggs");
            files.Add(new GeneratedFile
            {
                Path = filePath, Content = content, Generator = Name, TypeName = service.Name
            });
        }

        return new GeneratorResult { Files = files, Errors = errors, Warnings = warnings };
    }

    #region 文件头

    private static string GenerateFileHeader(string schemaPath)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 本文件由 hermes 命令自动生成，修改无效");
        sb.AppendLine($"// 源文件: {schemaPath}");
        sb.AppendLine($"// 生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        return sb.ToString();
    }

    #endregion

    #region Enum 生成

    private static string GenerateEnum(EnumDefinition enumDef, string schemaPath)
    {
        var sb = new StringBuilder();
        sb.Append(GenerateFileHeader(schemaPath));
        sb.AppendLine($"enum {enumDef.Name}");
        sb.AppendLine("{");

        for (var i = 0; i < enumDef.Members.Count; i++)
        {
            var member = enumDef.Members[i];
            var separator = i < enumDef.Members.Count - 1 ? "," : "";
            sb.AppendLine($"    {member.Name} = {member.Value}{separator}");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    #endregion

    #region Flags 生成

    private static string GenerateFlags(FlagsDefinition flagDef, string schemaPath)
    {
        var sb = new StringBuilder();
        sb.Append(GenerateFileHeader(schemaPath));
        sb.AppendLine($"flags {flagDef.Name}");
        sb.AppendLine("{");

        for (var i = 0; i < flagDef.Members.Count; i++)
        {
            var member = flagDef.Members[i];
            var separator = i < flagDef.Members.Count - 1 ? "," : "";
            sb.AppendLine($"    {member.Name} = {member.Value}{separator}");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    #endregion

    #region Union 生成

    private static string GenerateUnion(UnionDefinition unionDef, string schemaPath)
    {
        var sb = new StringBuilder();
        sb.Append(GenerateFileHeader(schemaPath));
        sb.AppendLine($"union {unionDef.Name}");
        sb.AppendLine("{");

        for (var i = 0; i < unionDef.Variants.Count; i++)
        {
            var variant = unionDef.Variants[i];
            var separator = i < unionDef.Variants.Count - 1 ? "," : "";
            var ggType = MapToGGScriptType(variant.Payload);
            sb.AppendLine($"    {variant.Name}: {ggType}{separator}");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    #endregion

    #region Service 生成

    private static string GenerateService(ServiceDefinition service, string schemaPath)
    {
        var sb = new StringBuilder();
        sb.Append(GenerateFileHeader(schemaPath));
        sb.AppendLine($"service {service.Name}");
        sb.AppendLine("{");

        foreach (var endpoint in service.Endpoints)
            switch (endpoint)
            {
                case HttpEndpoint http:
                    var returnType = http.ReturnType != null ? MapToGGScriptType(http.ReturnType) : "void";
                    sb.AppendLine($"    {http.HttpMethod} {http.Path}");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        // → {returnType}");
                    sb.AppendLine("    }");
                    break;
                case GrpcEndpoint grpc:
                    sb.AppendLine($"    rpc {grpc.Name} {{");
                    sb.AppendLine("        // → unknown");
                    sb.AppendLine("    }");
                    break;
                default:
                    sb.AppendLine($"    endpoint {endpoint.Name} {{ }}");
                    break;
            }

        sb.AppendLine("}");

        return sb.ToString();
    }

    #endregion

    #region 类型映射

    private static string MapToGGScriptType(SchemaType type)
    {
        return type switch
        {
            PrimitiveType p => p.TypeName switch
            {
                "i8" or "i16" or "i32" or "i64" => "int",
                "u8" or "u16" or "u32" or "u64" => "uint",
                "f32" => "float",
                "f64" => "double",
                "bool" => "bool",
                "utf8" or "utf16" => "string",
                "uuid" => "string",
                "unit" => "void",
                "datetime" => "datetime",
                "bytes" => "bytes",
                _ => "any"
            },
            ListType l => $"{MapToGGScriptType(l.ElementType)}[]",
            ArrayType a => $"{MapToGGScriptType(a.ElementType)}[]",
            OptionType o => $"{MapToGGScriptType(o.InnerType)}?",
            DictType d => $"map<{MapToGGScriptType(d.KeyType)}, {MapToGGScriptType(d.ValueType)}>",
            ResultType r => $"result<{MapToGGScriptType(r.OkType)}, {MapToGGScriptType(r.ErrorType!)}>",
            StreamType s => $"stream<{MapToGGScriptType(s.InnerType)}>",
            NamedType n => n.Name,
            ReferenceType refT => MapToGGScriptType(refT.ReferencedType),
            _ => "unknown"
        };
    }

    #endregion

    #region Struct 生成

    private static string GenerateStruct(ClassDefinition typeDef, string? schemaNamespace, string schemaPath)
    {
        var sb = new StringBuilder();
        sb.Append(GenerateFileHeader(schemaPath));

        if (!string.IsNullOrEmpty(schemaNamespace)) sb.AppendLine($"// namespace: {schemaNamespace}");

        sb.AppendLine($"struct {typeDef.Name}");
        sb.AppendLine("{");

        foreach (var field in typeDef.fields)
        {
            var ggType = MapToGGScriptType(field.FieldType);
            var optional = field.IsOptional ? "?" : "";
            sb.AppendLine($"    {field.Name}{optional}: {ggType};");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateStruct(ModelDefinition typeDef, string? schemaNamespace, string schemaPath)
    {
        var sb = new StringBuilder();
        sb.Append(GenerateFileHeader(schemaPath));

        if (!string.IsNullOrEmpty(schemaNamespace)) sb.AppendLine($"// namespace: {schemaNamespace}");

        sb.AppendLine($"struct {typeDef.Name}");
        sb.AppendLine("{");

        foreach (var field in typeDef.fields)
        {
            var ggType = MapToGGScriptType(field.FieldType);
            var optional = field.IsOptional ? "?" : "";
            sb.AppendLine($"    {field.Name}{optional}: {ggType};");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    #endregion
}