<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Nyar.Protocol.PostgreSQL</RootNamespace>
    <AssemblyName>Nyar.Protocol.PostgreSQL</AssemblyName>
    <PackageId>Nyar.Protocol.PostgreSQL</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sonic.Standard.Data.Binary.csproj"/>
  </ItemGroup>

</Project>


