<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <PackageId>Sonic.Standard.Data.Binary.Wasm</PackageId>
        <RootNamespace>Std.Data.Binary.Wasm</RootNamespace>
        <AssemblyName>Sonic.Standard.Data.Binary.Wasm</AssemblyName>
        <Authors>Nyar Team - Acorn Group</Authors>
        <Description>WebAssembly 二进制编解码 — .wasm 模块格式</Description>
            <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Standard.Data.Binary\Standard.Data.Binary.csproj" />
    </ItemGroup>
</Project>