<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <RootNamespace>Std.Schema.ORM</RootNamespace>
        <AssemblyName>Hermes.ORM</AssemblyName>
        <PackageId>Hermes.ORM</PackageId>
        <Authors>NyarVM</Authors>
        <Description>Hermes ORM — C# LINQ 风格查询 API</Description>
        <PackageTags>hermes;orm;linq;database</PackageTags>
            <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Sonic.Standard.Data.Text\Sonic.Standard.Data.Text.csproj"/>
        <ProjectReference Include="..\Sonic.Standard.Data.Text.Valkyrie\Valkyrie.csproj"/>
    </ItemGroup>
</Project>
