<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <RootNamespace>Galatea.Cluster</RootNamespace>
    <PackageId>Galatea.Cluster</PackageId>
        <Description>Galatea 集群抽象接口 + 本地/联邦实现</Description>
    <Authors>Olymp</Authors>
          <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sonic.Standard.DL.csproj" />
  </ItemGroup>

</Project>
