using System.Globalization;
using System.Text;
using Std.Data.Text.DejaVu.Expressions;

namespace Std.Data.Text.DejaVu.CodeGen;

/// <summary>
///     Java 代码生成器——将 DejaVu 模板 AST 转译为 Java 渲染类源码。
///     输出可在 JVM 中直接编译执行的 Java 代码。
/// </summary>
public sealed class JavaCodeGenerator
{
    private int _indent_level;


    /// <summary>
    ///     创建 Java 代码生成器
    /// </summary>
    public JavaCodeGenerator()
    {
        options = new JavaGeneratorOptions();
    }


    /// <summary>
    ///     创建 Java 代码生成器
    /// </summary>
    /// <param name="options">生成选项。</param>
    public JavaCodeGenerator(JavaGeneratorOptions options)
    {
        this.options = options;
    }


    /// <summary>
    ///     生成选项
    /// </summary>
    public JavaGeneratorOptions options { get; }


    /// <summary>
    ///     生成 Java 渲染类源码
    /// </summary>
    /// <param name="nodes">优化后的模板节点列表。</param>
    /// <param name="className">类名。</param>
    /// <returns>Java 源码。</returns>
    public string generate(IReadOnlyList<DejaVuTemplateNode> nodes, string className = "TemplateRenderer")
    {
        var sb = new StringBuilder();

        generate_header(sb);
        generate_class_header(sb, className);
        generate_render_method(sb, nodes);
        generate_helper_methods(sb);
        generate_class_footer(sb);

        return sb.ToString();
    }

    private void generate_header(StringBuilder sb)
    {
        if (options.include_header)
        {
            sb.AppendLine("// Auto-generated by DejaVu Java Code Generator");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine();
        }

        sb.AppendLine("import java.util.*;");
        sb.AppendLine("import java.util.stream.*;");
        sb.AppendLine();
    }

    private void generate_class_header(StringBuilder sb, string className)
    {
        sb.AppendLine($"public class {className} {{");
        _indent_level = 1;
    }

    private void generate_class_footer(StringBuilder sb)
    {
        _indent_level = 0;
        sb.AppendLine("}");
    }

    private void generate_render_method(StringBuilder sb, IReadOnlyList<DejaVuTemplateNode> nodes)
    {
        indent(sb);
        sb.AppendLine("public String render(Map<String, Object> ctx) {");
        _indent_level++;

        indent(sb);
        sb.AppendLine("StringBuilder sb = new StringBuilder();");

        foreach (var node in nodes) generate_node(sb, node, "ctx", "sb");

        indent(sb);
        sb.AppendLine("return sb.toString();");

        _indent_level--;
        indent(sb);
        sb.AppendLine("}");
    }

    private void generate_node(StringBuilder sb, DejaVuTemplateNode node, string ctxVar, string sbVar)
    {
        switch (node)
        {
            case DejaVuTextNode textNode:
                generate_text_node(sb, textNode, sbVar);
                break;
            case DejaVuCodeNode codeNode:
                generate_code_node(sb, codeNode, ctxVar, sbVar);
                break;
            case DejaVuIfNode ifNode:
                generate_if_node(sb, ifNode, ctxVar, sbVar);
                break;
            case DejaVuLoopNode loopNode:
                generate_loop_node(sb, loopNode, ctxVar, sbVar);
                break;
            case DejaVuLetNode letNode:
                generate_let_node(sb, letNode, ctxVar, sbVar);
                break;
            case DejaVuWithNode withNode:
                generate_with_node(sb, withNode, ctxVar, sbVar);
                break;
            case DejaVuBlockNode blockNode:
                generate_block_node(sb, blockNode, ctxVar, sbVar);
                break;
            case DejaVuIncludeNode includeNode:
                generate_include_node(sb, includeNode, ctxVar, sbVar);
                break;
            case DejaVuSuperNode:
                generate_super_node(sb, sbVar);
                break;
            case DejaVuRawNode rawNode:
                generate_raw_node(sb, rawNode, ctxVar, sbVar);
                break;
            case DejaVuMatchNode matchNode:
                generate_match_node(sb, matchNode, ctxVar, sbVar);
                break;
            case DejaVuExtendsNode extendsNode:
                generate_extends_node(sb, extendsNode);
                break;
        }
    }

    private void generate_text_node(StringBuilder sb, DejaVuTextNode textNode, string sbVar)
    {
        var escaped = escape_java_string(textNode.text);
        indent(sb);
        sb.AppendLine($"{sbVar}.append(\"{escaped}\");");
    }

    private void generate_code_node(StringBuilder sb, DejaVuCodeNode codeNode, string ctxVar, string sbVar)
    {
        var expr = generate_expression(codeNode.parsed_expression, codeNode.code, ctxVar);
        indent(sb);
        sb.AppendLine($"{sbVar}.append(escapeHtml(String.valueOf({expr})));");
    }

    private void generate_if_node(StringBuilder sb, DejaVuIfNode ifNode, string ctxVar, string sbVar)
    {
        var condition = generate_expression(ifNode.parsed_condition, ifNode.condition, ctxVar);
        indent(sb);
        sb.AppendLine($"if (toBoolean({condition})) {{");

        _indent_level++;
        foreach (var child in ifNode.children) generate_node(sb, child, ctxVar, sbVar);

        _indent_level--;

        foreach (var elseIfNode in ifNode.else_if_nodes)
        {
            var elseIfCondition = generate_expression(elseIfNode.parsed_condition, elseIfNode.condition, ctxVar);
            indent(sb);
            sb.AppendLine($"}} else if (toBoolean({elseIfCondition})) {{");

            _indent_level++;
            foreach (var child in elseIfNode.children) generate_node(sb, child, ctxVar, sbVar);

            _indent_level--;
        }

        if (ifNode.else_children.Count > 0)
        {
            indent(sb);
            sb.AppendLine("} else {");

            _indent_level++;
            foreach (var child in ifNode.else_children) generate_node(sb, child, ctxVar, sbVar);

            _indent_level--;
        }

        indent(sb);
        sb.AppendLine("}");
    }

    private void generate_loop_node(StringBuilder sb, DejaVuLoopNode loopNode, string ctxVar, string sbVar)
    {
        var iterable = generate_expression(loopNode.parsed_expression, loopNode.expression, ctxVar);
        var itemName = loopNode.item_name ?? "item";
        var javaItemName = to_java_identifier(itemName);

        indent(sb);
        sb.AppendLine($"for (Object {javaItemName} : toIterable({iterable})) {{");

        _indent_level++;
        indent(sb);
        sb.AppendLine($"Map<String, Object> __loopCtx = new HashMap<>({ctxVar});");
        indent(sb);
        sb.AppendLine($"__loopCtx.put(\"{itemName}\", {javaItemName});");
        indent(sb);
        sb.AppendLine("__loopCtx.put(\"index\", __loopIndex++);");

        foreach (var child in loopNode.children) generate_node(sb, child, "__loopCtx", sbVar);

        _indent_level--;
        indent(sb);
        sb.AppendLine("}");
    }

    private void generate_let_node(StringBuilder sb, DejaVuLetNode letNode, string ctxVar, string sbVar)
    {
        var value = generate_expression(letNode.parsed_expression, letNode.expression, ctxVar);

        indent(sb);
        sb.AppendLine($"Map<String, Object> __letCtx = new HashMap<>({ctxVar});");
        indent(sb);
        sb.AppendLine($"__letCtx.put(\"{letNode.variable_name}\", {value});");

        foreach (var child in letNode.children) generate_node(sb, child, "__letCtx", sbVar);
    }

    private void generate_with_node(StringBuilder sb, DejaVuWithNode withNode, string ctxVar, string sbVar)
    {
        var obj = generate_expression(withNode.parsed_expression, withNode.expression, ctxVar);

        indent(sb);
        sb.AppendLine($"Object __withObj = {obj};");
        indent(sb);
        sb.AppendLine($"Map<String, Object> __withCtx = new HashMap<>({ctxVar});");
        indent(sb);
        sb.AppendLine("if (__withObj instanceof Map) { __withCtx.putAll((Map<?, ?>) __withObj); }");

        foreach (var child in withNode.children) generate_node(sb, child, "__withCtx", sbVar);
    }

    private void generate_block_node(StringBuilder sb, DejaVuBlockNode blockNode, string ctxVar, string sbVar)
    {
        indent(sb);
        sb.AppendLine($"// block: {blockNode.name}");

        foreach (var child in blockNode.children) generate_node(sb, child, ctxVar, sbVar);
    }

    private void generate_include_node(StringBuilder sb, DejaVuIncludeNode includeNode, string ctxVar, string sbVar)
    {
        var path = includeNode.template_path.Trim('\'', '"');
        indent(sb);
        sb.AppendLine($"{sbVar}.append(renderInclude({ctxVar}, \"{escape_java_string(path)}\"));");
    }

    private void generate_super_node(StringBuilder sb, string sbVar)
    {
        indent(sb);
        sb.AppendLine($"{sbVar}.append(renderSuper(ctx));");
    }

    private void generate_raw_node(StringBuilder sb, DejaVuRawNode rawNode, string ctxVar, string sbVar)
    {
        foreach (var child in rawNode.children)
            if (child is DejaVuTextNode textNode)
            {
                var escaped = escape_java_string(textNode.text);
                indent(sb);
                sb.AppendLine($"{sbVar}.append(\"{escaped}\");");
            }
            else if (child is DejaVuCodeNode codeNode)
            {
                var expr = generate_expression(codeNode.parsed_expression, codeNode.code, ctxVar);
                indent(sb);
                sb.AppendLine($"{sbVar}.append(String.valueOf({expr}));");
            }
    }

    private void generate_match_node(StringBuilder sb, DejaVuMatchNode matchNode, string ctxVar, string sbVar)
    {
        var matchExpr = generate_expression(matchNode.parsed_expression, matchNode.expression, ctxVar);
        indent(sb);
        sb.AppendLine($"Object __matchVal = {matchExpr};");

        var isFirst = true;
        foreach (var child in matchNode.children)
            if (child is DejaVuIfNode ifNode)
            {
                var condition = generate_expression(ifNode.parsed_condition, ifNode.condition, ctxVar);
                var keyword = isFirst ? "if" : "} else if";
                indent(sb);
                sb.AppendLine($"{keyword} (areEqual(__matchVal, {condition})) {{");

                _indent_level++;
                foreach (var ifChild in ifNode.children) generate_node(sb, ifChild, ctxVar, sbVar);

                _indent_level--;
                isFirst = false;
            }

        if (!isFirst)
        {
            indent(sb);
            sb.AppendLine("}");
        }
    }

    private void generate_extends_node(StringBuilder sb, DejaVuExtendsNode extendsNode)
    {
        var parent = extendsNode.parent_template.Trim('\'', '"');
        indent(sb);
        sb.AppendLine($"// extends: {escape_java_string(parent)}");
    }

    private string generate_expression(IExpressionNode? parsedAst, string fallback, string ctxVar)
    {
        if (parsedAst != null) return generate_expression_node(parsedAst, ctxVar);

        return $"evalExpr({ctxVar}, \"{escape_java_string(fallback)}\")";
    }

    private string generate_expression_node(IExpressionNode node, string ctxVar)
    {
        return node switch
        {
            LiteralNode lit => generate_literal(lit),
            IdentifierNode id => $"({ctxVar}.get(\"{id.name}\"))",
            BinaryNode binary => generate_binary(binary, ctxVar),
            UnaryNode unary => generate_unary(unary, ctxVar),
            MemberAccessNode member => generate_member_access(member, ctxVar),
            CallNode call => generate_call(call, ctxVar),
            IndexNode index => generate_index(index, ctxVar),
            PipeNode pipe => generate_pipe(pipe, ctxVar),
            _ => "null"
        };
    }

    private string generate_literal(LiteralNode lit)
    {
        return lit.value switch
        {
            null => "null",
            bool b => b ? "true" : "false",
            double d => d.ToString(CultureInfo.InvariantCulture) + "d",
            string s => $"\"{escape_java_string(s)}\"",
            _ => $"\"{escape_java_string(lit.value.ToString())}\""
        };
    }

    private string generate_binary(BinaryNode binary, string ctxVar)
    {
        var left = generate_expression_node(binary.left, ctxVar);
        var right = generate_expression_node(binary.right, ctxVar);

        return binary.@operator switch
        {
            BinaryOperator.add => $"addObjects({left}, {right})",
            BinaryOperator.subtract => $"subtractObjects({left}, {right})",
            BinaryOperator.multiply => $"multiplyObjects({left}, {right})",
            BinaryOperator.divide => $"divideObjects({left}, {right})",
            BinaryOperator.modulo => $"moduloObjects({left}, {right})",
            BinaryOperator.equal => $"Objects.equals({left}, {right})",
            BinaryOperator.not_equal => $"(!Objects.equals({left}, {right}))",
            BinaryOperator.less_than => $"lessThan({left}, {right})",
            BinaryOperator.less_than_or_equal => $"lessThanOrEqual({left}, {right})",
            BinaryOperator.greater_than => $"greaterThan({left}, {right})",
            BinaryOperator.greater_than_or_equal => $"greaterThanOrEqual({left}, {right})",
            BinaryOperator.and => $"(toBoolean({left}) && toBoolean({right}))",
            BinaryOperator.or => $"(toBoolean({left}) || toBoolean({right}))",
            _ => "null"
        };
    }

    private string generate_unary(UnaryNode unary, string ctxVar)
    {
        var operand = generate_expression_node(unary.operand, ctxVar);
        return unary.@operator switch
        {
            UnaryOperator.negate => $"negateObject({operand})",
            UnaryOperator.not => $"(!toBoolean({operand}))",
            _ => operand
        };
    }

    private string generate_member_access(MemberAccessNode member, string ctxVar)
    {
        var obj = generate_expression_node(member.@object, ctxVar);
        return $"memberAccess({obj}, \"{member.member_name}\")";
    }

    private string generate_call(CallNode call, string ctxVar)
    {
        var func = generate_expression_node(call.function, ctxVar);
        var args = string.Join(", ", call.arguments.Select(a => generate_expression_node(a, ctxVar)));
        return $"callFunction({func}{(string.IsNullOrEmpty(args) ? "" : $", {args}")})";
    }

    private string generate_index(IndexNode index, string ctxVar)
    {
        var obj = generate_expression_node(index.@object, ctxVar);
        var idx = generate_expression_node(index.index, ctxVar);
        return $"indexAccess({obj}, {idx})";
    }

    private string generate_pipe(PipeNode pipe, string ctxVar)
    {
        var left = generate_expression_node(pipe.left, ctxVar);
        var args = string.Join(", ", pipe.arguments.Select(a => generate_expression_node(a, ctxVar)));
        return $"applyFilter(\"{pipe.filter_name}\", {left}{(string.IsNullOrEmpty(args) ? "" : $", {args}")})";
    }

    private void generate_helper_methods(StringBuilder sb)
    {
        if (!options.emit_helpers_inline) return;

        _indent_level = 1;

        indent(sb);
        sb.AppendLine("private int __loopIndex = 0;");
        sb.AppendLine();

        generate_helper_method(sb, "escapeHtml", "String", "String input",
            "if (input == null) return \"\";",
            "return input",
            "    .replace(\"&\", \"&amp;\")",
            "    .replace(\"<\", \"&lt;\")",
            "    .replace(\">\", \"&gt;\")",
            "    .replace(\"\\\"\", \"&quot;\")",
            "    .replace(\"'\", \"&#x27;\");");

        generate_helper_method(sb, "toBoolean", "boolean", "Object value",
            "if (value == null) return false;",
            "if (value instanceof Boolean) return (Boolean) value;",
            "return true;");

        generate_helper_method(sb, "toIterable", "Iterable<?>", "Object value",
            "if (value instanceof Iterable) return (Iterable<?>) value;",
            "if (value instanceof Map) return ((Map<?, ?>) value).values();",
            "return Collections.emptyList();");

        generate_helper_method(sb, "areEqual", "boolean", "Object a, Object b",
            "if (a == null && b == null) return true;",
            "if (a == null || b == null) return false;",
            "return a.equals(b);");

        generate_helper_method(sb, "memberAccess", "Object", "Object obj, String member",
            "if (obj instanceof Map) return ((Map<?, ?>) obj).get(member);",
            "try {",
            "    var field = obj.getClass().getField(member);",
            "    return field.get(obj);",
            "} catch (Exception e) { return null; }");

        generate_helper_method(sb, "indexAccess", "Object", "Object obj, Object index",
            "if (obj instanceof List) { int i = ((Number) index).intValue(); var list = (List<?>) obj; return i >= 0 && i < list.size() ? list.get(i) : null; }",
            "if (obj instanceof Map) return ((Map<?, ?>) obj).get(index);",
            "return null;");

        generate_helper_method(sb, "callFunction", "Object", "Object func, Object... args",
            "if (func instanceof java.util.function.Function) return ((java.util.function.Function<Object, Object>) func).apply(args.length > 0 ? args[0] : null);",
            "return null;");

        generate_helper_method(sb, "addObjects", "Object", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() + ((Number) b).doubleValue();",
            "return String.valueOf(a) + String.valueOf(b);");

        generate_helper_method(sb, "subtractObjects", "Object", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() - ((Number) b).doubleValue();",
            "return 0d;");

        generate_helper_method(sb, "multiplyObjects", "Object", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() * ((Number) b).doubleValue();",
            "return 0d;");

        generate_helper_method(sb, "divideObjects", "Object", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) { double bv = ((Number) b).doubleValue(); return bv != 0 ? ((Number) a).doubleValue() / bv : 0d; }",
            "return 0d;");

        generate_helper_method(sb, "moduloObjects", "Object", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) { double bv = ((Number) b).doubleValue(); return bv != 0 ? ((Number) a).doubleValue() % bv : 0d; }",
            "return 0d;");

        generate_helper_method(sb, "negateObject", "Object", "Object a",
            "if (a instanceof Number) return -((Number) a).doubleValue();",
            "return 0d;");

        generate_helper_method(sb, "lessThan", "boolean", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() < ((Number) b).doubleValue();",
            "return false;");

        generate_helper_method(sb, "lessThanOrEqual", "boolean", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() <= ((Number) b).doubleValue();",
            "return false;");

        generate_helper_method(sb, "greaterThan", "boolean", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() > ((Number) b).doubleValue();",
            "return false;");

        generate_helper_method(sb, "greaterThanOrEqual", "boolean", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() >= ((Number) b).doubleValue();",
            "return false;");

        generate_filter_method(sb);
    }

    private void generate_helper_method(StringBuilder sb, string name, string returnType, string @params,
        params string[] bodyLines)
    {
        indent(sb);
        sb.AppendLine($"private static {returnType} {name}({@params}) {{");
        _indent_level++;
        foreach (var line in bodyLines)
        {
            indent(sb);
            sb.AppendLine(line);
        }

        _indent_level--;
        indent(sb);
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void generate_filter_method(StringBuilder sb)
    {
        indent(sb);
        sb.AppendLine("private static Object applyFilter(String name, Object value, Object... args) {");
        _indent_level++;
        indent(sb);
        sb.AppendLine("switch (name) {");

        var filters = new (string Name, string Body)[]
        {
            ("uppercase", "return String.valueOf(value).toUpperCase();"),
            ("lowercase", "return String.valueOf(value).toLowerCase();"),
            ("trim", "return String.valueOf(value).trim();"),
            ("capitalize",
                "String s = String.valueOf(value); return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);"),
            ("truncate",
                "int len = args.length > 0 ? ((Number) args[0]).intValue() : 30; String s = String.valueOf(value); return s.length() > len ? s.substring(0, len) + \"...\" : s;"),
            ("default", "return (value == null || \"\".equals(value)) ? (args.length > 0 ? args[0] : null) : value;"),
            ("join",
                "if (value instanceof Iterable) { String sep = args.length > 0 ? String.valueOf(args[0]) : \", \"; return StreamSupport.stream(((Iterable<?>) value).spliterator(), false).map(String::valueOf).collect(Collectors.joining(sep)); } return String.valueOf(value);"),
            ("length",
                "if (value instanceof Collection) return ((Collection<?>) value).size(); return String.valueOf(value).length();"),
            ("first",
                "if (value instanceof Iterable) { var it = ((Iterable<?>) value).iterator(); return it.hasNext() ? it.next() : null; } return null;"),
            ("last",
                "if (value instanceof List) { var list = (List<?>) value; return list.isEmpty() ? null : list.get(list.size() - 1); } return null;"),
            ("reverse",
                "if (value instanceof List) { var list = new ArrayList<>((List<?>) value); Collections.reverse(list); return list; } return new StringBuilder(String.valueOf(value)).reverse().toString();"),
            ("sort",
                "if (value instanceof List) { var list = new ArrayList<>((List<?>) value); Collections.sort(list, (a, b) -> String.valueOf(a).compareTo(String.valueOf(b))); return list; } return value;"),
            ("strip_html", "return String.valueOf(value).replaceAll(\"<[^>]*>\", \"\");"),
            ("escape", "return escapeHtml(String.valueOf(value));"),
            ("newline_to_br", "return String.valueOf(value).replace(\"\\n\", \"<br/>\");"),
            ("abs", "return value instanceof Number ? Math.abs(((Number) value).doubleValue()) : value;"),
            ("round",
                "int d = args.length > 0 ? ((Number) args[0]).intValue() : 0; return value instanceof Number ? Math.round(((Number) value).doubleValue() * Math.pow(10, d)) / Math.pow(10, d) : value;"),
            ("floor", "return value instanceof Number ? Math.floor(((Number) value).doubleValue()) : value;"),
            ("ceil", "return value instanceof Number ? Math.ceil(((Number) value).doubleValue()) : value;"),
            ("count",
                "if (value instanceof Collection) return ((Collection<?>) value).size(); if (value instanceof String) return ((String) value).length(); return 0;"),
            ("safe", "return value;"),
            ("date",
                "if (value instanceof java.time.temporal.Temporal) return value.toString(); return String.valueOf(value);"),
            ("datetime",
                "if (value instanceof java.time.temporal.Temporal) return value.toString(); return String.valueOf(value);")
        };

        foreach (var (name, body) in filters)
        {
            _indent_level++;
            indent(sb);
            sb.AppendLine($"case \"{name}\": {body}");
            _indent_level--;
        }

        indent(sb);
        sb.AppendLine("default: return value;");
        indent(sb);
        sb.AppendLine("}");

        _indent_level--;
        indent(sb);
        sb.AppendLine("}");
    }

    private void indent(StringBuilder sb)
    {
        sb.Append(new string(' ', _indent_level * options.indent_size));
    }

    private static string escape_java_string(string? input)
    {
        if (input == null) return string.Empty;

        return input
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    private static string to_java_identifier(string name)
    {
        if (string.IsNullOrEmpty(name)) return "item";

        if (char.IsDigit(name[0])) return "_" + name;

        return name;
    }
}