using System.Globalization;
using System.Text;
using Std.Data.Text.DejaVu.Expressions;

namespace Std.Data.Text.DejaVu.CodeGen;

/// <summary>
///     TypeScript 代码生成器——将 DejaVu 模板 AST 转译为 TypeScript 渲染函数源码。
///     输出可在浏览器/Node.js 中直接执行的 TypeScript 代码。
/// </summary>
public sealed class TypeScriptCodeGenerator
{
    private int _indent_level;


    /// <summary>
    ///     创建 TypeScript 代码生成器
    /// </summary>
    public TypeScriptCodeGenerator()
    {
        options = new TypeScriptGeneratorOptions();
    }


    /// <summary>
    ///     创建 TypeScript 代码生成器
    /// </summary>
    /// <param name="options">生成选项。</param>
    public TypeScriptCodeGenerator(TypeScriptGeneratorOptions options)
    {
        this.options = options;
    }


    /// <summary>
    ///     生成选项
    /// </summary>
    public TypeScriptGeneratorOptions options { get; }


    /// <summary>
    ///     生成 TypeScript 渲染模块源码
    /// </summary>
    /// <param name="nodes">优化后的模板节点列表。</param>
    /// <param name="templateName">模板名称（用于函数命名）。</param>
    /// <returns>TypeScript 源码。</returns>
    public string generate(IReadOnlyList<DejaVuTemplateNode> nodes, string templateName = "render")
    {
        var sb = new StringBuilder();

        generate_header(sb);
        generate_render_function(sb, nodes, templateName);
        generate_helper_functions(sb);

        return sb.ToString();
    }

    private void generate_header(StringBuilder sb)
    {
        if (options.include_header)
        {
            sb.AppendLine("// Auto-generated by DejaVu TypeScript Code Generator");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine();
        }

        if (options.emit_helpers_inline)
        {
            sb.AppendLine("type TemplateContext = Record<string, any>;");
            sb.AppendLine();
        }
    }

    private void generate_render_function(StringBuilder sb, IReadOnlyList<DejaVuTemplateNode> nodes, string funcName)
    {
        sb.AppendLine($"export function {funcName}(ctx: TemplateContext): string {{");
        _indent_level = 1;

        indent(sb);
        sb.AppendLine("const parts: string[] = [];");

        foreach (var node in nodes) generate_node(sb, node);

        indent(sb);
        sb.AppendLine("return parts.join('');");

        _indent_level = 0;
        sb.AppendLine("}");
    }

    private void generate_node(StringBuilder sb, DejaVuTemplateNode node)
    {
        switch (node)
        {
            case DejaVuTextNode textNode:
                generate_text_node(sb, textNode);
                break;
            case DejaVuCodeNode codeNode:
                generate_code_node(sb, codeNode);
                break;
            case DejaVuIfNode ifNode:
                generate_if_node(sb, ifNode);
                break;
            case DejaVuLoopNode loopNode:
                generate_loop_node(sb, loopNode);
                break;
            case DejaVuLetNode letNode:
                generate_let_node(sb, letNode);
                break;
            case DejaVuWithNode withNode:
                generate_with_node(sb, withNode);
                break;
            case DejaVuBlockNode blockNode:
                generate_block_node(sb, blockNode);
                break;
            case DejaVuExtendsNode extendsNode:
                generate_extends_node(sb, extendsNode);
                break;
            case DejaVuIncludeNode includeNode:
                generate_include_node(sb, includeNode);
                break;
            case DejaVuSuperNode:
                generate_super_node(sb);
                break;
            case DejaVuRawNode rawNode:
                generate_raw_node(sb, rawNode);
                break;
            case DejaVuMatchNode matchNode:
                generate_match_node(sb, matchNode);
                break;
        }
    }

    private void generate_text_node(StringBuilder sb, DejaVuTextNode textNode)
    {
        var escaped = escape_ts_string(textNode.text);
        indent(sb);
        sb.AppendLine($"parts.push(\"{escaped}\");");
    }

    private void generate_code_node(StringBuilder sb, DejaVuCodeNode codeNode)
    {
        var expr = generate_expression(codeNode.parsed_expression, codeNode.code);
        indent(sb);
        sb.AppendLine($"parts.push(escapeHtml(String({expr} ?? '')));");
    }

    private void generate_if_node(StringBuilder sb, DejaVuIfNode ifNode)
    {
        var condition = generate_expression(ifNode.parsed_condition, ifNode.condition);
        indent(sb);
        sb.AppendLine($"if (toBoolean({condition})) {{");

        _indent_level++;
        foreach (var child in ifNode.children) generate_node(sb, child);

        _indent_level--;

        foreach (var elseIfNode in ifNode.else_if_nodes)
        {
            var elseIfCondition = generate_expression(elseIfNode.parsed_condition, elseIfNode.condition);
            indent(sb);
            sb.AppendLine($"}} else if (toBoolean({elseIfCondition})) {{");

            _indent_level++;
            foreach (var child in elseIfNode.children) generate_node(sb, child);

            _indent_level--;
        }

        if (ifNode.else_children.Count > 0)
        {
            indent(sb);
            sb.AppendLine("} else {");

            _indent_level++;
            foreach (var child in ifNode.else_children) generate_node(sb, child);

            _indent_level--;
        }

        indent(sb);
        sb.AppendLine("}");
    }

    private void generate_loop_node(StringBuilder sb, DejaVuLoopNode loopNode)
    {
        var iterable = generate_expression(loopNode.parsed_expression, loopNode.expression);
        var itemName = loopNode.item_name ?? "item";

        indent(sb);
        sb.AppendLine($"for (const {itemName} of (toIterable({iterable}))) {{");

        _indent_level++;
        indent(sb);
        sb.AppendLine("const __loopCtx = { ...ctx, " + itemName + ", index: __loopIndex++ };");

        foreach (var child in loopNode.children) generate_node_with_ctx(sb, child, "__loopCtx");

        _indent_level--;
        indent(sb);
        sb.AppendLine("}");
    }

    private void generate_let_node(StringBuilder sb, DejaVuLetNode letNode)
    {
        var value = generate_expression(letNode.parsed_expression, letNode.expression);
        indent(sb);
        sb.AppendLine($"const __letCtx = {{ ...ctx, {letNode.variable_name}: {value} }};");

        foreach (var child in letNode.children) generate_node_with_ctx(sb, child, "__letCtx");
    }

    private void generate_with_node(StringBuilder sb, DejaVuWithNode withNode)
    {
        var obj = generate_expression(withNode.parsed_expression, withNode.expression);
        indent(sb);
        sb.AppendLine($"const __withObj = {obj};");

        indent(sb);
        sb.AppendLine("const __withCtx = { ...ctx, ...(__withObj instanceof Object ? __withObj : {}) };");

        foreach (var child in withNode.children) generate_node_with_ctx(sb, child, "__withCtx");
    }

    private void generate_block_node(StringBuilder sb, DejaVuBlockNode blockNode)
    {
        indent(sb);
        sb.AppendLine($"// block: {blockNode.name}");

        foreach (var child in blockNode.children) generate_node(sb, child);
    }

    private void generate_extends_node(StringBuilder sb, DejaVuExtendsNode extendsNode)
    {
        var parent = extendsNode.parent_template.Trim('\'', '"');
        indent(sb);
        sb.AppendLine($"// extends: {escape_ts_string(parent)}");
    }

    private void generate_include_node(StringBuilder sb, DejaVuIncludeNode includeNode)
    {
        var path = includeNode.template_path.Trim('\'', '"');
        indent(sb);
        sb.AppendLine($"parts.push(renderInclude(ctx, \"{escape_ts_string(path)}\"));");
    }

    private void generate_super_node(StringBuilder sb)
    {
        indent(sb);
        sb.AppendLine("parts.push(renderSuper(ctx));");
    }

    private void generate_raw_node(StringBuilder sb, DejaVuRawNode rawNode)
    {
        foreach (var child in rawNode.children)
            if (child is DejaVuTextNode textNode)
            {
                var escaped = escape_ts_string(textNode.text);
                indent(sb);
                sb.AppendLine($"parts.push(\"{escaped}\");");
            }
            else if (child is DejaVuCodeNode codeNode)
            {
                var expr = generate_expression(codeNode.parsed_expression, codeNode.code);
                indent(sb);
                sb.AppendLine($"parts.push(String({expr} ?? ''));");
            }
    }

    private void generate_match_node(StringBuilder sb, DejaVuMatchNode matchNode)
    {
        var matchExpr = generate_expression(matchNode.parsed_expression, matchNode.expression);
        indent(sb);
        sb.AppendLine($"const __matchVal = {matchExpr};");

        var isFirst = true;
        foreach (var child in matchNode.children)
            if (child is DejaVuIfNode ifNode)
            {
                var condition = generate_expression(ifNode.parsed_condition, ifNode.condition);
                var keyword = isFirst ? "if" : "} else if";
                indent(sb);
                sb.AppendLine($"{keyword} (areEqual(__matchVal, {condition})) {{");

                _indent_level++;
                foreach (var ifChild in ifNode.children) generate_node(sb, ifChild);

                _indent_level--;
                isFirst = false;
            }

        if (!isFirst)
        {
            indent(sb);
            sb.AppendLine("}");
        }
    }

    private void generate_node_with_ctx(StringBuilder sb, DejaVuTemplateNode node, string ctxVar)
    {
        switch (node)
        {
            case DejaVuTextNode textNode:
                var escaped = escape_ts_string(textNode.text);
                indent(sb);
                sb.AppendLine($"parts.push(\"{escaped}\");");
                break;
            case DejaVuCodeNode codeNode:
                var expr = generate_expression(codeNode.parsed_expression, codeNode.code);
                indent(sb);
                sb.AppendLine($"parts.push(escapeHtml(String({expr} ?? '')));");
                break;
            default:
                indent(sb);
                sb.AppendLine($"// TODO: nested {node.node_type} in scoped context");
                break;
        }
    }

    private string generate_expression(IExpressionNode? parsedAst, string fallback)
    {
        if (parsedAst != null) return generate_expression_node(parsedAst);

        return generate_fallback_expression(fallback);
    }

    private string generate_expression_node(IExpressionNode node)
    {
        return node switch
        {
            LiteralNode lit => generate_literal(lit),
            IdentifierNode id => $"ctx[\"{id.name}\"]",
            BinaryNode binary => generate_binary(binary),
            UnaryNode unary => generate_unary(unary),
            MemberAccessNode member => generate_member_access(member),
            CallNode call => generate_call(call),
            IndexNode index => generate_index(index),
            PipeNode pipe => generate_pipe(pipe),
            _ => "undefined"
        };
    }

    private string generate_literal(LiteralNode lit)
    {
        return lit.value switch
        {
            null => "null",
            bool b => b ? "true" : "false",
            double d => d.ToString(CultureInfo.InvariantCulture),
            string s => $"\"{escape_ts_string(s)}\"",
            _ => $"\"{escape_ts_string(lit.value.ToString())}\""
        };
    }

    private string generate_binary(BinaryNode binary)
    {
        var left = generate_expression_node(binary.left);
        var right = generate_expression_node(binary.right);

        return binary.@operator switch
        {
            BinaryOperator.add => $"({left} + {right})",
            BinaryOperator.subtract => $"({left} - {right})",
            BinaryOperator.multiply => $"({left} * {right})",
            BinaryOperator.divide => $"({left} / {right})",
            BinaryOperator.modulo => $"({left} % {right})",
            BinaryOperator.equal => $"({left} === {right})",
            BinaryOperator.not_equal => $"({left} !== {right})",
            BinaryOperator.less_than => $"({left} < {right})",
            BinaryOperator.less_than_or_equal => $"({left} <= {right})",
            BinaryOperator.greater_than => $"({left} > {right})",
            BinaryOperator.greater_than_or_equal => $"({left} >= {right})",
            BinaryOperator.and => $"({left} && {right})",
            BinaryOperator.or => $"({left} || {right})",
            _ => "undefined"
        };
    }

    private string generate_unary(UnaryNode unary)
    {
        var operand = generate_expression_node(unary.operand);
        return unary.@operator switch
        {
            UnaryOperator.negate => $"(-{operand})",
            UnaryOperator.not => $"(!{operand})",
            _ => operand
        };
    }

    private string generate_member_access(MemberAccessNode member)
    {
        var obj = generate_expression_node(member.@object);
        return $"{obj}[\"{member.member_name}\"]";
    }

    private string generate_call(CallNode call)
    {
        var func = generate_expression_node(call.function);
        var args = string.Join(", ", call.arguments.Select(generate_expression_node));
        return $"(typeof {func} === 'function' ? {func}({args}) : undefined)";
    }

    private string generate_index(IndexNode index)
    {
        var obj = generate_expression_node(index.@object);
        var idx = generate_expression_node(index.index);
        return $"{obj}[{idx}]";
    }

    private string generate_pipe(PipeNode pipe)
    {
        var left = generate_expression_node(pipe.left);
        var args = string.Join(", ", pipe.arguments.Select(generate_expression_node));
        return $"applyFilter(\"{pipe.filter_name}\", {left}{(string.IsNullOrEmpty(args) ? "" : $", {args}")})";
    }

    private string generate_fallback_expression(string expression)
    {
        return $"evalExpr(ctx, \"{escape_ts_string(expression)}\")";
    }

    private void generate_helper_functions(StringBuilder sb)
    {
        if (!options.emit_helpers_inline) return;

        sb.AppendLine();
        sb.AppendLine("function escapeHtml(input: string): string {");
        sb.AppendLine("    return input");
        sb.AppendLine("        .replace(/&/g, '&amp;')");
        sb.AppendLine("        .replace(/</g, '&lt;')");
        sb.AppendLine("        .replace(/>/g, '&gt;')");
        sb.AppendLine("        .replace(/\"/g, '&quot;')");
        sb.AppendLine("        .replace(/'/g, '&#x27;');");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("function toBoolean(value: any): boolean {");
        sb.AppendLine("    if (value === null || value === undefined) return false;");
        sb.AppendLine("    if (typeof value === 'boolean') return value;");
        sb.AppendLine("    return true;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("function toIterable(value: any): any[] {");
        sb.AppendLine("    if (Array.isArray(value)) return value;");
        sb.AppendLine("    if (value instanceof Object) return Object.entries(value);");
        sb.AppendLine("    return [];");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("function areEqual(a: any, b: any): boolean {");
        sb.AppendLine("    if (a === b) return true;");
        sb.AppendLine("    if (a === null || b === null) return false;");
        sb.AppendLine("    return String(a) === String(b);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("function applyFilter(name: string, value: any, ...args: any[]): any {");
        sb.AppendLine("    const filters: Record<string, (v: any, ...a: any[]) => any> = {");
        sb.AppendLine("        uppercase: (v) => String(v).toUpperCase(),");
        sb.AppendLine("        lowercase: (v) => String(v).toLowerCase(),");
        sb.AppendLine("        trim: (v) => String(v).trim(),");
        sb.AppendLine(
            "        capitalize: (v) => { const s = String(v); return s.charAt(0).toUpperCase() + s.slice(1); },");
        sb.AppendLine(
            "        truncate: (v, len) => { const s = String(v); return s.length > len ? s.slice(0, len) + '...' : s; },");
        sb.AppendLine("        default: (v, d) => (v === null || v === undefined || v === '') ? d : v,");
        sb.AppendLine("        join: (v, sep) => Array.isArray(v) ? v.join(sep ?? ', ') : String(v),");
        sb.AppendLine("        length: (v) => Array.isArray(v) ? v.length : String(v).length,");
        sb.AppendLine("        first: (v) => Array.isArray(v) ? v[0] : undefined,");
        sb.AppendLine("        last: (v) => Array.isArray(v) ? v[v.length - 1] : undefined,");
        sb.AppendLine(
            "        reverse: (v) => Array.isArray(v) ? [...v].reverse() : String(v).split('').reverse().join(''),");
        sb.AppendLine("        sort: (v) => Array.isArray(v) ? [...v].sort() : v,");
        sb.AppendLine("        strip_html: (v) => String(v).replace(/<[^>]*>/g, ''),");
        sb.AppendLine("        escape: (v) => escapeHtml(String(v)),");
        sb.AppendLine("        newline_to_br: (v) => String(v).replace(/\\n/g, '<br/>'),");
        sb.AppendLine("    };");
        sb.AppendLine("    const fn = filters[name];");
        sb.AppendLine("    return fn ? fn(value, ...args) : value;");
        sb.AppendLine("}");
    }

    private void indent(StringBuilder sb)
    {
        sb.Append(new string(' ', _indent_level * options.indent_size));
    }

    private static string escape_ts_string(string? input)
    {
        if (input == null) return string.Empty;

        return input
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}