using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator.Storage;

/// <summary>
///     为标记了 <c>[Entity]</c> 特性的类自动生成数据库键构建器和仓储代码，
///     提供实体类型与存储层之间的映射和访问能力。
/// </summary>
[Generator]
public sealed class StorageGenerator : IIncrementalGenerator
{
    private const string _entity_attribute_full_name = "Sonic.Standard.Data.EntityAttribute";
    private const string _key_attribute_full_name = "Sonic.Standard.Data.Key.KeyAttribute";
    private const string _index_attribute_full_name = "Sonic.Standard.Data.Index.IndexAttribute";

    /// <summary>
    ///     初始化增量源代码生成管道。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var entities = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _entity_attribute_full_name,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => transform_entity(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value)
            .Collect();

        context.RegisterSourceOutput(entities, generate_source);
    }

    /// <summary>
    ///     提取标记了 <c>[Entity]</c> 特性的类型信息。
    /// </summary>
    private static StorageEntityInfo? transform_entity(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        var typeSymbol = (INamedTypeSymbol)context.TargetSymbol;

        StoragePropertyInfo? keyProperty = null;
        var indexProperties = new List<StoragePropertyInfo>();

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member.IsStatic) continue;

            if (member.DeclaredAccessibility != Accessibility.Public) continue;

            if (member is not IPropertySymbol prop) continue;

            if (prop.IsWriteOnly) continue;

            var hasKeyAttr = prop.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
                $"global::{_key_attribute_full_name}");

            if (hasKeyAttr)
                keyProperty = new StoragePropertyInfo(
                    prop.Name,
                    prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));

            var hasIndexAttr = prop.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
                $"global::{_index_attribute_full_name}");

            if (hasIndexAttr)
                indexProperties.Add(new StoragePropertyInfo(
                    prop.Name,
                    prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
        }

        if (keyProperty is null) return null;

        return new StorageEntityInfo(
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.ContainingNamespace?.ToDisplayString(),
            keyProperty.Value,
            indexProperties);
    }

    /// <summary>
    ///     生成所有实体的数据库键构建器和仓储源代码。
    /// </summary>
    private static void generate_source(SourceProductionContext context, ImmutableArray<StorageEntityInfo> entityInfos)
    {
        if (entityInfos.IsEmpty) return;

        var keyBuilderSource = generate_key_builder_source();
        context.AddSource("DatabaseKeyBuilder.g.cs", SourceText.From(keyBuilderSource, Encoding.UTF8));

        foreach (var info in entityInfos)
        {
            var sourceText = generate_repository_source(info);
            var hintName = $"{info.type_name}.Repository.g.cs";
            context.AddSource(hintName, SourceText.From(sourceText, Encoding.UTF8));
        }
    }

    /// <summary>
    ///     生成数据库键构建器的源代码。
    /// </summary>
    private static string generate_key_builder_source()
    {
        var sb = new SourceTextBuilder();
        sb.append_line("// <auto-generated />");
        sb.append_line("#nullable enable");
        sb.append_line();
        sb.append_line("namespace Sonic.Standard.Database;");
        sb.append_line();
        sb.append_line("/// <summary>");
        sb.append_line("/// 实体键构建器，根据实体类型和主键值构建数据库键。");
        sb.append_line("/// </summary>");
        sb.append_line("public static class DatabaseKeyBuilder");
        using (sb.block())
        {
            generate_build_method(sb);
            sb.append_line();
            generate_build_index_key_method(sb);
        }

        return sb.ToString();
    }

    /// <summary>
    ///     生成 <c>Build&lt;T&gt;</c> 方法。
    /// </summary>
    private static void generate_build_method(SourceTextBuilder sb)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 根据实体类型 T 和主键值构建数据库键。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"pkValue\">主键值。</param>");
        sb.append_line("/// <returns>构建的数据库键。</returns>");
        sb.append_line("public static global::System.ReadOnlyMemory<byte> Build<T>(object pkValue)");
        using (sb.block())
        {
            sb.append_line("var raw = typeof(T).FullName! + ((char)0) + pkValue;");
            sb.append_line("return global::System.Text.Encoding.UTF8.GetBytes(raw);");
        }
    }

    /// <summary>
    ///     生成 <c>BuildIndexKey&lt;T&gt;</c> 方法。
    /// </summary>
    private static void generate_build_index_key_method(SourceTextBuilder sb)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 根据实体类型 T、索引名称和索引值构建索引键。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"indexName\">索引名称。</param>");
        sb.append_line("/// <param name=\"indexValue\">索引值。</param>");
        sb.append_line("/// <returns>构建的索引键。</returns>");
        sb.append_line(
            "public static global::System.ReadOnlyMemory<byte> BuildIndexKey<T>(string indexName, object indexValue)");
        using (sb.block())
        {
            sb.append_line("var raw = typeof(T).FullName! + ((char)0) + indexName + ((char)0) + indexValue;");
            sb.append_line("return global::System.Text.Encoding.UTF8.GetBytes(raw);");
        }
    }

    /// <summary>
    ///     生成单个实体的仓储接口和实现源代码。
    /// </summary>
    private static string generate_repository_source(StorageEntityInfo info)
    {
        var sb = new SourceTextBuilder();
        sb.append_line("// <auto-generated />");
        sb.append_line("#nullable enable");
        sb.append_line();
        sb.append_line("namespace Sonic.Standard.Database;");
        sb.append_line();
        generate_repository_interface(sb, info);
        sb.append_line();
        generate_repository_implementation(sb, info);

        return sb.ToString();
    }

    /// <summary>
    ///     生成仓储接口。
    /// </summary>
    private static void generate_repository_interface(SourceTextBuilder sb, StorageEntityInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line($"/// <c>{info.type_name}</c> 实体的仓储接口。");
        sb.append_line("/// </summary>");
        sb.append_line($"public interface I{info.type_name}Repository");
        using (sb.block())
        {
            generate_interface_get_method(sb, info);
            sb.append_line();
            generate_interface_save_method(sb, info);
            sb.append_line();
            generate_interface_delete_method(sb, info);

            foreach (var indexProp in info.index_properties)
            {
                sb.append_line();
                generate_interface_find_by_index_method(sb, info, indexProp);
            }
        }
    }

    /// <summary>
    ///     生成接口中的获取方法声明。
    /// </summary>
    private static void generate_interface_get_method(SourceTextBuilder sb, StorageEntityInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 根据主键获取实体。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"key\">主键值。</param>");
        sb.append_line("/// <returns>实体实例，未找到时返回 null。</returns>");
        sb.append_line($"{info.fully_qualified_name}? get(object key);");
    }

    /// <summary>
    ///     生成接口中的保存方法声明。
    /// </summary>
    private static void generate_interface_save_method(SourceTextBuilder sb, StorageEntityInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 保存实体。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"entity\">要保存的实体。</param>");
        sb.append_line($"void save({info.fully_qualified_name} entity);");
    }

    /// <summary>
    ///     生成接口中的删除方法声明。
    /// </summary>
    private static void generate_interface_delete_method(SourceTextBuilder sb, StorageEntityInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 根据主键删除实体。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"key\">主键值。</param>");
        sb.append_line("void delete(object key);");
    }

    /// <summary>
    ///     生成接口中的索引查找方法声明。
    /// </summary>
    private static void generate_interface_find_by_index_method(SourceTextBuilder sb, StorageEntityInfo info,
        StoragePropertyInfo indexProp)
    {
        var snakeName = to_snake_case(indexProp.name);

        sb.append_line("/// <summary>");
        sb.append_line($"/// 根据 <c>{indexProp.name}</c> 索引查找实体。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"indexValue\">索引值。</param>");
        sb.append_line("/// <returns>匹配的实体列表。</returns>");
        sb.append_line(
            $"global::System.Collections.Generic.IEnumerable<{info.fully_qualified_name}> find_by_{snakeName}(object indexValue);");
    }

    /// <summary>
    ///     生成仓储实现类。
    /// </summary>
    private static void generate_repository_implementation(SourceTextBuilder sb, StorageEntityInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line($"/// <c>{info.type_name}</c> 实体的仓储实现。");
        sb.append_line("/// </summary>");
        sb.append_line($"public sealed class {info.type_name}Repository : I{info.type_name}Repository");
        using (sb.block())
        {
            generate_engine_field(sb);
            sb.append_line();
            generate_constructor(sb, info);
            sb.append_line();
            generate_impl_get_method(sb, info);
            sb.append_line();
            generate_impl_save_method(sb, info);
            sb.append_line();
            generate_impl_delete_method(sb, info);

            foreach (var indexProp in info.index_properties)
            {
                sb.append_line();
                generate_impl_find_by_index_method(sb, info, indexProp);
            }
        }
    }

    /// <summary>
    ///     生成存储引擎字段。
    /// </summary>
    private static void generate_engine_field(SourceTextBuilder sb)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 存储引擎实例。");
        sb.append_line("/// </summary>");
        sb.append_line("private readonly global::Sonic.Standard.Database.IStorageEngine _engine;");
    }

    /// <summary>
    ///     生成构造函数。
    /// </summary>
    private static void generate_constructor(SourceTextBuilder sb, StorageEntityInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line($"/// 初始化 <c>{info.type_name}Repository</c> 的新实例。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"engine\">存储引擎实例。</param>");
        sb.append_line($"public {info.type_name}Repository(global::Sonic.Standard.Database.IStorageEngine engine)");
        using (sb.block())
        {
            sb.append_line("_engine = engine;");
        }
    }

    /// <summary>
    ///     生成实现中的获取方法。
    /// </summary>
    private static void generate_impl_get_method(SourceTextBuilder sb, StorageEntityInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 根据主键获取实体。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"key\">主键值。</param>");
        sb.append_line("/// <returns>实体实例，未找到时返回 null。</returns>");
        sb.append_line($"public {info.fully_qualified_name}? get(object key)");
        using (sb.block())
        {
            sb.append_line($"var dbKey = DatabaseKeyBuilder.Build<{info.fully_qualified_name}>(key);");
            sb.append_line($"return _engine.get<{info.fully_qualified_name}>(dbKey);");
        }
    }

    /// <summary>
    ///     生成实现中的保存方法。
    /// </summary>
    private static void generate_impl_save_method(SourceTextBuilder sb, StorageEntityInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 保存实体。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"entity\">要保存的实体。</param>");
        sb.append_line($"public void save({info.fully_qualified_name} entity)");
        using (sb.block())
        {
            sb.append_line(
                $"var dbKey = DatabaseKeyBuilder.Build<{info.fully_qualified_name}>(entity.{info.key_property.name});");
            sb.append_line("_engine.save(dbKey, entity);");
        }
    }

    /// <summary>
    ///     生成实现中的删除方法。
    /// </summary>
    private static void generate_impl_delete_method(SourceTextBuilder sb, StorageEntityInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 根据主键删除实体。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"key\">主键值。</param>");
        sb.append_line("public void delete(object key)");
        using (sb.block())
        {
            sb.append_line($"var dbKey = DatabaseKeyBuilder.Build<{info.fully_qualified_name}>(key);");
            sb.append_line("_engine.delete(dbKey);");
        }
    }

    /// <summary>
    ///     生成实现中的索引查找方法。
    /// </summary>
    private static void generate_impl_find_by_index_method(SourceTextBuilder sb, StorageEntityInfo info,
        StoragePropertyInfo indexProp)
    {
        var snakeName = to_snake_case(indexProp.name);

        sb.append_line("/// <summary>");
        sb.append_line($"/// 根据 <c>{indexProp.name}</c> 索引查找实体。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"indexValue\">索引值。</param>");
        sb.append_line("/// <returns>匹配的实体列表。</returns>");
        sb.append_line(
            $"public global::System.Collections.Generic.IEnumerable<{info.fully_qualified_name}> find_by_{snakeName}(object indexValue)");
        using (sb.block())
        {
            sb.append_line(
                $"var indexKey = DatabaseKeyBuilder.BuildIndexKey<{info.fully_qualified_name}>(\"{indexProp.name}\", indexValue);");
            sb.append_line($"return _engine.find_by_index<{info.fully_qualified_name}>(indexKey);");
        }
    }

    /// <summary>
    ///     将 PascalCase 名称转换为 snake_case。
    /// </summary>
    private static string to_snake_case(string name)
    {
        var sb = new StringBuilder(name.Length + 4);

        for (var i = 0; i < name.Length; i++)
        {
            var c = name[i];

            if (char.IsUpper(c))
            {
                if (i > 0) sb.Append('_');

                sb.Append(char.ToLowerInvariant(c));
            }
            else
            {
                sb.Append(c);
            }
        }

        return sb.ToString();
    }
}