<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <RootNamespace>Std.Template.Deploy</RootNamespace>
        <AssemblyName>Sonic.Standard.Template.Deploy</AssemblyName>
        <PackageId>Sonic.Standard.Template.Deploy</PackageId>
        <Version>0.1.0</Version>
        <Authors>NyarVM</Authors>
        <Description>部署工具</Description>
        <PackageProjectUrl>https://github.com/nyar-vm/DejavuEngine</PackageProjectUrl>
        <RepositoryUrl>https://github.com/nyar-vm/DejavuEngine</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>template;deploy</PackageTags>
            <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

</Project>
