<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <PackageId>Sonic.Standard.Data.Text.Wit</PackageId>
        <RootNamespace>Oak.Wit</RootNamespace>
        <AssemblyName>Sonic.Standard.Data.Text.Wit</AssemblyName>
        <Authors>Nyar Team - Oak Group</Authors>
        <Description>WIT 文本编解码 — WebAssembly Interface Type</Description>
            <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Sonic.Standard.Data.Text\Sonic.Standard.Data.Text.csproj"/>
    </ItemGroup>
</Project>