using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     为标记了 <c>[GenerateMatch]</c> 特性的类型自动生成代数数据类型的模式匹配代码，
///     包括 <c>Match</c> 方法、<c>IsXxx</c> 属性和 <c>AsXxx</c> 属性。
/// </summary>
[Generator]
public sealed class AdtGenerator : IIncrementalGenerator
{
    private const string _generate_match_attribute_full_name = "Sonic.Standard.Collection.ADT.GenerateMatchAttribute";
    private const string _union_case_attribute_full_name = "Sonic.Standard.Collection.ADT.UnionCaseAttribute";

    /// <summary>
    ///     初始化增量源代码生成管道。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _generate_match_attribute_full_name,
                static (node, _) => node is TypeDeclarationSyntax typeDecl &&
                                    typeDecl.Modifiers.Any(SyntaxKind.PartialKeyword),
                static (ctx, ct) => transform_adt(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value)
            .Collect();

        context.RegisterSourceOutput(targetTypes, generate_source);
    }

    /// <summary>
    ///     提取需要生成 ADT 模式匹配代码的类型信息。
    /// </summary>
    private static AdtTypeInfo? transform_adt(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        var typeSymbol = (INamedTypeSymbol)context.TargetSymbol;

        var cases = extract_union_cases(typeSymbol);

        if (cases.Count == 0) return null;

        return new AdtTypeInfo(
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.ContainingNamespace?.ToDisplayString(),
            typeSymbol.TypeKind == TypeKind.Struct,
            cases);
    }

    /// <summary>
    ///     提取类型中所有标记了 <c>[UnionCase]</c> 特性的成员信息。
    /// </summary>
    private static List<UnionCaseInfo> extract_union_cases(INamedTypeSymbol typeSymbol)
    {
        var cases = new List<UnionCaseInfo>();

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member.IsStatic) continue;

            if (member.DeclaredAccessibility != Accessibility.Public) continue;

            var unionCaseAttr = member.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
                $"global::{_union_case_attribute_full_name}");

            if (unionCaseAttr is null) continue;

            ITypeSymbol caseType;

            if (member is IPropertySymbol prop)
                caseType = prop.Type;
            else if (member is IFieldSymbol field)
                caseType = field.Type;
            else
                continue;

            var caseName = member.Name;
            string? tagValue = null;

            foreach (var named in unionCaseAttr.NamedArguments)
                if (named is { Key: "tag", Value.Value: string t })
                    tagValue = t;

            cases.Add(new UnionCaseInfo(
                caseName,
                caseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                caseType.Name,
                tagValue));
        }

        return cases;
    }

    /// <summary>
    ///     生成所有类型的 ADT 模式匹配源代码。
    /// </summary>
    private static void generate_source(SourceProductionContext context, ImmutableArray<AdtTypeInfo> typeInfos)
    {
        foreach (var info in typeInfos)
        {
            var sourceText = generate_adt_source(info);
            var hintName = $"{info.type_name}.ADT.g.cs";
            context.AddSource(hintName, SourceText.From(sourceText, Encoding.UTF8));
        }
    }

    /// <summary>
    ///     生成单个类型的 ADT 模式匹配源代码。
    /// </summary>
    private static string generate_adt_source(AdtTypeInfo info)
    {
        var sb = new SourceTextBuilder();
        sb.append_line("// <auto-generated />");
        sb.append_line("#nullable enable");
        sb.append_line();

        if (!string.IsNullOrEmpty(info.namespace_name))
        {
            sb.append_line($"namespace {info.namespace_name};");
            sb.append_line();
        }

        var typeKeyword = info.is_struct ? "partial struct" : "partial class";
        sb.append_line($"{typeKeyword} {info.type_name}");
        using (sb.block())
        {
            generate_match_method(sb, info);
            sb.append_line();
            generate_is_properties(sb, info);
            sb.append_line();
            generate_as_properties(sb, info);
        }

        return sb.ToString();
    }

    /// <summary>
    ///     生成 <c>Match</c> 方法，对联合类型进行模式匹配。
    /// </summary>
    private static void generate_match_method(SourceTextBuilder sb, AdtTypeInfo info)
    {
        var typeParams = string.Join(", ",
            info.cases.Select(c => $"global::System.Func<{c.fully_qualified_type}, TResult>"));
        var paramList = string.Join(", ",
            info.cases.Select(c => $"global::System.Func<{c.fully_qualified_type}, TResult> on{c.case_name}"));

        sb.append_line("/// <summary>");
        sb.append_line($"/// 对当前 <c>{info.type_name}</c> 实例执行模式匹配，根据联合类型分派到对应的处理函数。");
        sb.append_line("/// </summary>");

        foreach (var c in info.cases)
            sb.append_line($"/// <param name=\"on{c.case_name}\">当实例为 <c>{c.type_short_name}</c> 时的处理函数。</param>");

        sb.append_line("/// <typeparam name=\"TResult\">匹配结果的类型。</typeparam>");
        sb.append_line($"public TResult Match<TResult>({paramList})");
        using (sb.block())
        {
            foreach (var c in info.cases)
            {
                var varName = char.ToLowerInvariant(c.case_name[0]) + c.case_name.Substring(1);
                sb.append_line($"if (this is {c.fully_qualified_type} {varName}) return on{c.case_name}({varName});");
            }

            sb.append_line("throw new global::System.InvalidOperationException(\"Unknown union case\");");
        }
    }

    /// <summary>
    ///     生成 <c>IsXxx</c> 布尔属性，用于判断当前实例是否为指定的联合类型。
    /// </summary>
    private static void generate_is_properties(SourceTextBuilder sb, AdtTypeInfo info)
    {
        for (var i = 0; i < info.cases.Count; i++)
        {
            if (i > 0) sb.append_line();

            var c = info.cases[i];
            sb.append_line("/// <summary>");
            sb.append_line($"/// 判断当前实例是否为 <c>{c.type_short_name}</c> 类型。");
            sb.append_line("/// </summary>");
            sb.append_line($"public bool Is{c.case_name} => this is {c.fully_qualified_type};");
        }
    }

    /// <summary>
    ///     生成 <c>AsXxx</c> 可空属性，用于将当前实例安全转换为指定的联合类型。
    /// </summary>
    private static void generate_as_properties(SourceTextBuilder sb, AdtTypeInfo info)
    {
        for (var i = 0; i < info.cases.Count; i++)
        {
            if (i > 0) sb.append_line();

            var c = info.cases[i];
            var varName = char.ToLowerInvariant(c.case_name[0]) + c.case_name.Substring(1);
            sb.append_line("/// <summary>");
            sb.append_line($"/// 将当前实例安全转换为 <c>{c.type_short_name}</c> 类型，若类型不匹配则返回 <c>null</c>。");
            sb.append_line("/// </summary>");
            sb.append_line(
                $"public {c.fully_qualified_type}? As{c.case_name} => this is {c.fully_qualified_type} {varName} ? {varName} : default;");
        }
    }

    #region 数据模型

    /// <summary>
    ///     需要生成 ADT 模式匹配代码的目标类型信息。
    /// </summary>
    internal readonly struct AdtTypeInfo
    {
        /// <summary>
        ///     类型名称。
        /// </summary>
        public readonly string type_name;

        /// <summary>
        ///     完全限定类型名称。
        /// </summary>
        public readonly string fully_qualified_name;

        /// <summary>
        ///     命名空间名称。
        /// </summary>
        public readonly string? namespace_name;

        /// <summary>
        ///     是否为结构体。
        /// </summary>
        public readonly bool is_struct;

        /// <summary>
        ///     联合类型成员列表。
        /// </summary>
        public readonly List<UnionCaseInfo> cases;

        /// <summary>
        ///     初始化 <see cref="AdtTypeInfo" /> 的新实例。
        /// </summary>
        public AdtTypeInfo(
            string typeName,
            string fullyQualifiedName,
            string? namespaceName,
            bool isStruct,
            List<UnionCaseInfo> cases)
        {
            type_name = typeName;
            fully_qualified_name = fullyQualifiedName;
            namespace_name = namespaceName;
            is_struct = isStruct;
            this.cases = cases;
        }
    }

    /// <summary>
    ///     联合类型成员信息，描述一个标记了 <c>[UnionCase]</c> 的属性或字段。
    /// </summary>
    internal readonly struct UnionCaseInfo
    {
        /// <summary>
        ///     成员名称。
        /// </summary>
        public readonly string case_name;

        /// <summary>
        ///     成员类型的完全限定名称。
        /// </summary>
        public readonly string fully_qualified_type;

        /// <summary>
        ///     成员类型的短名称。
        /// </summary>
        public readonly string type_short_name;

        /// <summary>
        ///     自定义标签值，为 <c>null</c> 时使用成员名称。
        /// </summary>
        public readonly string? tag;

        /// <summary>
        ///     初始化 <see cref="UnionCaseInfo" /> 的新实例。
        /// </summary>
        public UnionCaseInfo(
            string caseName,
            string fullyQualifiedType,
            string typeShortName,
            string? tag)
        {
            case_name = caseName;
            fully_qualified_type = fullyQualifiedType;
            type_short_name = typeShortName;
            this.tag = tag;
        }
    }

    #endregion
}