using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     AI 模型代码生成器，消费 Sonic.Standard.AI.AiModelAttribute 生成模型加载和推理代码
/// </summary>
[Generator]
public sealed class AIModelGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了 AiModelAttribute 的类型信息
    /// </summary>
    private static TypeInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var node = ctx.Node as ClassDeclarationSyntax;
        if (node is null) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(node) as INamedTypeSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.AI.AiModelAttribute")
            {
                var modelPath =
                    attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "model_path").Value.Value as string;
                var version = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "version").Value.Value as string;
                return new TypeInfo(
                    symbol.ContainingNamespace.ToDisplayString(),
                    symbol.Name,
                    modelPath ?? "",
                    version ?? "1.0.0");
            }
        }

        return null;
    }

    /// <summary>
    ///     生成 AI 模型加载代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, TypeInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Sonic.Standard.AI;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的 AI 模型加载");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class {info.Value.ClassName}AIExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 模型路径");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static string model_path => \"{info.Value.ModelPath}\";");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 模型版本");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static string model_version => \"{info.Value.Version}\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}AIModel.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     类型信息记录
    /// </summary>
    private readonly struct TypeInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string ModelPath { get; }
        public string Version { get; }

        public TypeInfo(string namespace_, string className, string modelPath, string version)
        {
            Namespace = namespace_;
            ClassName = className;
            ModelPath = modelPath;
            Version = version;
        }
    }
}