using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     为标记了 <c>[Authenticate]</c> 特性的方法自动生成身份验证检查包装。
/// </summary>
[Generator]
public sealed class AuthGenerator : IIncrementalGenerator
{
    private const string _authenticate_attribute_full_name =
        "Sonic.Standard.Security.Authentication.AuthenticateAttribute";

    /// <summary>
    ///     初始化增量源代码生成管道。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _authenticate_attribute_full_name,
                static (node, _) => node is TypeDeclarationSyntax typeDecl &&
                                    typeDecl.Modifiers.Any(SyntaxKind.PartialKeyword),
                static (ctx, ct) => transform_authenticate(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value)
            .Collect();

        context.RegisterSourceOutput(targetTypes, generate_source);
    }

    /// <summary>
    ///     提取标记了 <c>[Authenticate]</c> 的类型和方法信息。
    /// </summary>
    private static AuthTypeInfo? transform_authenticate(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        var typeSymbol = (INamedTypeSymbol)context.TargetSymbol;

        var classHasAuth = typeSymbol.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
            $"global::{_authenticate_attribute_full_name}");

        var methods = new List<AuthMethodInfo>();

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member is not IMethodSymbol method) continue;

            if (method.IsStatic) continue;

            if (method.DeclaredAccessibility != Accessibility.Public) continue;

            var methodHasAuth = method.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
                $"global::{_authenticate_attribute_full_name}");

            if (methodHasAuth || classHasAuth)
            {
                var parameters = method.Parameters
                    .Select(p => new AuthParameterInfo(
                        p.Name,
                        p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        p.RefKind))
                    .ToList();

                methods.Add(new AuthMethodInfo(
                    method.Name,
                    method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    method.ReturnsVoid,
                    parameters,
                    methodHasAuth));
            }
        }

        if (methods.Count == 0) return null;

        return new AuthTypeInfo(
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.ContainingNamespace?.ToDisplayString(),
            typeSymbol.TypeKind == TypeKind.Struct,
            methods);
    }

    /// <summary>
    ///     生成所有类型的身份验证包装源代码。
    /// </summary>
    private static void generate_source(SourceProductionContext context, ImmutableArray<AuthTypeInfo> typeInfos)
    {
        foreach (var info in typeInfos)
        {
            var sourceText = generate_auth_source(info);
            var hintName = $"{info.type_name}.Auth.g.cs";
            context.AddSource(hintName, SourceText.From(sourceText, Encoding.UTF8));
        }
    }

    /// <summary>
    ///     生成单个类型的身份验证包装源代码。
    /// </summary>
    private static string generate_auth_source(AuthTypeInfo info)
    {
        var sb = new SourceTextBuilder();
        sb.append_line("// <auto-generated />");
        sb.append_line("#nullable enable");
        sb.append_line();

        if (!string.IsNullOrEmpty(info.namespace_name))
        {
            sb.append_line($"namespace {info.namespace_name};");
            sb.append_line();
        }

        var typeKeyword = info.is_struct ? "partial struct" : "partial class";
        sb.append_line($"{typeKeyword} {info.type_name}");
        using (sb.block())
        {
            foreach (var method in info.methods)
            {
                generate_auth_wrapper(sb, info, method);
                sb.append_line();
            }
        }

        return sb.ToString();
    }

    /// <summary>
    ///     为单个方法生成身份验证检查包装方法。
    /// </summary>
    private static void generate_auth_wrapper(SourceTextBuilder sb, AuthTypeInfo info, AuthMethodInfo method)
    {
        var paramList = string.Join(", ", method.parameters.Select(p => format_parameter(p)));
        var argList = string.Join(", ", method.parameters.Select(p => format_argument(p)));

        sb.append_line("/// <summary>");
        sb.append_line($"/// 带身份验证检查的 <c>{method.method_name}</c> 包装方法。");
        sb.append_line("/// </summary>");

        foreach (var p in method.parameters) sb.append_line($"/// <param name=\"{p.name}\">{p.name} 参数。</param>");

        var returnType = method.is_void ? "void" : method.return_type;
        sb.append_line($"public {returnType} {method.method_name}_authenticated({paramList})");
        using (sb.block())
        {
            sb.append_line(
                "var __principal = global::Sonic.Standard.Security.Authentication.AuthContext.current_principal();");
            sb.append_line("if (__principal is null)");
            using (sb.block())
            {
                sb.append_line("throw new global::System.UnauthorizedAccessException(\"身份验证失败：未提供有效的身份凭据\");");
            }

            sb.append_line();

            if (method.is_void)
                sb.append_line($"{method.method_name}({argList});");
            else
                sb.append_line($"return {method.method_name}({argList});");
        }
    }

    /// <summary>
    ///     格式化参数声明。
    /// </summary>
    private static string format_parameter(AuthParameterInfo param)
    {
        var prefix = param.ref_kind switch
        {
            RefKind.Ref => "ref ",
            RefKind.Out => "out ",
            RefKind.In => "in ",
            _ => ""
        };

        return $"{prefix}{param.Type} {param.name}";
    }

    /// <summary>
    ///     格式化参数调用。
    /// </summary>
    private static string format_argument(AuthParameterInfo param)
    {
        var prefix = param.ref_kind switch
        {
            RefKind.Ref => "ref ",
            RefKind.Out => "out ",
            RefKind.In => "in ",
            _ => ""
        };

        return $"{prefix}{param.name}";
    }

    #region 数据模型

    /// <summary>
    ///     包含身份验证方法的类型信息。
    /// </summary>
    internal readonly struct AuthTypeInfo
    {
        /// <summary>
        ///     类型名称。
        /// </summary>
        public readonly string type_name;

        /// <summary>
        ///     完全限定类型名称。
        /// </summary>
        public readonly string fully_qualified_name;

        /// <summary>
        ///     命名空间名称。
        /// </summary>
        public readonly string? namespace_name;

        /// <summary>
        ///     是否为结构体。
        /// </summary>
        public readonly bool is_struct;

        /// <summary>
        ///     需要身份验证的方法列表。
        /// </summary>
        public readonly List<AuthMethodInfo> methods;

        /// <summary>
        ///     初始化 <see cref="AuthTypeInfo" /> 的新实例。
        /// </summary>
        public AuthTypeInfo(
            string typeName,
            string fullyQualifiedName,
            string? namespaceName,
            bool isStruct,
            List<AuthMethodInfo> methods)
        {
            type_name = typeName;
            fully_qualified_name = fullyQualifiedName;
            namespace_name = namespaceName;
            is_struct = isStruct;
            this.methods = methods;
        }
    }

    /// <summary>
    ///     需要身份验证的方法信息。
    /// </summary>
    internal readonly struct AuthMethodInfo
    {
        /// <summary>
        ///     方法名称。
        /// </summary>
        public readonly string method_name;

        /// <summary>
        ///     返回类型的完全限定名称。
        /// </summary>
        public readonly string return_type;

        /// <summary>
        ///     是否为 void 返回类型。
        /// </summary>
        public readonly bool is_void;

        /// <summary>
        ///     参数列表。
        /// </summary>
        public readonly List<AuthParameterInfo> parameters;

        /// <summary>
        ///     方法自身是否标记了 <c>[Authenticate]</c>。
        /// </summary>
        public readonly bool has_own_attribute;

        /// <summary>
        ///     初始化 <see cref="AuthMethodInfo" /> 的新实例。
        /// </summary>
        public AuthMethodInfo(
            string methodName,
            string returnType,
            bool isVoid,
            List<AuthParameterInfo> parameters,
            bool hasOwnAttribute)
        {
            method_name = methodName;
            return_type = returnType;
            is_void = isVoid;
            this.parameters = parameters;
            has_own_attribute = hasOwnAttribute;
        }
    }

    /// <summary>
    ///     方法参数信息。
    /// </summary>
    internal readonly struct AuthParameterInfo
    {
        /// <summary>
        ///     参数名称。
        /// </summary>
        public readonly string name;

        /// <summary>
        ///     参数类型的完全限定名称。
        /// </summary>
        public readonly string Type;

        /// <summary>
        ///     参数传递方式。
        /// </summary>
        public readonly RefKind ref_kind;

        /// <summary>
        ///     初始化 <see cref="AuthParameterInfo" /> 的新实例。
        /// </summary>
        public AuthParameterInfo(string name, string type, RefKind refKind)
        {
            this.name = name;
            Type = type;
            ref_kind = refKind;
        }
    }

    #endregion
}