using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     压缩代码生成器，消费 Sonic.Standard.Data.Compression.CompressAttribute 生成压缩扩展方法
/// </summary>
[Generator]
public sealed class CompressGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了 CompressAttribute 的类型信息
    /// </summary>
    private static TypeInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var node = ctx.Node as ClassDeclarationSyntax;
        if (node is null) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(node) as INamedTypeSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Data.Compression.CompressAttribute")
            {
                var algorithmArg = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "algorithm");
                var algorithm = "gzip";
                if (algorithmArg.Value.Value is int algValue)
                    algorithm = algValue switch
                    {
                        0 => "deflate",
                        2 => "brotli",
                        3 => "zstd",
                        4 => "lz4",
                        _ => "gzip"
                    };

                return new TypeInfo(
                    symbol.ContainingNamespace.ToDisplayString(),
                    symbol.Name,
                    algorithm);
            }
        }

        return null;
    }

    /// <summary>
    ///     生成压缩扩展方法代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, TypeInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.IO.Compression;");
        sb.AppendLine("using Sonic.Standard.Data.Compression;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的压缩扩展方法");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class {info.Value.ClassName}CompressionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 将 {info.Value.ClassName} 实例压缩为字节数组");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static byte[] ToCompressedBytes(this {info.Value.ClassName} instance)");
        sb.AppendLine("        {");
        sb.AppendLine("            var data = System.Text.Json.JsonSerializer.Serialize(instance);");
        sb.AppendLine("            var bytes = System.Text.Encoding.UTF8.GetBytes(data);");
        sb.AppendLine(
            $"            var compressor = new Sonic.Standard.Compression.{GetCompressorClass(info.Value.Algorithm)}();");
        sb.AppendLine("            return compressor.compress(bytes);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 从压缩字节数组解压缩为 {info.Value.ClassName} 实例");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static {info.Value.ClassName}? FromCompressedBytes(byte[] compressed)");
        sb.AppendLine("        {");
        sb.AppendLine(
            $"            var compressor = new Sonic.Standard.Compression.{GetCompressorClass(info.Value.Algorithm)}();");
        sb.AppendLine("            var bytes = compressor.decompress(compressed);");
        sb.AppendLine("            var json = System.Text.Encoding.UTF8.GetString(bytes);");
        sb.AppendLine($"            return System.Text.Json.JsonSerializer.Deserialize<{info.Value.ClassName}>(json);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}Compression.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     根据算法名获取压缩器类名
    /// </summary>
    private static string GetCompressorClass(string algorithm)
    {
        return algorithm switch
        {
            "deflate" => "DeflateCompressor",
            "brotli" => "BrotliCompressor",
            _ => "GzipCompressor"
        };
    }

    /// <summary>
    ///     类型信息记录
    /// </summary>
    private readonly struct TypeInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string Algorithm { get; }

        public TypeInfo(string namespace_, string className, string algorithm)
        {
            Namespace = namespace_;
            ClassName = className;
            Algorithm = algorithm;
        }
    }
}