using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     为标记了 <c>[CryptoService]</c> 特性的类自动生成依赖注入注册代码。
/// </summary>
[Generator]
public sealed class CryptoGenerator : IIncrementalGenerator
{
    private const string _crypto_service_attribute_full_name =
        "Sonic.Standard.Security.Cryptography.CryptoServiceAttribute";

    /// <summary>
    ///     初始化增量源代码生成管道。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _crypto_service_attribute_full_name,
                static (node, _) => node is TypeDeclarationSyntax typeDecl &&
                                    typeDecl.Modifiers.Any(SyntaxKind.PartialKeyword),
                static (ctx, ct) => transform_crypto_service(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value)
            .Collect();

        context.RegisterSourceOutput(targetTypes, generate_source);
    }

    /// <summary>
    ///     提取标记了 <c>[CryptoService]</c> 的类型信息。
    /// </summary>
    private static CryptoServiceInfo? transform_crypto_service(GeneratorAttributeSyntaxContext context,
        CancellationToken ct)
    {
        var typeSymbol = (INamedTypeSymbol)context.TargetSymbol;

        var interfaces = extract_crypto_interfaces(typeSymbol);

        if (interfaces.Count == 0) return null;

        return new CryptoServiceInfo(
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.ContainingNamespace?.ToDisplayString(),
            typeSymbol.TypeKind == TypeKind.Struct,
            interfaces);
    }

    /// <summary>
    ///     提取类型实现的加密相关接口。
    /// </summary>
    private static List<CryptoInterfaceInfo> extract_crypto_interfaces(INamedTypeSymbol typeSymbol)
    {
        var interfaces = new List<CryptoInterfaceInfo>();

        var cryptoNamespaces = new HashSet<string>
        {
            "Sonic.Standard.Security.Cryptography"
        };

        foreach (var iface in typeSymbol.AllInterfaces)
        {
            var ns = iface.ContainingNamespace?.ToDisplayString();

            if (ns is not null && cryptoNamespaces.Contains(ns))
                interfaces.Add(new CryptoInterfaceInfo(
                    iface.Name,
                    iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
        }

        return interfaces;
    }

    /// <summary>
    ///     生成所有类型的 DI 注册源代码。
    /// </summary>
    private static void generate_source(SourceProductionContext context, ImmutableArray<CryptoServiceInfo> typeInfos)
    {
        foreach (var info in typeInfos)
        {
            var sourceText = generate_crypto_source(info);
            var hintName = $"{info.type_name}.Crypto.g.cs";
            context.AddSource(hintName, SourceText.From(sourceText, Encoding.UTF8));
        }
    }

    /// <summary>
    ///     生成单个类型的 DI 注册源代码。
    /// </summary>
    private static string generate_crypto_source(CryptoServiceInfo info)
    {
        var sb = new SourceTextBuilder();
        sb.append_line("// <auto-generated />");
        sb.append_line("#nullable enable");
        sb.append_line();

        if (!string.IsNullOrEmpty(info.namespace_name))
        {
            sb.append_line($"namespace {info.namespace_name};");
            sb.append_line();
        }

        var typeKeyword = info.is_struct ? "partial struct" : "partial class";
        sb.append_line($"{typeKeyword} {info.type_name}");
        using (sb.block())
        {
            generate_register_method(sb, info);
        }

        return sb.ToString();
    }

    /// <summary>
    ///     生成 DI 注册扩展方法。
    /// </summary>
    private static void generate_register_method(SourceTextBuilder sb, CryptoServiceInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line($"/// 将 <c>{info.type_name}</c> 注册到依赖注入容器。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"services\">服务集合。</param>");
        sb.append_line(
            "public static void register_crypto_services(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        using (sb.block())
        {
            foreach (var iface in info.interfaces)
                sb.append_line($"services.AddSingleton<{iface.fully_qualified_name}, {info.fully_qualified_name}>();");
        }
    }

    #region 数据模型

    /// <summary>
    ///     标记了 <c>[CryptoService]</c> 的类型信息。
    /// </summary>
    internal readonly struct CryptoServiceInfo
    {
        /// <summary>
        ///     类型名称。
        /// </summary>
        public readonly string type_name;

        /// <summary>
        ///     完全限定类型名称。
        /// </summary>
        public readonly string fully_qualified_name;

        /// <summary>
        ///     命名空间名称。
        /// </summary>
        public readonly string? namespace_name;

        /// <summary>
        ///     是否为结构体。
        /// </summary>
        public readonly bool is_struct;

        /// <summary>
        ///     实现的加密接口列表。
        /// </summary>
        public readonly List<CryptoInterfaceInfo> interfaces;

        /// <summary>
        ///     初始化 <see cref="CryptoServiceInfo" /> 的新实例。
        /// </summary>
        public CryptoServiceInfo(
            string typeName,
            string fullyQualifiedName,
            string? namespaceName,
            bool isStruct,
            List<CryptoInterfaceInfo> interfaces)
        {
            type_name = typeName;
            fully_qualified_name = fullyQualifiedName;
            namespace_name = namespaceName;
            is_struct = isStruct;
            this.interfaces = interfaces;
        }
    }

    /// <summary>
    ///     加密接口信息。
    /// </summary>
    internal readonly struct CryptoInterfaceInfo
    {
        /// <summary>
        ///     接口名称。
        /// </summary>
        public readonly string name;

        /// <summary>
        ///     完全限定接口名称。
        /// </summary>
        public readonly string fully_qualified_name;

        /// <summary>
        ///     初始化 <see cref="CryptoInterfaceInfo" /> 的新实例。
        /// </summary>
        public CryptoInterfaceInfo(string name, string fullyQualifiedName)
        {
            this.name = name;
            fully_qualified_name = fullyQualifiedName;
        }
    }

    #endregion
}