using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     ECS 代码生成器，消费 Sonic.Standard.Simulation.ECS.ComponentAttribute 和 Sonic.Standard.Simulation.ECS.SystemAttribute 生成
///     ECS 基础设施代码
/// </summary>
[Generator]
public sealed class EcsGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了 Component 或 System 属性的类型信息
    /// </summary>
    private static TypeInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Simulation.ECS.ComponentAttribute")
                return new TypeInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, "Component");
            if (attrName == "Sonic.Standard.Simulation.ECS.SystemAttribute")
                return new TypeInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, "System");
        }

        return null;
    }

    /// <summary>
    ///     生成 ECS 基础设施代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, TypeInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Sonic.Standard.Simulation.ECS;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的 {info.Value.Kind} 注册");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class {info.Value.ClassName}{info.Value.Kind}Extensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 注册 {info.Value.ClassName} {info.Value.Kind}");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static void Register{info.Value.ClassName}(this World world)");
        sb.AppendLine("        {");
        sb.AppendLine($"            // 注册 {info.Value.Kind}: {info.Value.ClassName}");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}{info.Value.Kind}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     类型信息记录
    /// </summary>
    private readonly struct TypeInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string Kind { get; }

        public TypeInfo(string namespace_, string className, string kind)
        {
            Namespace = namespace_;
            ClassName = className;
            Kind = kind;
        }
    }
}