using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     为标记了 <c>[FFI]</c> 特性的类自动生成 P/Invoke 包装方法，
///     根据类中的公共方法声明生成对应的外部函数调用代码。
/// </summary>
[Generator]
public sealed class FfiGenerator : IIncrementalGenerator
{
    private const string _ffi_attribute_full_name = "Sonic.Standard.Compiler.FFI.FfiAttribute";

    /// <summary>
    ///     初始化增量源代码生成管道。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _ffi_attribute_full_name,
                static (node, _) => node is ClassDeclarationSyntax classDecl &&
                                    classDecl.Modifiers.Any(SyntaxKind.PartialKeyword),
                static (ctx, ct) => transform_ffi(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value)
            .Collect();

        context.RegisterSourceOutput(targetTypes, generate_source);
    }

    /// <summary>
    ///     提取标记了 <c>[FFI]</c> 特性的类信息。
    /// </summary>
    private static FfiTypeInfo? transform_ffi(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        var typeSymbol = (INamedTypeSymbol)context.TargetSymbol;

        var ffiAttr = context.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
            $"global::{_ffi_attribute_full_name}");

        if (ffiAttr is null) return null;

        string? libraryName = null;

        if (ffiAttr.ConstructorArguments.Length > 0 &&
            ffiAttr.ConstructorArguments[0].Value is string ln)
            libraryName = ln;

        if (libraryName is null) return null;

        var methods = extract_ffi_methods(typeSymbol);

        return new FfiTypeInfo(
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.ContainingNamespace?.ToDisplayString(),
            libraryName,
            methods);
    }

    /// <summary>
    ///     提取类中的公共方法信息，用于生成 P/Invoke 包装。
    /// </summary>
    private static List<FfiMethodInfo> extract_ffi_methods(INamedTypeSymbol typeSymbol)
    {
        var methods = new List<FfiMethodInfo>();

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member is not IMethodSymbol method) continue;

            if (method.DeclaredAccessibility != Accessibility.Public) continue;

            if (method.IsStatic) continue;

            if (method.MethodKind != MethodKind.Ordinary) continue;

            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var isAsync = is_type(method.ReturnType);
            var parameters = extract_ffi_parameters(method);

            methods.Add(new FfiMethodInfo(
                method.Name,
                returnType,
                isAsync,
                parameters));
        }

        return methods;
    }

    /// <summary>
    ///     判断返回类型是否为异步类型。
    /// </summary>
    private static bool is_type(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType) return namedType.Name is "Task" or "ValueTask";

        return false;
    }

    /// <summary>
    ///     提取方法的参数信息列表。
    /// </summary>
    private static List<FfiParameterInfo> extract_ffi_parameters(IMethodSymbol method)
    {
        var parameters = new List<FfiParameterInfo>();

        foreach (var param in method.Parameters)
            parameters.Add(new FfiParameterInfo(
                param.Name,
                param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                param.RefKind));

        return parameters;
    }

    /// <summary>
    ///     生成所有 FFI 类型的源代码。
    /// </summary>
    private static void generate_source(SourceProductionContext context, ImmutableArray<FfiTypeInfo> typeInfos)
    {
        foreach (var info in typeInfos)
        {
            var sourceText = generate_ffi_source(info);
            var hintName = $"{info.type_name}.FFI.g.cs";
            context.AddSource(hintName, SourceText.From(sourceText, Encoding.UTF8));
        }
    }

    /// <summary>
    ///     生成单个 FFI 类型的源代码。
    /// </summary>
    private static string generate_ffi_source(FfiTypeInfo info)
    {
        var sb = new SourceTextBuilder();
        sb.append_line("// <auto-generated />");
        sb.append_line("#nullable enable");
        sb.append_line();
        sb.append_line("using System.Runtime.InteropServices;");
        sb.append_line("using System.Threading.Tasks;");
        sb.append_line();

        if (!string.IsNullOrEmpty(info.namespace_name))
        {
            sb.append_line($"namespace {info.namespace_name};");
            sb.append_line();
        }

        sb.append_line($"partial class {info.type_name} : global::Sonic.Standard.Compiler.FFI.IForeignLibrary");
        using (sb.block())
        {
            generate_library_name_property(sb, info);
            sb.append_line();

            generate_native_methods_class(sb, info);
            sb.append_line();

            generate_wrapper_methods(sb, info);
        }

        return sb.ToString();
    }

    /// <summary>
    ///     生成 <c>library_name</c> 属性实现。
    /// </summary>
    private static void generate_library_name_property(SourceTextBuilder sb, FfiTypeInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 获取原生库的名称。");
        sb.append_line("/// </summary>");
        sb.append_line($"public string library_name => \"{StringEscapeHelper.escape_for_string(info.library_name)}\";");
    }

    /// <summary>
    ///     生成 <c>NativeMethods</c> 内部类，包含 DllImport 声明。
    /// </summary>
    private static void generate_native_methods_class(SourceTextBuilder sb, FfiTypeInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 原生方法声明，包含 P/Invoke 入口点。");
        sb.append_line("/// </summary>");
        sb.append_line("private static class NativeMethods");
        using (sb.block())
        {
            foreach (var method in info.methods)
            {
                generate_dll_import(sb, info, method);
                sb.append_line();
            }
        }
    }

    /// <summary>
    ///     生成单个 <c>DllImport</c> 声明。
    /// </summary>
    private static void generate_dll_import(SourceTextBuilder sb, FfiTypeInfo info, FfiMethodInfo method)
    {
        var paramList = build_native_parameter_list(method.parameters);
        var returnType = map_to_native_return_type(method.return_type, method.is_async);

        sb.append_line("/// <summary>");
        sb.append_line($"/// 原生方法 <c>{method.method_name}</c> 的 P/Invoke 声明。");
        sb.append_line("/// </summary>");
        sb.append_line(
            $"[global::System.Runtime.InteropServices.DllImport(\"{StringEscapeHelper.escape_for_string(info.library_name)}\", " +
            $"CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl)]");
        sb.append_line($"public static extern {returnType} {method.method_name}({paramList});");
    }

    /// <summary>
    ///     生成包装方法，将托管调用转发到 P/Invoke。
    /// </summary>
    private static void generate_wrapper_methods(SourceTextBuilder sb, FfiTypeInfo info)
    {
        foreach (var method in info.methods)
        {
            generate_wrapper_method(sb, method);
            sb.append_line();
        }
    }

    /// <summary>
    ///     生成单个包装方法。
    /// </summary>
    private static void generate_wrapper_method(SourceTextBuilder sb, FfiMethodInfo method)
    {
        var paramList = build_managed_parameter_list(method.parameters);
        var argList = build_argument_list(method.parameters);

        sb.append_line("/// <summary>");
        sb.append_line($"/// <c>{method.method_name}</c> 的托管包装方法。");
        sb.append_line("/// </summary>");

        foreach (var param in method.parameters)
            sb.append_line($"/// <param name=\"{param.name}\">{param.name} 参数。</param>");

        sb.append_line($"public {method.return_type} {method.method_name}({paramList})");
        using (sb.block())
        {
            if (method.is_async)
            {
                sb.append_line(
                    $"return global::System.Threading.Tasks.Task.Run(() => NativeMethods.{method.method_name}({argList}));");
            }
            else
            {
                if (method.return_type == "global::System.Void")
                    sb.append_line($"NativeMethods.{method.method_name}({argList});");
                else
                    sb.append_line($"return NativeMethods.{method.method_name}({argList});");
            }
        }
    }

    /// <summary>
    ///     构建原生方法参数列表字符串。
    /// </summary>
    private static string build_native_parameter_list(List<FfiParameterInfo> parameters)
    {
        var parts = new List<string>();

        foreach (var param in parameters)
        {
            var prefix = param.ref_kind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In => "in ",
                _ => ""
            };

            parts.Add($"{prefix}{param.Type} {param.name}");
        }

        return string.Join(", ", parts);
    }

    /// <summary>
    ///     构建托管方法参数列表字符串。
    /// </summary>
    private static string build_managed_parameter_list(List<FfiParameterInfo> parameters)
    {
        var parts = new List<string>();

        foreach (var param in parameters)
        {
            var prefix = param.ref_kind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In => "in ",
                _ => ""
            };

            parts.Add($"{prefix}{param.Type} {param.name}");
        }

        return string.Join(", ", parts);
    }

    /// <summary>
    ///     构建方法调用参数列表字符串。
    /// </summary>
    private static string build_argument_list(List<FfiParameterInfo> parameters)
    {
        var parts = new List<string>();

        foreach (var param in parameters)
        {
            var prefix = param.ref_kind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In => "in ",
                _ => ""
            };

            parts.Add($"{prefix}{param.name}");
        }

        return string.Join(", ", parts);
    }

    /// <summary>
    ///     将托管返回类型映射为原生返回类型。
    /// </summary>
    private static string map_to_native_return_type(string returnType, bool isAsync)
    {
        if (isAsync) return "global::System.IntPtr";

        return returnType;
    }

    #region 数据模型

    /// <summary>
    ///     需要生成 FFI 包装的类型信息。
    /// </summary>
    internal readonly struct FfiTypeInfo
    {
        /// <summary>
        ///     类型名称。
        /// </summary>
        public readonly string type_name;

        /// <summary>
        ///     完全限定类型名称。
        /// </summary>
        public readonly string fully_qualified_name;

        /// <summary>
        ///     命名空间名称。
        /// </summary>
        public readonly string? namespace_name;

        /// <summary>
        ///     原生库名称。
        /// </summary>
        public readonly string library_name;

        /// <summary>
        ///     FFI 方法列表。
        /// </summary>
        public readonly List<FfiMethodInfo> methods;

        /// <summary>
        ///     初始化 <see cref="FfiTypeInfo" /> 的新实例。
        /// </summary>
        public FfiTypeInfo(
            string typeName,
            string fullyQualifiedName,
            string? namespaceName,
            string libraryName,
            List<FfiMethodInfo> methods)
        {
            type_name = typeName;
            fully_qualified_name = fullyQualifiedName;
            namespace_name = namespaceName;
            library_name = libraryName;
            this.methods = methods;
        }
    }

    /// <summary>
    ///     FFI 方法信息。
    /// </summary>
    internal readonly struct FfiMethodInfo
    {
        /// <summary>
        ///     方法名称。
        /// </summary>
        public readonly string method_name;

        /// <summary>
        ///     返回类型完全限定名称。
        /// </summary>
        public readonly string return_type;

        /// <summary>
        ///     是否为异步方法。
        /// </summary>
        public readonly bool is_async;

        /// <summary>
        ///     方法参数列表。
        /// </summary>
        public readonly List<FfiParameterInfo> parameters;

        /// <summary>
        ///     初始化 <see cref="FfiMethodInfo" /> 的新实例。
        /// </summary>
        public FfiMethodInfo(
            string methodName,
            string returnType,
            bool isAsync,
            List<FfiParameterInfo> parameters)
        {
            method_name = methodName;
            return_type = returnType;
            is_async = isAsync;
            this.parameters = parameters;
        }
    }

    /// <summary>
    ///     FFI 方法参数信息。
    /// </summary>
    internal readonly struct FfiParameterInfo
    {
        /// <summary>
        ///     参数名称。
        /// </summary>
        public readonly string name;

        /// <summary>
        ///     参数类型完全限定名称。
        /// </summary>
        public readonly string Type;

        /// <summary>
        ///     参数传递方式。
        /// </summary>
        public readonly RefKind ref_kind;

        /// <summary>
        ///     初始化 <see cref="FfiParameterInfo" /> 的新实例。
        /// </summary>
        public FfiParameterInfo(string name, string type, RefKind refKind)
        {
            this.name = name;
            Type = type;
            ref_kind = refKind;
        }
    }

    #endregion
}