using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     金融代码生成器，消费 Sonic.Standard.Finance.CurrencyAttribute 和 Sonic.Standard.Finance.PrecisionAttribute 生成货币运算代码
/// </summary>
[Generator]
public sealed class FinanceGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了 CurrencyAttribute 的类型信息
    /// </summary>
    private static TypeInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Finance.CurrencyAttribute")
            {
                var code = attr.ConstructorArguments.FirstOrDefault().Value as string ?? "USD";
                var digits = 2;
                foreach (var member in symbol.GetMembers())
                    if (member is IPropertySymbol or IFieldSymbol)
                        foreach (var propAttr in member.GetAttributes())
                            if (propAttr.AttributeClass?.ToDisplayString() ==
                                "Sonic.Standard.Finance.PrecisionAttribute")
                                digits = propAttr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "decimal_digits")
                                    .Value.Value as int? ?? 2;

                return new TypeInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, code, digits);
            }
        }

        return null;
    }

    /// <summary>
    ///     生成货币运算代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, TypeInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Sonic.Standard.Finance;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的货币运算扩展");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class {info.Value.ClassName}FinanceExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 获取 {info.Value.ClassName} 的货币实例");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static Currency GetCurrency()");
        sb.AppendLine("        {");
        sb.AppendLine($"            return new Currency(\"{info.Value.Code}\", {info.Value.DecimalDigits});");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 创建 {info.Value.ClassName} 金额");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static Money ToMoney(this decimal amount)");
        sb.AppendLine("        {");
        sb.AppendLine(
            $"            return new Money(amount, new Currency(\"{info.Value.Code}\", {info.Value.DecimalDigits}));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}Finance.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     类型信息记录
    /// </summary>
    private readonly struct TypeInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string Code { get; }
        public int DecimalDigits { get; }

        public TypeInfo(string namespace_, string className, string code, int decimalDigits)
        {
            Namespace = namespace_;
            ClassName = className;
            Code = code;
            DecimalDigits = decimalDigits;
        }
    }
}