using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     GeoJSON 代码生成器，消费 Sonic.Standard.Geo.GeoJsonAttribute 生成序列化与反序列化代码
/// </summary>
[Generator]
public sealed class GeoJsonGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了 GeoJsonAttribute 的类型信息
    /// </summary>
    private static TypeInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Geo.GeoJsonAttribute")
                return new TypeInfo(
                    symbol.ContainingNamespace.ToDisplayString(),
                    symbol.Name,
                    symbol.TypeKind == TypeKind.Struct);
        }

        return null;
    }

    /// <summary>
    ///     生成 GeoJSON 序列化代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, TypeInfo? info)
    {
        if (info is null) return;

        var keyword = info.Value.IsStruct ? "struct" : "class";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Sonic.Standard.Geo;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的 GeoJSON 序列化扩展");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class {info.Value.ClassName}GeoJsonExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 将 {info.Value.ClassName} 序列化为 GeoJSON 字符串");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static string ToGeoJson(this {info.Value.ClassName} instance)");
        sb.AppendLine("        {");
        sb.AppendLine("            return System.Text.Json.JsonSerializer.Serialize(instance);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 从 GeoJSON 字符串反序列化为 {info.Value.ClassName}");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static {info.Value.ClassName}? FromGeoJson(string geoJson)");
        sb.AppendLine("        {");
        sb.AppendLine(
            $"            return System.Text.Json.JsonSerializer.Deserialize<{info.Value.ClassName}>(geoJson);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}GeoJson.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     类型信息记录
    /// </summary>
    private readonly struct TypeInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public bool IsStruct { get; }

        public TypeInfo(string namespace_, string className, bool isStruct)
        {
            Namespace = namespace_;
            ClassName = className;
            IsStruct = isStruct;
        }
    }
}