using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     热模块替换代码生成器，消费 Sonic.Standard.Widget.Hmr.HotReloadAttribute 和 Sonic.Standard.Widget.Hmr.AcceptStateAttribute
///     生成热重载代理代码
/// </summary>
[Generator]
public sealed class HmrGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了 HotReloadAttribute 的类型信息
    /// </summary>
    private static TypeInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var node = ctx.Node as ClassDeclarationSyntax;
        if (node is null) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(node) as INamedTypeSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Widget.Hmr.HotReloadAttribute")
                return new TypeInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name);
        }

        return null;
    }

    /// <summary>
    ///     生成热重载代理代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, TypeInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的热重载代理");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public partial class {info.Value.ClassName}");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 接受热重载状态");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public void accept_hot_reload_state({info.Value.ClassName} previous)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 热重载时保留状态");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}Hmr.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     类型信息记录
    /// </summary>
    private readonly struct TypeInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }

        public TypeInfo(string namespace_, string className)
        {
            Namespace = namespace_;
            ClassName = className;
        }
    }
}