using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     为标记了 <c>[InfraStack]</c> 特性的类型自动生成 IaC 资源定义，
///     为 <c>[Queue]</c> 字段生成队列资源配置。
/// </summary>
[Generator]
public sealed class InfraGenerator : IIncrementalGenerator
{
    private const string _infra_stack_attribute_full_name = "Sonic.Standard.Infra.InfraStackAttribute";
    private const string _queue_attribute_full_name = "Sonic.Standard.Infra.QueueAttribute";

    /// <summary>
    ///     初始化增量源代码生成管道。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _infra_stack_attribute_full_name,
                static (node, _) => node is TypeDeclarationSyntax typeDecl &&
                                    typeDecl.Modifiers.Any(SyntaxKind.PartialKeyword),
                static (ctx, ct) => transform_infra_stack(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value)
            .Collect();

        context.RegisterSourceOutput(targetTypes, generate_source);
    }

    /// <summary>
    ///     提取标记了 <c>[InfraStack]</c> 的类型信息。
    /// </summary>
    private static InfraStackInfo? transform_infra_stack(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        var typeSymbol = (INamedTypeSymbol)context.TargetSymbol;

        var infraStackAttr = context.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
            $"global::{_infra_stack_attribute_full_name}");

        string? stackName = null;

        if (infraStackAttr is not null)
            foreach (var named in infraStackAttr.NamedArguments)
                if (named is { Key: "name", Value.Value: string n })
                    stackName = n;

        var queues = extract_queues(typeSymbol);

        return new InfraStackInfo(
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.ContainingNamespace?.ToDisplayString(),
            typeSymbol.TypeKind == TypeKind.Struct,
            stackName ?? typeSymbol.Name,
            queues);
    }

    /// <summary>
    ///     提取类型中标记了 <c>[Queue]</c> 的字段和属性。
    /// </summary>
    private static List<QueueInfo> extract_queues(INamedTypeSymbol typeSymbol)
    {
        var queues = new List<QueueInfo>();

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member.IsStatic) continue;

            var queueAttr = member.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
                $"global::{_queue_attribute_full_name}");

            if (queueAttr is null) continue;

            string? queueName = null;
            var visibility = 0;

            foreach (var named in queueAttr.NamedArguments)
            {
                if (named is { Key: "name", Value.Value: string n }) queueName = n;

                if (named is { Key: "visibility", Value.Value: int v }) visibility = v;
            }

            var memberName = member.Name;
            var memberType = member switch
            {
                IPropertySymbol prop => prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                IFieldSymbol field => field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                _ => "global::System.Object"
            };

            queues.Add(new QueueInfo(
                memberName,
                queueName ?? memberName,
                memberType,
                visibility));
        }

        return queues;
    }

    /// <summary>
    ///     生成所有类型的 IaC 资源定义源代码。
    /// </summary>
    private static void generate_source(SourceProductionContext context, ImmutableArray<InfraStackInfo> typeInfos)
    {
        foreach (var info in typeInfos)
        {
            var sourceText = generate_infra_source(info);
            var hintName = $"{info.type_name}.Infra.g.cs";
            context.AddSource(hintName, SourceText.From(sourceText, Encoding.UTF8));
        }
    }

    /// <summary>
    ///     生成单个类型的 IaC 资源定义源代码。
    /// </summary>
    private static string generate_infra_source(InfraStackInfo info)
    {
        var sb = new SourceTextBuilder();
        sb.append_line("// <auto-generated />");
        sb.append_line("#nullable enable");
        sb.append_line();
        sb.append_line("using System.Collections.Generic;");
        sb.append_line();

        if (!string.IsNullOrEmpty(info.namespace_name))
        {
            sb.append_line($"namespace {info.namespace_name};");
            sb.append_line();
        }

        var typeKeyword = info.is_struct ? "partial struct" : "partial class";
        sb.append_line($"{typeKeyword} {info.type_name}");
        using (sb.block())
        {
            generate_stack_resource_method(sb, info);
            sb.append_line();
            generate_queue_resources_method(sb, info);
        }

        return sb.ToString();
    }

    /// <summary>
    ///     生成 <c>build_stack_resources</c> 方法，返回栈级别的云资源列表。
    /// </summary>
    private static void generate_stack_resource_method(SourceTextBuilder sb, InfraStackInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line($"/// 构建当前 <c>{info.type_name}</c> 基础设施栈的云资源定义。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <returns>云资源列表。</returns>");
        sb.append_line(
            "public global::System.Collections.Generic.List<global::Sonic.Standard.Infra.ICloudResource> build_stack_resources()");
        using (sb.block())
        {
            sb.append_line(
                "var __resources = new global::System.Collections.Generic.List<global::Sonic.Standard.Infra.ICloudResource>();");
            sb.append_line();

            foreach (var queue in info.queues) sb.append_line($"__resources.Add({queue.member_name}_to_resource());");

            sb.append_line();
            sb.append_line("return __resources;");
        }
    }

    /// <summary>
    ///     生成每个 <c>[Queue]</c> 字段的资源转换方法。
    /// </summary>
    private static void generate_queue_resources_method(SourceTextBuilder sb, InfraStackInfo info)
    {
        foreach (var queue in info.queues)
        {
            sb.append_line("/// <summary>");
            sb.append_line($"/// 将 <c>{queue.member_name}</c> 队列转换为云资源定义。");
            sb.append_line("/// </summary>");
            sb.append_line("/// <returns>队列云资源。</returns>");
            sb.append_line($"private global::Sonic.Standard.Infra.CloudResource {queue.member_name}_to_resource()");
            using (sb.block())
            {
                sb.append_line("var __props = new global::System.Collections.Generic.Dictionary<string, object>();");
                sb.append_line($"__props[\"queueName\"] = \"{queue.queue_name}\";");
                sb.append_line($"__props[\"visibility\"] = {queue.visibility};");
                sb.append_line(
                    $"return new global::Sonic.Standard.Infra.CloudResource(\"queue\", \"{queue.queue_name}\", __props);");
            }

            sb.append_line();
        }
    }

    #region 数据模型

    /// <summary>
    ///     标记了 <c>[InfraStack]</c> 的类型信息。
    /// </summary>
    internal readonly struct InfraStackInfo
    {
        /// <summary>
        ///     类型名称。
        /// </summary>
        public readonly string type_name;

        /// <summary>
        ///     完全限定类型名称。
        /// </summary>
        public readonly string fully_qualified_name;

        /// <summary>
        ///     命名空间名称。
        /// </summary>
        public readonly string? namespace_name;

        /// <summary>
        ///     是否为结构体。
        /// </summary>
        public readonly bool is_struct;

        /// <summary>
        ///     基础设施栈名称。
        /// </summary>
        public readonly string stack_name;

        /// <summary>
        ///     队列资源列表。
        /// </summary>
        public readonly List<QueueInfo> queues;

        /// <summary>
        ///     初始化 <see cref="InfraStackInfo" /> 的新实例。
        /// </summary>
        public InfraStackInfo(
            string typeName,
            string fullyQualifiedName,
            string? namespaceName,
            bool isStruct,
            string stackName,
            List<QueueInfo> queues)
        {
            type_name = typeName;
            fully_qualified_name = fullyQualifiedName;
            namespace_name = namespaceName;
            is_struct = isStruct;
            stack_name = stackName;
            this.queues = queues;
        }
    }

    /// <summary>
    ///     队列资源信息。
    /// </summary>
    internal readonly struct QueueInfo
    {
        /// <summary>
        ///     成员名称。
        /// </summary>
        public readonly string member_name;

        /// <summary>
        ///     队列名称。
        /// </summary>
        public readonly string queue_name;

        /// <summary>
        ///     成员类型的完全限定名称。
        /// </summary>
        public readonly string member_type;

        /// <summary>
        ///     队列可见性。
        /// </summary>
        public readonly int visibility;

        /// <summary>
        ///     初始化 <see cref="QueueInfo" /> 的新实例。
        /// </summary>
        public QueueInfo(string memberName, string queueName, string memberType, int visibility)
        {
            member_name = memberName;
            queue_name = queueName;
            member_type = memberType;
            this.visibility = visibility;
        }
    }

    #endregion
}