using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     岛屿架构代码生成器，消费 Sonic.Standard.Widget.Island.IslandAttribute 和 Sonic.Standard.Widget.Island.HydrateAttribute 生成
///     SSR/CSR 代码
/// </summary>
[Generator]
public sealed class IslandGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了 IslandAttribute 或 HydrateAttribute 的类型信息
    /// </summary>
    private static TypeInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var node = ctx.Node as ClassDeclarationSyntax;
        if (node is null) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(node) as INamedTypeSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Widget.Island.IslandAttribute")
            {
                var renderMode =
                    attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "render_mode").Value.Value as int?;
                return new TypeInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, "Island",
                    renderMode ?? 0);
            }

            if (attrName == "Sonic.Standard.Widget.Island.HydrateAttribute")
                return new TypeInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, "Hydrate", 0);
        }

        return null;
    }

    /// <summary>
    ///     生成岛屿架构代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, TypeInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Sonic.Standard.Widget.Island;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的 {info.Value.Kind} 基础设施");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public partial class {info.Value.ClassName}");
        sb.AppendLine("    {");

        if (info.Value.Kind == "Island")
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 渲染模式");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public RenderMode render_mode => RenderMode.server;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 服务端渲染");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public string render_server()");
            sb.AppendLine("        {");
            sb.AppendLine(
                "            return typeof(global::System.Reflection.IntrospectionExtensions).Assembly.GetType(nameof(global::System.Object))?.FullName ?? string.Empty;");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}Island.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     类型信息记录
    /// </summary>
    private readonly struct TypeInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string Kind { get; }
        public int RenderMode { get; }

        public TypeInfo(string namespace_, string className, string kind, int renderMode)
        {
            Namespace = namespace_;
            ClassName = className;
            Kind = kind;
            RenderMode = renderMode;
        }
    }
}