using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     布局代码生成器，消费 Sonic.Standard.Widget.Layout.GridAttribute 和 Sonic.Standard.Widget.Layout.StackAttribute 生成布局实现
/// </summary>
[Generator]
public sealed class LayoutGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了布局属性的类信息
    /// </summary>
    private static LayoutInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var node = ctx.Node as ClassDeclarationSyntax;
        if (node is null) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(node) as INamedTypeSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Widget.Layout.GridAttribute")
            {
                var rows = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "rows").Value.Value as int? ?? 1;
                var cols = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "columns").Value.Value as int? ?? 1;
                return new LayoutInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, "Grid", rows, cols);
            }

            if (attrName == "Sonic.Standard.Widget.Layout.StackAttribute")
                return new LayoutInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, "Stack", 0, 0);
        }

        return null;
    }

    /// <summary>
    ///     生成布局代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, LayoutInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Sonic.Standard.Widget.Layout;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的 {info.Value.Kind} 布局实现");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public partial class {info.Value.ClassName} : ILayoutItem");
        sb.AppendLine("    {");

        if (info.Value.Kind == "Grid")
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 网格行数");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public int row_count => {info.Value.Rows};");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 网格列数");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public int column_count => {info.Value.Cols};");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}Layout.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     布局信息记录
    /// </summary>
    private readonly struct LayoutInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string Kind { get; }
        public int Rows { get; }
        public int Cols { get; }

        public LayoutInfo(string namespace_, string className, string kind, int rows, int cols)
        {
            Namespace = namespace_;
            ClassName = className;
            Kind = kind;
            Rows = rows;
            Cols = cols;
        }
    }
}