using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     为标记了 <c>[LocaleResource]</c> 特性的类型自动生成 <c>IStringLocalizer</c> 实现，
///     包含 <c>get</c> 方法和索引器。
/// </summary>
[Generator]
public sealed class LocaleGenerator : IIncrementalGenerator
{
    private const string _locale_resource_attribute_full_name = "Sonic.Standard.Locale.LocaleResourceAttribute";

    /// <summary>
    ///     初始化增量源代码生成管道。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _locale_resource_attribute_full_name,
                static (node, _) => node is TypeDeclarationSyntax typeDecl &&
                                    typeDecl.Modifiers.Any(SyntaxKind.PartialKeyword),
                static (ctx, ct) => transform_locale(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value)
            .Collect();

        context.RegisterSourceOutput(targetTypes, generate_source);
    }

    /// <summary>
    ///     提取需要生成本地化代码的类型信息。
    /// </summary>
    private static LocaleTypeInfo? transform_locale(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        var typeSymbol = (INamedTypeSymbol)context.TargetSymbol;

        var localeAttr = context.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
            $"global::{_locale_resource_attribute_full_name}");

        string? resourcePath = null;
        var defaultLocale = "en";

        if (localeAttr is not null)
            foreach (var named in localeAttr.NamedArguments)
            {
                if (named is { Key: "resource_path", Value.Value: string rp }) resourcePath = rp;

                if (named is { Key: "default_locale", Value.Value: string dl }) defaultLocale = dl;
            }

        var stringKeys = new List<StringKeyInfo>();

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member.IsStatic) continue;

            if (member.DeclaredAccessibility != Accessibility.Public) continue;

            if (member is IPropertySymbol { IsWriteOnly: false, Type.SpecialType: SpecialType.System_String } prop) stringKeys.Add(new StringKeyInfo(prop.Name));
        }

        return new LocaleTypeInfo(
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.ContainingNamespace?.ToDisplayString(),
            typeSymbol.TypeKind == TypeKind.Struct,
            resourcePath,
            defaultLocale,
            stringKeys);
    }

    /// <summary>
    ///     生成所有本地化类型的源代码。
    /// </summary>
    private static void generate_source(SourceProductionContext context, ImmutableArray<LocaleTypeInfo> typeInfos)
    {
        foreach (var info in typeInfos)
        {
            var sourceText = generate_locale_source(info);
            var hintName = $"{info.type_name}.Locale.g.cs";
            context.AddSource(hintName, SourceText.From(sourceText, Encoding.UTF8));
        }
    }

    /// <summary>
    ///     生成单个类型的本地化实现源代码。
    /// </summary>
    private static string generate_locale_source(LocaleTypeInfo info)
    {
        var sb = new SourceTextBuilder();
        sb.append_line("// <auto-generated />");
        sb.append_line("#nullable enable");
        sb.append_line();
        sb.append_line("using System.Collections.Generic;");
        sb.append_line();

        if (!string.IsNullOrEmpty(info.namespace_name))
        {
            sb.append_line($"namespace {info.namespace_name};");
            sb.append_line();
        }

        var typeKeyword = info.is_struct ? "partial struct" : "partial class";
        sb.append_line("/// <summary>");
        sb.append_line($"/// <c>{info.type_name}</c> 的 <c>IStringLocalizer</c> 实现。");
        sb.append_line("/// </summary>");
        sb.append_line($"{typeKeyword} {info.type_name} : global::Sonic.Standard.Locale.IStringLocalizer");
        using (sb.block())
        {
            generate_fields(sb, info);
            sb.append_line();
            generate_constructor(sb, info);
            sb.append_line();
            generate_get_method(sb);
            sb.append_line();
            generate_indexer(sb);
            sb.append_line();
            generate_key_accessors(sb, info);
        }

        return sb.ToString();
    }

    /// <summary>
    ///     生成后备字段。
    /// </summary>
    private static void generate_fields(SourceTextBuilder sb, LocaleTypeInfo info)
    {
        sb.append_line("#region 后备字段");
        sb.append_line();
        sb.append_line("private readonly global::System.Collections.Generic.Dictionary<string, string> _strings;");
        sb.append_line($"private readonly string _default_locale = \"{escape_string(info.default_locale)}\";");
        sb.append_line();

        if (info.resource_path is not null)
            sb.append_line($"private readonly string? _resource_path = \"{escape_string(info.resource_path)}\";");
        else
            sb.append_line("private readonly string? _resource_path;");

        sb.append_line();
        sb.append_line("#endregion");
    }

    /// <summary>
    ///     生成构造函数。
    /// </summary>
    private static void generate_constructor(SourceTextBuilder sb, LocaleTypeInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line($"/// 初始化 <c>{info.type_name}</c> 的新实例。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"locale\">区域名称，为 null 时使用默认区域。</param>");
        sb.append_line($"public {info.type_name}(string? locale = null)");
        using (sb.block())
        {
            sb.append_line("_strings = new global::System.Collections.Generic.Dictionary<string, string>();");
            sb.append_line("var target_locale = locale ?? _default_locale;");
            sb.append_line("load_locale(target_locale);");
        }
    }

    /// <summary>
    ///     生成 <c>get</c> 方法。
    /// </summary>
    private static void generate_get_method(SourceTextBuilder sb)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 根据名称获取本地化字符串，支持格式化参数。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"name\">字符串名称。</param>");
        sb.append_line("/// <param name=\"args\">格式化参数。</param>");
        sb.append_line("/// <returns>格式化后的本地化字符串。</returns>");
        sb.append_line("public string get(string name, params object[] args)");
        using (sb.block())
        {
            sb.append_line("if (!_strings.TryGetValue(name, out var value))");
            using (sb.block())
            {
                sb.append_line("value = name;");
            }

            sb.append_line();
            sb.append_line("if (args is null || args.Length == 0)");
            using (sb.block())
            {
                sb.append_line("return value;");
            }

            sb.append_line();
            sb.append_line("return global::System.String.Format(value, args);");
        }
    }

    /// <summary>
    ///     生成索引器。
    /// </summary>
    private static void generate_indexer(SourceTextBuilder sb)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 根据名称获取本地化字符串的索引器。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"name\">字符串名称。</param>");
        sb.append_line("/// <returns>本地化字符串。</returns>");
        sb.append_line("public string this[string name] => get(name);");
    }

    /// <summary>
    ///     生成字符串键的强类型访问属性。
    /// </summary>
    private static void generate_key_accessors(SourceTextBuilder sb, LocaleTypeInfo info)
    {
        if (info.string_keys.Count == 0) return;

        sb.append_line("#region 字符串键访问器");
        sb.append_line();

        foreach (var key in info.string_keys)
        {
            sb.append_line("/// <summary>");
            sb.append_line($"/// 获取 <c>{key.name}</c> 的本地化字符串。");
            sb.append_line("/// </summary>");
            sb.append_line($"public string {key.name} => get(\"{key.name}\");");
            sb.append_line();
        }

        sb.append_line("#endregion");
    }

    /// <summary>
    ///     对字符串进行转义，用于嵌入生成的源代码中。
    /// </summary>
    private static string escape_string(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    #region 数据模型

    /// <summary>
    ///     需要生成本地化代码的目标类型信息。
    /// </summary>
    internal readonly struct LocaleTypeInfo
    {
        /// <summary>
        ///     类型名称。
        /// </summary>
        public readonly string type_name;

        /// <summary>
        ///     完全限定类型名称。
        /// </summary>
        public readonly string fully_qualified_name;

        /// <summary>
        ///     命名空间名称。
        /// </summary>
        public readonly string? namespace_name;

        /// <summary>
        ///     是否为结构体。
        /// </summary>
        public readonly bool is_struct;

        /// <summary>
        ///     资源路径。
        /// </summary>
        public readonly string? resource_path;

        /// <summary>
        ///     默认区域。
        /// </summary>
        public readonly string default_locale;

        /// <summary>
        ///     字符串键列表。
        /// </summary>
        public readonly List<StringKeyInfo> string_keys;

        /// <summary>
        ///     初始化 <see cref="LocaleTypeInfo" /> 的新实例。
        /// </summary>
        public LocaleTypeInfo(
            string typeName,
            string fullyQualifiedName,
            string? namespaceName,
            bool isStruct,
            string? resourcePath,
            string defaultLocale,
            List<StringKeyInfo> stringKeys)
        {
            type_name = typeName;
            fully_qualified_name = fullyQualifiedName;
            namespace_name = namespaceName;
            is_struct = isStruct;
            resource_path = resourcePath;
            default_locale = defaultLocale;
            string_keys = stringKeys;
        }
    }

    /// <summary>
    ///     字符串键信息。
    /// </summary>
    internal readonly struct StringKeyInfo
    {
        /// <summary>
        ///     键名称。
        /// </summary>
        public readonly string name;

        /// <summary>
        ///     初始化 <see cref="StringKeyInfo" /> 的新实例。
        /// </summary>
        public StringKeyInfo(string name)
        {
            this.name = name;
        }
    }

    #endregion
}