using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     为标记了 <c>[Debounce]</c> 或 <c>[Throttle]</c> 特性的属性自动生成
///     延迟或节流属性变更通知的包装代码。
/// </summary>
[Generator]
public sealed class ObservableGenerator : IIncrementalGenerator
{
    private const string _debounce_attribute_full_name = "Sonic.Standard.State.Observable.DebounceAttribute";
    private const string _throttle_attribute_full_name = "Sonic.Standard.State.Observable.ThrottleAttribute";

    /// <summary>
    ///     初始化增量源代码生成管道。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var debounceTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _debounce_attribute_full_name,
                static (node, _) => node is PropertyDeclarationSyntax,
                static (ctx, ct) => transform_observable_property(ctx, ObservableKind.debounce, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        var throttleTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _throttle_attribute_full_name,
                static (node, _) => node is PropertyDeclarationSyntax,
                static (ctx, ct) => transform_observable_property(ctx, ObservableKind.throttle, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        var allTargets = debounceTargets.Collect().Combine(throttleTargets.Collect());

        context.RegisterSourceOutput(allTargets, generate_source);
    }

    /// <summary>
    ///     提取可观察属性信息。
    /// </summary>
    private static ObservablePropertyInfo? transform_observable_property(GeneratorAttributeSyntaxContext context,
        ObservableKind kind, CancellationToken ct)
    {
        var propertySymbol = (IPropertySymbol)context.TargetSymbol;
        var typeSymbol = propertySymbol.ContainingType;

        if (typeSymbol is null) return null;

        var milliseconds = 300;

        var attr = context.Attributes.First();

        foreach (var named in attr.NamedArguments)
            if (named is { Key: "milliseconds", Value.Value: int ms })
                milliseconds = ms;

        return new ObservablePropertyInfo(
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.ContainingNamespace?.ToDisplayString(),
            propertySymbol.Name,
            propertySymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            kind,
            milliseconds);
    }

    /// <summary>
    ///     生成所有可观察属性的源代码。
    /// </summary>
    private static void generate_source(SourceProductionContext context,
        (ImmutableArray<ObservablePropertyInfo> debounce, ImmutableArray<ObservablePropertyInfo> throttle) allTargets)
    {
        var grouped = new Dictionary<string, List<ObservablePropertyInfo>>();

        foreach (var prop in allTargets.debounce) add_property(grouped, prop);

        foreach (var prop in allTargets.throttle) add_property(grouped, prop);

        foreach (var __kvp in grouped)
        {
            var props = __kvp.Value;
            var first = props[0];
            var sourceText = generate_observable_source(first, props);
            var hintName = $"{first.type_name}.Observable.g.cs";
            context.AddSource(hintName, SourceText.From(sourceText, Encoding.UTF8));
        }
    }

    /// <summary>
    ///     将属性信息添加到按类型分组的字典中。
    /// </summary>
    private static void add_property(Dictionary<string, List<ObservablePropertyInfo>> grouped,
        ObservablePropertyInfo prop)
    {
        if (!grouped.TryGetValue(prop.fully_qualified_name, out var list))
        {
            list = [];
            grouped[prop.fully_qualified_name] = list;
        }

        list.Add(prop);
    }

    /// <summary>
    ///     生成单个类型的可观察属性源代码。
    /// </summary>
    private static string generate_observable_source(ObservablePropertyInfo first, List<ObservablePropertyInfo> props)
    {
        var sb = new SourceTextBuilder();
        sb.append_line("// <auto-generated />");
        sb.append_line("#nullable enable");
        sb.append_line();
        sb.append_line("using System;");
        sb.append_line("using System.ComponentModel;");
        sb.append_line("using System.Threading;");
        sb.append_line("using System.Threading.Tasks;");
        sb.append_line();

        if (!string.IsNullOrEmpty(first.namespace_name))
        {
            sb.append_line($"namespace {first.namespace_name};");
            sb.append_line();
        }

        sb.append_line("/// <summary>");
        sb.append_line($"/// <c>{first.type_name}</c> 的防抖/节流可观察属性实现。");
        sb.append_line("/// </summary>");
        sb.append_line($"public partial class {first.type_name}");
        using (sb.block())
        {
            generate_timer_fields(sb, props);
            sb.append_line();
            generate_wrapped_properties(sb, props);
            sb.append_line();
            generate_dispose_method(sb, props);
        }

        return sb.ToString();
    }

    /// <summary>
    ///     生成定时器后备字段。
    /// </summary>
    private static void generate_timer_fields(SourceTextBuilder sb, List<ObservablePropertyInfo> props)
    {
        sb.append_line("#region 定时器字段");
        sb.append_line();

        foreach (var prop in props)
            if (prop.kind == ObservableKind.debounce)
            {
                sb.append_line($"private global::System.Threading.Timer? __{prop.property_name}_debounce_timer;");
                sb.append_line($"private {prop.type_full_name} __{prop.property_name}_pending_value;");
            }
            else
            {
                sb.append_line($"private global::System.Threading.Timer? __{prop.property_name}_throttle_timer;");
                sb.append_line($"private long __{prop.property_name}_last_notify_time;");
            }

        sb.append_line();
        sb.append_line("#endregion");
    }

    /// <summary>
    ///     生成防抖/节流包装属性。
    /// </summary>
    private static void generate_wrapped_properties(SourceTextBuilder sb, List<ObservablePropertyInfo> props)
    {
        sb.append_line("#region 防抖/节流属性");
        sb.append_line();

        foreach (var prop in props)
        {
            if (prop.kind == ObservableKind.debounce)
                generate_debounce_property(sb, prop);
            else
                generate_throttle_property(sb, prop);

            sb.append_line();
        }

        sb.append_line("#endregion");
    }

    /// <summary>
    ///     生成防抖属性。
    /// </summary>
    private static void generate_debounce_property(SourceTextBuilder sb, ObservablePropertyInfo prop)
    {
        sb.append_line("/// <summary>");
        sb.append_line($"/// 防抖属性 <c>{prop.property_name}</c>，在值更改后 {prop.milliseconds} 毫秒触发通知。");
        sb.append_line("/// </summary>");
        sb.append_line($"public {prop.type_full_name} {prop.property_name}_debounced");
        using (sb.block())
        {
            sb.append_line($"get => {prop.property_name};");
            sb.append_line("set");
            using (sb.block())
            {
                sb.append_line($"__{prop.property_name}_pending_value = value;");
                sb.append_line($"__{prop.property_name}_debounce_timer?.Dispose();");
                sb.append_line($"__{prop.property_name}_debounce_timer = new global::System.Threading.Timer(__ =>");
                using (sb.block())
                {
                    sb.append_line($"{prop.property_name} = __{prop.property_name}_pending_value;");
                }

                sb.append_line($", null, {prop.milliseconds}, global::System.Threading.Timeout.Infinite);");
            }
        }
    }

    /// <summary>
    ///     生成节流属性。
    /// </summary>
    private static void generate_throttle_property(SourceTextBuilder sb, ObservablePropertyInfo prop)
    {
        sb.append_line("/// <summary>");
        sb.append_line($"/// 节流属性 <c>{prop.property_name}</c>，每 {prop.milliseconds} 毫秒最多触发一次通知。");
        sb.append_line("/// </summary>");
        sb.append_line($"public {prop.type_full_name} {prop.property_name}_throttled");
        using (sb.block())
        {
            sb.append_line($"get => {prop.property_name};");
            sb.append_line("set");
            using (sb.block())
            {
                sb.append_line($"{prop.property_name} = value;");
                sb.append_line("var __now = global::System.Diagnostics.Stopwatch.GetTimestamp();");
                sb.append_line(
                    $"var __elapsed = (long)((double)(__now - __{prop.property_name}_last_notify_time) / global::System.Diagnostics.Stopwatch.Frequency * 1000);");
                sb.append_line();
                sb.append_line($"if (__elapsed >= {prop.milliseconds})");
                using (sb.block())
                {
                    sb.append_line($"__{prop.property_name}_last_notify_time = __now;");
                    sb.append_line($"on_property_changed(nameof({prop.property_name}));");
                }
            }
        }
    }

    /// <summary>
    ///     生成 <c>Dispose</c> 方法清理定时器。
    /// </summary>
    private static void generate_dispose_method(SourceTextBuilder sb, List<ObservablePropertyInfo> props)
    {
        var hasTimers = props.Any(p => p.kind is ObservableKind.debounce or ObservableKind.throttle);

        if (!hasTimers) return;

        sb.append_line("/// <summary>");
        sb.append_line("/// 释放防抖/节流定时器资源。");
        sb.append_line("/// </summary>");
        sb.append_line("public void dispose_observable_timers()");
        using (sb.block())
        {
            foreach (var prop in props)
                if (prop.kind == ObservableKind.debounce)
                    sb.append_line($"__{prop.property_name}_debounce_timer?.Dispose();");
                else
                    sb.append_line($"__{prop.property_name}_throttle_timer?.Dispose();");
        }
    }

    #region 数据模型

    /// <summary>
    ///     可观察属性信息。
    /// </summary>
    internal readonly struct ObservablePropertyInfo
    {
        /// <summary>
        ///     类型名称。
        /// </summary>
        public readonly string type_name;

        /// <summary>
        ///     完全限定类型名称。
        /// </summary>
        public readonly string fully_qualified_name;

        /// <summary>
        ///     命名空间名称。
        /// </summary>
        public readonly string? namespace_name;

        /// <summary>
        ///     属性名称。
        /// </summary>
        public readonly string property_name;

        /// <summary>
        ///     属性类型的完全限定名称。
        /// </summary>
        public readonly string type_full_name;

        /// <summary>
        ///     可观察种类。
        /// </summary>
        public readonly ObservableKind kind;

        /// <summary>
        ///     延迟/节流毫秒数。
        /// </summary>
        public readonly int milliseconds;

        /// <summary>
        ///     初始化 <see cref="ObservablePropertyInfo" /> 的新实例。
        /// </summary>
        public ObservablePropertyInfo(
            string typeName,
            string fullyQualifiedName,
            string? namespaceName,
            string propertyName,
            string typeFullName,
            ObservableKind kind,
            int milliseconds)
        {
            type_name = typeName;
            fully_qualified_name = fullyQualifiedName;
            namespace_name = namespaceName;
            property_name = propertyName;
            type_full_name = typeFullName;
            this.kind = kind;
            this.milliseconds = milliseconds;
        }
    }

    /// <summary>
    ///     可观察种类。
    /// </summary>
    internal enum ObservableKind
    {
        /// <summary>
        ///     防抖。
        /// </summary>
        debounce,

        /// <summary>
        ///     节流。
        /// </summary>
        throttle
    }

    #endregion
}