using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     寻路代码生成器，消费 Sonic.Standard.Simulation.Pathfinding.PathfindAttribute 生成寻路实现骨架
/// </summary>
[Generator]
public sealed class PathfindingGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了 PathfindAttribute 的类信息
    /// </summary>
    private static TypeInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var node = ctx.Node as ClassDeclarationSyntax;
        if (node is null) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(node) as INamedTypeSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Simulation.Pathfinding.PathfindAttribute")
                return new TypeInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name);
        }

        return null;
    }

    /// <summary>
    ///     生成寻路代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, TypeInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Sonic.Standard.Simulation.Pathfinding;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的寻路实现");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public partial class {info.Value.ClassName} : IPathfinder");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 从起点到终点寻路");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine(
            "        public System.Collections.Generic.IReadOnlyList<IPathNode> find_path(IPathNode start, IPathNode end)");
        sb.AppendLine("        {");
        sb.AppendLine("            var pathfinder = new AStarPathfinder();");
        sb.AppendLine("            return pathfinder.find_path(start, end);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}Pathfinding.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     类型信息记录
    /// </summary>
    private readonly struct TypeInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }

        public TypeInfo(string namespace_, string className)
        {
            Namespace = namespace_;
            ClassName = className;
        }
    }
}