using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     物理代码生成器，消费 Sonic.Standard.Simulation.Physics.RigidBodyAttribute 和
///     Sonic.Standard.Simulation.Physics.ColliderAttribute 生成物理体注册代码
/// </summary>
[Generator]
public sealed class PhysicsGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了物理属性的类信息
    /// </summary>
    private static TypeInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var node = ctx.Node as ClassDeclarationSyntax;
        if (node is null) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(node) as INamedTypeSymbol;
        if (symbol is null) return null;

        var mass = 1.0f;
        var shape = "sphere";
        var found = false;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Simulation.Physics.RigidBodyAttribute")
            {
                mass = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "mass").Value.Value as float? ?? 1.0f;
                found = true;
            }

            if (attrName == "Sonic.Standard.Simulation.Physics.ColliderAttribute")
            {
                shape = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "shape").Value.Value as string ?? "sphere";
                found = true;
            }
        }

        return found ? new TypeInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, mass, shape) : null;
    }

    /// <summary>
    ///     生成物理体注册代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, TypeInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Sonic.Standard.Simulation.Physics;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的物理体注册");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class {info.Value.ClassName}PhysicsExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 将 {info.Value.ClassName} 注册到物理世界");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine(
            $"        public static void Register{info.Value.ClassName}(this PhysicsWorld world, {info.Value.ClassName} instance)");
        sb.AppendLine("        {");
        sb.AppendLine($"            // 质量: {info.Value.Mass}, 形状: {info.Value.Shape}");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}Physics.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     类型信息记录
    /// </summary>
    private readonly struct TypeInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public float Mass { get; }
        public string Shape { get; }

        public TypeInfo(string namespace_, string className, float mass, string shape)
        {
            Namespace = namespace_;
            ClassName = className;
            Mass = mass;
            Shape = shape;
        }
    }
}