using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     插件代码生成器，消费 Sonic.Standard.Plugin.PluginAttribute 和 Sonic.Standard.Plugin.ExtensionPointAttribute 生成插件发现代码
/// </summary>
[Generator]
public sealed class PluginGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pluginProvider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax,
                (ctx, _) => ExtractPluginInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(pluginProvider, Generate);
    }

    /// <summary>
    ///     提取标记了 PluginAttribute 的类型信息
    /// </summary>
    private static TypeInfo? ExtractPluginInfo(GeneratorSyntaxContext ctx)
    {
        var node = ctx.Node as ClassDeclarationSyntax;
        if (node is null) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(node) as INamedTypeSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Plugin.PluginAttribute")
            {
                var nameArg = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "name").Value.Value as string;
                var versionArg = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "version").Value.Value as string;
                return new TypeInfo(
                    symbol.ContainingNamespace.ToDisplayString(),
                    symbol.Name,
                    nameArg ?? symbol.Name,
                    versionArg ?? "1.0.0");
            }
        }

        return null;
    }

    /// <summary>
    ///     生成插件注册代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, TypeInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Sonic.Standard.Plugin;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的插件注册扩展方法");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class {info.Value.ClassName}PluginExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 注册 {info.Value.PluginName} 插件到宿主");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static void Register{info.Value.ClassName}(this IPluginHost host)");
        sb.AppendLine("    {");
        sb.AppendLine($"            var plugin = new {info.Value.ClassName}();");
        sb.AppendLine("            plugin.initialize(host);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}Plugin.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     类型信息记录
    /// </summary>
    private readonly struct TypeInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string PluginName { get; }
        public string Version { get; }

        public TypeInfo(string namespace_, string className, string pluginName, string version)
        {
            Namespace = namespace_;
            ClassName = className;
            PluginName = pluginName;
            Version = version;
        }
    }
}