using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     调度代码生成器，消费 Sonic.Standard.Chrono.Scheduling.CronJobAttribute 生成定时任务注册代码
/// </summary>
[Generator]
public sealed class SchedulingGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is MethodDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了 CronJobAttribute 的方法信息
    /// </summary>
    private static MethodInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var node = ctx.Node as MethodDeclarationSyntax;
        if (node is null) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(node) as IMethodSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Chrono.Scheduling.CronJobAttribute")
            {
                var expression = attr.ConstructorArguments.FirstOrDefault().Value as string ?? "* * * * *";
                return new MethodInfo(
                    symbol.ContainingType.ContainingNamespace.ToDisplayString(),
                    symbol.ContainingType.Name,
                    symbol.Name,
                    expression);
            }
        }

        return null;
    }

    /// <summary>
    ///     生成定时任务注册代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, MethodInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Sonic.Standard.State.Chrono;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName}.{info.Value.MethodName} 生成的定时任务注册");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class {info.Value.ClassName}{info.Value.MethodName}SchedulingExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 注册定时任务 {info.Value.MethodName}");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static void Register{info.Value.MethodName}Job(this CronScheduler scheduler)");
        sb.AppendLine("        {");
        sb.AppendLine(
            $"            scheduler.schedule(\"{info.Value.Expression}\", () => {{ var instance = new {info.Value.ClassName}(); instance.{info.Value.MethodName}(); }});");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}{info.Value.MethodName}Scheduling.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     方法信息记录
    /// </summary>
    private readonly struct MethodInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string MethodName { get; }
        public string Expression { get; }

        public MethodInfo(string namespace_, string className, string methodName, string expression)
        {
            Namespace = namespace_;
            ClassName = className;
            MethodName = methodName;
            Expression = expression;
        }
    }
}