using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     为包含 <c>[Observable]</c> 属性的类自动生成 <c>INotifyPropertyChanged</c> 实现，
///     并为 <c>[Derived]</c> 属性生成依赖可观察属性的计算属性。
/// </summary>
[Generator]
public sealed class StateGenerator : IIncrementalGenerator
{
    private const string _observable_attribute_full_name = "Sonic.Standard.State.ObservableAttribute";
    private const string _derived_attribute_full_name = "Sonic.Standard.State.DerivedAttribute";

    /// <summary>
    ///     初始化增量源代码生成管道。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _observable_attribute_full_name,
                static (node, _) => node is TypeDeclarationSyntax typeDecl &&
                                    typeDecl.Modifiers.Any(SyntaxKind.PartialKeyword),
                static (ctx, ct) => transform_state(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value)
            .Collect();

        context.RegisterSourceOutput(targetTypes, generate_source);
    }

    /// <summary>
    ///     提取状态类型信息。
    /// </summary>
    private static StateTypeInfo? transform_state(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        var typeSymbol = (INamedTypeSymbol)context.TargetSymbol;

        var observableProps = new List<ObservablePropertyInfo>();
        var derivedProps = new List<DerivedPropertyInfo>();

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member.IsStatic) continue;

            if (member is not IPropertySymbol prop) continue;

            if (prop.DeclaredAccessibility != Accessibility.Public) continue;

            var observableAttr = prop.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
                $"global::{_observable_attribute_full_name}");

            if (observableAttr is not null)
            {
                observableProps.Add(new ObservablePropertyInfo(
                    prop.Name,
                    prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    prop.SetMethod is not null && prop.SetMethod.DeclaredAccessibility == Accessibility.Public));
                continue;
            }

            var derivedAttr = prop.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
                $"global::{_derived_attribute_full_name}");

            if (derivedAttr is not null)
            {
                var dependencies = find_dependencies(prop, observableProps);
                var hasGetter = prop.GetMethod is not null;

                derivedProps.Add(new DerivedPropertyInfo(
                    prop.Name,
                    prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    dependencies,
                    hasGetter));
            }
        }

        if (observableProps.Count == 0) return null;

        return new StateTypeInfo(
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.ContainingNamespace?.ToDisplayString(),
            typeSymbol.TypeKind == TypeKind.Struct,
            observableProps,
            derivedProps);
    }

    /// <summary>
    ///     查找派生属性依赖的可观察属性。
    /// </summary>
    private static List<string> find_dependencies(IPropertySymbol prop, List<ObservablePropertyInfo> observableProps)
    {
        var dependencies = new List<string>();

        if (prop.GetMethod is null) return dependencies;

        foreach (var observable in observableProps) dependencies.Add(observable.name);

        return dependencies;
    }

    /// <summary>
    ///     生成所有状态类型的源代码。
    /// </summary>
    private static void generate_source(SourceProductionContext context, ImmutableArray<StateTypeInfo> typeInfos)
    {
        foreach (var info in typeInfos)
        {
            var sourceText = generate_state_source(info);
            var hintName = $"{info.type_name}.State.g.cs";
            context.AddSource(hintName, SourceText.From(sourceText, Encoding.UTF8));
        }
    }

    /// <summary>
    ///     生成单个状态类型的源代码。
    /// </summary>
    private static string generate_state_source(StateTypeInfo info)
    {
        var sb = new SourceTextBuilder();
        sb.append_line("// <auto-generated />");
        sb.append_line("#nullable enable");
        sb.append_line();
        sb.append_line("using System;");
        sb.append_line("using System.ComponentModel;");
        sb.append_line("using System.Runtime.CompilerServices;");
        sb.append_line();

        if (!string.IsNullOrEmpty(info.namespace_name))
        {
            sb.append_line($"namespace {info.namespace_name};");
            sb.append_line();
        }

        var typeKeyword = info.is_struct ? "partial struct" : "partial class";
        sb.append_line("/// <summary>");
        sb.append_line($"/// <c>{info.type_name}</c> 的可观察状态实现。");
        sb.append_line("/// </summary>");
        sb.append_line($"public {typeKeyword} {info.type_name} : global::System.ComponentModel.INotifyPropertyChanged");
        using (sb.block())
        {
            generate_event(sb);
            sb.append_line();
            generate_backing_fields(sb, info);
            sb.append_line();
            generate_observable_properties(sb, info);
            sb.append_line();
            generate_derived_properties(sb, info);
            sb.append_line();
            generate_set_field_method(sb, info);
        }

        return sb.ToString();
    }

    /// <summary>
    ///     生成 <c>PropertyChanged</c> 事件。
    /// </summary>
    private static void generate_event(SourceTextBuilder sb)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 当属性值更改时触发。");
        sb.append_line("/// </summary>");
        sb.append_line("public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;");
    }

    /// <summary>
    ///     生成可观察属性的后备字段。
    /// </summary>
    private static void generate_backing_fields(SourceTextBuilder sb, StateTypeInfo info)
    {
        sb.append_line("#region 后备字段");
        sb.append_line();

        foreach (var prop in info.observable_properties)
            sb.append_line($"private {prop.type_full_name} __{prop.name};");

        sb.append_line();
        sb.append_line("#endregion");
    }

    /// <summary>
    ///     生成可观察属性，在值更改时触发 <c>PropertyChanged</c> 事件。
    /// </summary>
    private static void generate_observable_properties(SourceTextBuilder sb, StateTypeInfo info)
    {
        sb.append_line("#region 可观察属性");
        sb.append_line();

        foreach (var prop in info.observable_properties)
        {
            sb.append_line("/// <summary>");
            sb.append_line($"/// 可观察属性 <c>{prop.name}</c>，值更改时触发 <c>PropertyChanged</c> 事件。");
            sb.append_line("/// </summary>");
            sb.append_line($"public {prop.type_full_name} {prop.name}");
            using (sb.block())
            {
                sb.append_line($"get => __{prop.name};");
                sb.append_line("set");
                using (sb.block())
                {
                    if (prop.has_setter)
                        sb.append_line(
                            $"if (global::System.Collections.Generic.EqualityComparer<{prop.type_full_name}>.Default.Equals(__{prop.name}, value)) return;");
                    else
                        sb.append_line(
                            $"if (global::System.Collections.Generic.EqualityComparer<{prop.type_full_name}>.Default.Equals(__{prop.name}, value)) return;");

                    sb.append_line($"__{prop.name} = value;");
                    sb.append_line($"on_property_changed(nameof({prop.name}));");
                }
            }

            sb.append_line();
        }

        sb.append_line("#endregion");
    }

    /// <summary>
    ///     生成派生属性，依赖可观察属性并在其更改时触发通知。
    /// </summary>
    private static void generate_derived_properties(SourceTextBuilder sb, StateTypeInfo info)
    {
        if (info.derived_properties.Count == 0) return;

        sb.append_line("#region 派生属性");
        sb.append_line();

        foreach (var prop in info.derived_properties)
        {
            sb.append_line("/// <summary>");
            sb.append_line($"/// 派生属性 <c>{prop.name}</c>，依赖可观察属性自动计算。");
            sb.append_line("/// </summary>");
            sb.append_line($"public {prop.type_full_name} {prop.name} => {prop.name};");

            sb.append_line();
        }

        sb.append_line("#endregion");
    }

    /// <summary>
    ///     生成 <c>on_property_changed</c> 方法和 <c>set_field</c> 辅助方法。
    /// </summary>
    private static void generate_set_field_method(SourceTextBuilder sb, StateTypeInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 触发 <c>PropertyChanged</c> 事件。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"propertyName\">更改的属性名称。</param>");
        sb.append_line("protected virtual void on_property_changed([CallerMemberName] string? propertyName = null)");
        using (sb.block())
        {
            sb.append_line(
                "PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));");
        }

        sb.append_line();

        sb.append_line("/// <summary>");
        sb.append_line("/// 设置字段值并在值更改时触发 <c>PropertyChanged</c> 事件。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <typeparam name=\"T\">字段类型。</typeparam>");
        sb.append_line("/// <param name=\"field\">字段引用。</param>");
        sb.append_line("/// <param name=\"value\">新值。</param>");
        sb.append_line("/// <param name=\"propertyName\">属性名称。</param>");
        sb.append_line("/// <returns>值是否更改。</returns>");
        sb.append_line(
            "protected bool set_field<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)");
        using (sb.block())
        {
            sb.append_line(
                "if (global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(field, value)) return false;");
            sb.append_line();
            sb.append_line("field = value;");
            sb.append_line("on_property_changed(propertyName);");

            foreach (var derived in info.derived_properties)
            foreach (var dep in derived.dependencies)
                sb.append_line($"if (propertyName == nameof({dep})) on_property_changed(nameof({derived.name}));");

            sb.append_line();
            sb.append_line("return true;");
        }
    }

    #region 数据模型

    /// <summary>
    ///     状态类型信息。
    /// </summary>
    internal readonly struct StateTypeInfo
    {
        /// <summary>
        ///     类型名称。
        /// </summary>
        public readonly string type_name;

        /// <summary>
        ///     完全限定类型名称。
        /// </summary>
        public readonly string fully_qualified_name;

        /// <summary>
        ///     命名空间名称。
        /// </summary>
        public readonly string? namespace_name;

        /// <summary>
        ///     是否为结构体。
        /// </summary>
        public readonly bool is_struct;

        /// <summary>
        ///     可观察属性列表。
        /// </summary>
        public readonly List<ObservablePropertyInfo> observable_properties;

        /// <summary>
        ///     派生属性列表。
        /// </summary>
        public readonly List<DerivedPropertyInfo> derived_properties;

        /// <summary>
        ///     初始化 <see cref="StateTypeInfo" /> 的新实例。
        /// </summary>
        public StateTypeInfo(
            string typeName,
            string fullyQualifiedName,
            string? namespaceName,
            bool isStruct,
            List<ObservablePropertyInfo> observableProperties,
            List<DerivedPropertyInfo> derivedProperties)
        {
            type_name = typeName;
            fully_qualified_name = fullyQualifiedName;
            namespace_name = namespaceName;
            is_struct = isStruct;
            observable_properties = observableProperties;
            derived_properties = derivedProperties;
        }
    }

    /// <summary>
    ///     可观察属性信息。
    /// </summary>
    internal readonly struct ObservablePropertyInfo
    {
        /// <summary>
        ///     属性名称。
        /// </summary>
        public readonly string name;

        /// <summary>
        ///     类型的完全限定名称。
        /// </summary>
        public readonly string type_full_name;

        /// <summary>
        ///     是否有公共 setter。
        /// </summary>
        public readonly bool has_setter;

        /// <summary>
        ///     初始化 <see cref="ObservablePropertyInfo" /> 的新实例。
        /// </summary>
        public ObservablePropertyInfo(string name, string typeFullName, bool hasSetter)
        {
            this.name = name;
            type_full_name = typeFullName;
            has_setter = hasSetter;
        }
    }

    /// <summary>
    ///     派生属性信息。
    /// </summary>
    internal readonly struct DerivedPropertyInfo
    {
        /// <summary>
        ///     属性名称。
        /// </summary>
        public readonly string name;

        /// <summary>
        ///     类型的完全限定名称。
        /// </summary>
        public readonly string type_full_name;

        /// <summary>
        ///     依赖的可观察属性名称列表。
        /// </summary>
        public readonly List<string> dependencies;

        /// <summary>
        ///     是否有 getter。
        /// </summary>
        public readonly bool has_getter;

        /// <summary>
        ///     初始化 <see cref="DerivedPropertyInfo" /> 的新实例。
        /// </summary>
        public DerivedPropertyInfo(string name, string typeFullName, List<string> dependencies, bool hasGetter)
        {
            this.name = name;
            type_full_name = typeFullName;
            this.dependencies = dependencies;
            has_getter = hasGetter;
        }
    }

    #endregion
}