using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     样式代码生成器，消费 Sonic.Standard.Widget.Style.ThemeAttribute 和 Sonic.Standard.Widget.Style.StyleAttribute 生成主题和样式代码
/// </summary>
[Generator]
public sealed class StyleGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了 ThemeAttribute 或 StyleAttribute 的类型信息
    /// </summary>
    private static TypeInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var node = ctx.Node as ClassDeclarationSyntax;
        if (node is null) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(node) as INamedTypeSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Widget.Style.ThemeAttribute")
                return new TypeInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, "Theme");
            if (attrName == "Sonic.Standard.Widget.Style.StyleAttribute")
                return new TypeInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, "Style");
        }

        return null;
    }

    /// <summary>
    ///     生成样式或主题代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, TypeInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Sonic.Standard.Widget.Style;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的 {info.Value.Kind} 注册");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class {info.Value.ClassName}{info.Value.Kind}Extensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// 注册 {info.Value.ClassName} {info.Value.Kind}");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine(
            $"        public static void Register{info.Value.ClassName}{info.Value.Kind}(this IStyleProvider provider)");
        sb.AppendLine("        {");
        sb.AppendLine(
            $"            provider.register(typeof({info.Value.ClassName}).FullName!, new {info.Value.ClassName}());");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}{info.Value.Kind}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     类型信息记录
    /// </summary>
    private readonly struct TypeInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string Kind { get; }

        public TypeInfo(string namespace_, string className, string kind)
        {
            Namespace = namespace_;
            ClassName = className;
            Kind = kind;
        }
    }
}