using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     为标记了 <c>[TranspileTo]</c> 特性的类型自动生成类型定义导出代码，
///     根据目标语言生成对应的类型声明。
/// </summary>
[Generator]
public sealed class TranspileGenerator : IIncrementalGenerator
{
    private const string _transpile_to_attribute_full_name =
        "Sonic.Standard.Compiler.Transpilation.TranspileToAttribute";

    /// <summary>
    ///     初始化增量源代码生成管道。
    /// </summary>
    /// <param name="context">增量生成器初始化上下文。</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _transpile_to_attribute_full_name,
                static (node, _) => node is TypeDeclarationSyntax typeDecl &&
                                    typeDecl.Modifiers.Any(SyntaxKind.PartialKeyword),
                static (ctx, ct) => transform_transpile(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value)
            .Collect();

        context.RegisterSourceOutput(targetTypes, generate_source);
    }

    /// <summary>
    ///     提取标记了 <c>[TranspileTo]</c> 特性的类型信息。
    /// </summary>
    private static TranspileTypeInfo? transform_transpile(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        var typeSymbol = (INamedTypeSymbol)context.TargetSymbol;

        var targetLanguages = new List<int>();

        foreach (var attr in context.Attributes)
        {
            if (attr.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) !=
                $"global::{_transpile_to_attribute_full_name}")
                continue;

            if (attr.ConstructorArguments.Length > 0 &&
                attr.ConstructorArguments[0].Values.Length > 0)
                foreach (var arg in attr.ConstructorArguments[0].Values)
                    if (arg.Value is int langVal)
                        targetLanguages.Add(langVal);
        }

        if (targetLanguages.Count == 0) return null;

        var members = extract_type_members(typeSymbol);

        return new TranspileTypeInfo(
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.ContainingNamespace?.ToDisplayString(),
            typeSymbol.TypeKind == TypeKind.Struct,
            targetLanguages,
            members);
    }

    /// <summary>
    ///     提取类型的公共属性和字段信息。
    /// </summary>
    private static List<TranspileMemberInfo> extract_type_members(INamedTypeSymbol typeSymbol)
    {
        var members = new List<TranspileMemberInfo>();

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member.IsStatic) continue;

            if (member.DeclaredAccessibility != Accessibility.Public) continue;

            if (member is IPropertySymbol prop)
            {
                if (prop.IsWriteOnly) continue;

                members.Add(new TranspileMemberInfo(
                    prop.Name,
                    prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    prop.Type.SpecialType));
            }
            else if (member is IFieldSymbol field)
            {
                members.Add(new TranspileMemberInfo(
                    field.Name,
                    field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    field.Type.SpecialType));
            }
        }

        return members;
    }

    /// <summary>
    ///     生成所有转译类型的源代码。
    /// </summary>
    private static void generate_source(SourceProductionContext context, ImmutableArray<TranspileTypeInfo> typeInfos)
    {
        foreach (var info in typeInfos)
        {
            var sourceText = generate_transpile_source(info);
            var hintName = $"{info.type_name}.Transpile.g.cs";
            context.AddSource(hintName, SourceText.From(sourceText, Encoding.UTF8));
        }
    }

    /// <summary>
    ///     生成单个类型的转译源代码。
    /// </summary>
    private static string generate_transpile_source(TranspileTypeInfo info)
    {
        var sb = new SourceTextBuilder();
        sb.append_line("// <auto-generated />");
        sb.append_line("#nullable enable");
        sb.append_line();
        sb.append_line("using System.Text;");
        sb.append_line();

        if (!string.IsNullOrEmpty(info.namespace_name))
        {
            sb.append_line($"namespace {info.namespace_name};");
            sb.append_line();
        }

        var typeKeyword = info.is_struct ? "partial struct" : "partial class";
        sb.append_line($"{typeKeyword} {info.type_name}");
        using (sb.block())
        {
            generate_export_method(sb, info);
        }

        return sb.ToString();
    }

    /// <summary>
    ///     生成 <c>export_type_definition</c> 方法，按目标语言生成类型定义。
    /// </summary>
    private static void generate_export_method(SourceTextBuilder sb, TranspileTypeInfo info)
    {
        sb.append_line("/// <summary>");
        sb.append_line("/// 将当前类型定义导出为指定目标语言的类型声明。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <param name=\"language\">目标语言。</param>");
        sb.append_line("/// <returns>目标语言的类型定义字符串。</returns>");
        sb.append_line(
            "public string export_type_definition(global::Sonic.Standard.Compiler.Transpilation.TargetLanguage language)");
        using (sb.block())
        {
            sb.append_line("return language switch");
            using (sb.block())
            {
                foreach (var lang in info.target_languages.Distinct())
                {
                    var langName = (TargetLanguage)lang;
                    sb.append_line(
                        $"global::Sonic.Standard.Compiler.Transpilation.TargetLanguage.{langName} => export_{langName}(),");
                }

                sb.append_line(
                    "_ => throw new global::System.ArgumentOutOfRangeException(nameof(language), language, \"不支持的目标语言\"),");
            }

            sb.append_line(";");
        }

        sb.append_line();

        foreach (var lang in info.target_languages.Distinct())
        {
            var langName = (TargetLanguage)lang;
            generate_language_export_method(sb, info, langName);
            sb.append_line();
        }
    }

    /// <summary>
    ///     生成特定语言的类型导出方法。
    /// </summary>
    private static void generate_language_export_method(SourceTextBuilder sb, TranspileTypeInfo info,
        TargetLanguage language)
    {
        sb.append_line("/// <summary>");
        sb.append_line($"/// 导出为 <c>{language}</c> 语言的类型定义。");
        sb.append_line("/// </summary>");
        sb.append_line("/// <returns>类型定义字符串。</returns>");
        sb.append_line($"private string export_{language}()");
        using (sb.block())
        {
            sb.append_line("var __sb = new global::System.Text.StringBuilder();");

            var (typeKeyword, separator, lineEnd) = get_language_syntax(language);

            sb.append_line($"__sb.AppendLine(\"{typeKeyword} {info.type_name} {separator}\");");

            for (var i = 0; i < info.members.Count; i++)
            {
                var member = info.members[i];
                var langType = map_type_to_language(member.special_type, language);
                var comma = i < info.members.Count - 1 ? "," : "";
                sb.append_line($"__sb.AppendLine(\"    {langType} {member.name}{comma}{lineEnd}\");");
            }

            sb.append_line("__sb.AppendLine(\"}\");");
            sb.append_line("return __sb.ToString();");
        }
    }

    /// <summary>
    ///     获取目标语言的语法格式。
    /// </summary>
    private static (string typeKeyword, string separator, string lineEnd) get_language_syntax(TargetLanguage language)
    {
        return language switch
        {
            TargetLanguage.type_script => ("interface", "{", ""),
            TargetLanguage.java_script => ("interface", "{", ""),
            TargetLanguage.python => ("class", ":", ""),
            TargetLanguage.java => ("class", "{", ";"),
            TargetLanguage.go => ("type struct", "{", ""),
            TargetLanguage.rust => ("struct", "{", ","),
            TargetLanguage.swift => ("struct", "{", ""),
            TargetLanguage.kotlin => ("data class", "{", ","),
            TargetLanguage.cpp => ("struct", "{", ";"),
            _ => ("class", "{", "")
        };
    }

    /// <summary>
    ///     将特殊类型映射为目标语言的类型名称。
    /// </summary>
    private static string map_type_to_language(SpecialType specialType, TargetLanguage language)
    {
        return language switch
        {
            TargetLanguage.type_script => map_to_typescript(specialType),
            TargetLanguage.java_script => map_to_typescript(specialType),
            TargetLanguage.python => map_to_python(specialType),
            TargetLanguage.java => map_to_java(specialType),
            TargetLanguage.go => map_to_go(specialType),
            TargetLanguage.rust => map_to_rust(specialType),
            TargetLanguage.swift => map_to_swift(specialType),
            TargetLanguage.kotlin => map_to_kotlin(specialType),
            TargetLanguage.cpp => map_to_cpp(specialType),
            _ => specialType.ToString()
        };
    }

    /// <summary>
    ///     映射为 TypeScript 类型。
    /// </summary>
    private static string map_to_typescript(SpecialType specialType)
    {
        return specialType switch
        {
            SpecialType.System_String => "string",
            SpecialType.System_Int32 => "number",
            SpecialType.System_Int64 => "number",
            SpecialType.System_UInt64 => "number",
            SpecialType.System_Boolean => "boolean",
            SpecialType.System_Double => "number",
            SpecialType.System_Single => "number",
            _ => "any"
        };
    }

    /// <summary>
    ///     映射为 Python 类型。
    /// </summary>
    private static string map_to_python(SpecialType specialType)
    {
        return specialType switch
        {
            SpecialType.System_String => "str",
            SpecialType.System_Int32 => "int",
            SpecialType.System_Int64 => "int",
            SpecialType.System_UInt64 => "int",
            SpecialType.System_Boolean => "bool",
            SpecialType.System_Double => "float",
            SpecialType.System_Single => "float",
            _ => "Any"
        };
    }

    /// <summary>
    ///     映射为 Java 类型。
    /// </summary>
    private static string map_to_java(SpecialType specialType)
    {
        return specialType switch
        {
            SpecialType.System_String => "String",
            SpecialType.System_Int32 => "int",
            SpecialType.System_Int64 => "long",
            SpecialType.System_UInt64 => "long",
            SpecialType.System_Boolean => "boolean",
            SpecialType.System_Double => "double",
            SpecialType.System_Single => "float",
            _ => "Object"
        };
    }

    /// <summary>
    ///     映射为 Go 类型。
    /// </summary>
    private static string map_to_go(SpecialType specialType)
    {
        return specialType switch
        {
            SpecialType.System_String => "string",
            SpecialType.System_Int32 => "int32",
            SpecialType.System_Int64 => "int64",
            SpecialType.System_UInt64 => "uint64",
            SpecialType.System_Boolean => "bool",
            SpecialType.System_Double => "float64",
            SpecialType.System_Single => "float32",
            _ => "interface{}"
        };
    }

    /// <summary>
    ///     映射为 Rust 类型。
    /// </summary>
    private static string map_to_rust(SpecialType specialType)
    {
        return specialType switch
        {
            SpecialType.System_String => "String",
            SpecialType.System_Int32 => "i32",
            SpecialType.System_Int64 => "i64",
            SpecialType.System_UInt64 => "u64",
            SpecialType.System_Boolean => "bool",
            SpecialType.System_Double => "f64",
            SpecialType.System_Single => "f32",
            _ => "Box<dyn Any>"
        };
    }

    /// <summary>
    ///     映射为 Swift 类型。
    /// </summary>
    private static string map_to_swift(SpecialType specialType)
    {
        return specialType switch
        {
            SpecialType.System_String => "String",
            SpecialType.System_Int32 => "Int32",
            SpecialType.System_Int64 => "Int64",
            SpecialType.System_UInt64 => "UInt64",
            SpecialType.System_Boolean => "Bool",
            SpecialType.System_Double => "Double",
            SpecialType.System_Single => "Float",
            _ => "Any"
        };
    }

    /// <summary>
    ///     映射为 Kotlin 类型。
    /// </summary>
    private static string map_to_kotlin(SpecialType specialType)
    {
        return specialType switch
        {
            SpecialType.System_String => "String",
            SpecialType.System_Int32 => "Int",
            SpecialType.System_Int64 => "Long",
            SpecialType.System_UInt64 => "ULong",
            SpecialType.System_Boolean => "Boolean",
            SpecialType.System_Double => "Double",
            SpecialType.System_Single => "Float",
            _ => "Any"
        };
    }

    /// <summary>
    ///     映射为 C++ 类型。
    /// </summary>
    private static string map_to_cpp(SpecialType specialType)
    {
        return specialType switch
        {
            SpecialType.System_String => "std::string",
            SpecialType.System_Int32 => "int32_t",
            SpecialType.System_Int64 => "int64_t",
            SpecialType.System_UInt64 => "uint64_t",
            SpecialType.System_Boolean => "bool",
            SpecialType.System_Double => "double",
            SpecialType.System_Single => "float",
            _ => "std::any"
        };
    }

    #region 数据模型

    /// <summary>
    ///     目标语言枚举，与 Sonic.Core 中定义的 <c>TargetLanguage</c> 对应。
    /// </summary>
    internal enum TargetLanguage
    {
        /// <summary>
        ///     TypeScript 语言。
        /// </summary>
        type_script = 0,

        /// <summary>
        ///     Python 语言。
        /// </summary>
        python = 1,

        /// <summary>
        ///     Java 语言。
        /// </summary>
        java = 2,

        /// <summary>
        ///     Go 语言。
        /// </summary>
        go = 3,

        /// <summary>
        ///     Rust 语言。
        /// </summary>
        rust = 4,

        /// <summary>
        ///     Swift 语言。
        /// </summary>
        swift = 5,

        /// <summary>
        ///     Kotlin 语言。
        /// </summary>
        kotlin = 6,

        /// <summary>
        ///     JavaScript 语言。
        /// </summary>
        java_script = 7,

        /// <summary>
        ///     C++ 语言。
        /// </summary>
        cpp = 8
    }

    /// <summary>
    ///     需要生成转译代码的类型信息。
    /// </summary>
    internal readonly struct TranspileTypeInfo
    {
        /// <summary>
        ///     类型名称。
        /// </summary>
        public readonly string type_name;

        /// <summary>
        ///     完全限定类型名称。
        /// </summary>
        public readonly string fully_qualified_name;

        /// <summary>
        ///     命名空间名称。
        /// </summary>
        public readonly string? namespace_name;

        /// <summary>
        ///     是否为结构体。
        /// </summary>
        public readonly bool is_struct;

        /// <summary>
        ///     目标语言列表。
        /// </summary>
        public readonly List<int> target_languages;

        /// <summary>
        ///     类型成员列表。
        /// </summary>
        public readonly List<TranspileMemberInfo> members;

        /// <summary>
        ///     初始化 <see cref="TranspileTypeInfo" /> 的新实例。
        /// </summary>
        public TranspileTypeInfo(
            string typeName,
            string fullyQualifiedName,
            string? namespaceName,
            bool isStruct,
            List<int> targetLanguages,
            List<TranspileMemberInfo> members)
        {
            type_name = typeName;
            fully_qualified_name = fullyQualifiedName;
            namespace_name = namespaceName;
            is_struct = isStruct;
            target_languages = targetLanguages;
            this.members = members;
        }
    }

    /// <summary>
    ///     转译类型成员信息。
    /// </summary>
    internal readonly struct TranspileMemberInfo
    {
        /// <summary>
        ///     成员名称。
        /// </summary>
        public readonly string name;

        /// <summary>
        ///     完全限定类型名称。
        /// </summary>
        public readonly string fully_qualified_type;

        /// <summary>
        ///     特殊类型。
        /// </summary>
        public readonly SpecialType special_type;

        /// <summary>
        ///     初始化 <see cref="TranspileMemberInfo" /> 的新实例。
        /// </summary>
        public TranspileMemberInfo(string name, string fullyQualifiedType, SpecialType specialType)
        {
            this.name = name;
            fully_qualified_type = fullyQualifiedType;
            special_type = specialType;
        }
    }

    #endregion
}