using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sonic.Data.Generator;

/// <summary>
///     Widget 代码生成器，消费 Sonic.Standard.Widget.PageAttribute 和 Sonic.Standard.Widget.WidgetAttribute 生成 UI 组件基类代码
/// </summary>
[Generator]
public sealed class WidgetGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     初始化生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (node, _) => node is ClassDeclarationSyntax,
                (ctx, _) => ExtractInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, Generate);
    }

    /// <summary>
    ///     提取标记了 PageAttribute 或 WidgetAttribute 的类型信息
    /// </summary>
    private static TypeInfo? ExtractInfo(GeneratorSyntaxContext ctx)
    {
        var node = ctx.Node as ClassDeclarationSyntax;
        if (node is null) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(node) as INamedTypeSymbol;
        if (symbol is null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.ToDisplayString();
            if (attrName == "Sonic.Standard.Widget.PageAttribute")
            {
                var route = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "route").Value.Value as string;
                return new TypeInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, "Page",
                    route ?? $"/{symbol.Name}");
            }

            if (attrName == "Sonic.Standard.Widget.WidgetAttribute")
                return new TypeInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, "Widget", null);
        }

        return null;
    }

    /// <summary>
    ///     生成 Widget 或 Page 代码
    /// </summary>
    private static void Generate(SourceProductionContext ctx, TypeInfo? info)
    {
        if (info is null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Sonic.Standard.Widget;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Value.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// 为 {info.Value.ClassName} 生成的 {info.Value.Kind} 基础设施");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public partial class {info.Value.ClassName}");
        sb.AppendLine("    {");

        if (info.Value.Kind == "Page")
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 页面路由");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public string route => \"{info.Value.Route}\";");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.Value.ClassName}Widget.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    ///     类型信息记录
    /// </summary>
    private readonly struct TypeInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string Kind { get; }
        public string Route { get; }

        public TypeInfo(string namespace_, string className, string kind, string route)
        {
            Namespace = namespace_;
            ClassName = className;
            Kind = kind;
            Route = route;
        }
    }
}