<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <RootNamespace>Nyar.Language.Tailwind</RootNamespace>
        <AssemblyName>Nyar.Language.Tailwind</AssemblyName>
        <Authors>Nyar Team</Authors>
        <Description>Tailwind CSS 工具类系统 — 原子化 CSS 类名生成与自定义配置支持</Description>
            <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Css\Css.csproj" />
    </ItemGroup>
  <ItemGroup>
    <Compile Remove="TailwindStylesheet.cs"/>
  </ItemGroup>
</Project>