using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nyar.Generator;

/// <summary>
///     部分求值源生成器，扫描实现了 <c>I*Algebra&lt;Code&gt;</c> 接口的类中标记
///     <c>[StaticAware]</c> 的方法，并为每个方法生成静态/动态双路径包装器
/// </summary>
[Generator]
public sealed class PEGenerator : ISourceGenerator
{
    #region 辅助方法

    /// <summary>
    ///     清理标识符中的非法字符
    /// </summary>
    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder();
        foreach (var ch in name)
            if (char.IsLetterOrDigit(ch) || ch == '_')
                sb.Append(ch);
            else
                sb.Append('_');

        if (sb.Length == 0) return "_";

        if (char.IsDigit(sb[0])) sb.Insert(0, '_');

        return sb.ToString();
    }

    #endregion

    #region 常量

    private const string StaticAwareAttrFullName = "Nyar.PartialEvaluate.StaticAwareAttribute";
    private const string StaticInterpAttrFullName = "Nyar.PartialEvaluate.StaticInterpretationAttribute";
    private const string IDialectAlgebraFullName = "Nyar.ObjectAlgebra.IDialectAlgebra";

    #endregion

    #region 初始化

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var peMethods = new List<PEMethodInfo>();

        foreach (var tree in context.Compilation.SyntaxTrees)
        {
            var semanticModel = context.Compilation.GetSemanticModel(tree);
            var root = tree.GetRoot();

            foreach (var methodDecl in root.DescendantNodes().OfType<MethodDeclarationSyntax>())
            {
                var methodSymbol = semanticModel.GetDeclaredSymbol(methodDecl) as IMethodSymbol;
                if (methodSymbol is null) continue;

                // [StaticAware] 标记的方法是实例方法，非静态
                if (methodSymbol.IsStatic) continue;

                var staticAwareAttr = methodSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == StaticAwareAttrFullName);

                if (staticAwareAttr is null) continue;

                var containingType = methodSymbol.ContainingType;
                if (containingType is null) continue;

                // 检查包含类型是否实现了 I*Algebra 接口
                var algebraInterfaces = GetAlgebraInterfaces(containingType);
                if (algebraInterfaces.Count == 0) continue;

                // 解析 [StaticInterpretation(typeof(T))]
                var staticInterpAttr = methodSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == StaticInterpAttrFullName);

                var interpTypeName = (string?)null;
                var arg = staticInterpAttr?.ConstructorArguments.FirstOrDefault();
                if (arg?.Value is INamedTypeSymbol interpTypeSymbol)
                    interpTypeName = interpTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                // 分析方法参数
                var paramInfos = new List<PEParamInfo>();
                foreach (var param in methodSymbol.Parameters) paramInfos.Add(AnalyzePEParam(param));

                var returnTypeName = methodSymbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var containingTypeDisplay = containingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                peMethods.Add(new PEMethodInfo(
                    methodSymbol.Name,
                    containingTypeDisplay,
                    algebraInterfaces,
                    paramInfos,
                    returnTypeName,
                    interpTypeName));
            }
        }

        if (peMethods.Count == 0) return;

        // 按包含类型分组生成代码
        var groupedByType = peMethods.GroupBy(m => m.ContainingTypeDisplay);

        foreach (var group in groupedByType)
        {
            var methods = group.ToList();
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.CodeDom.Compiler;");
            sb.AppendLine("using Nyar.ObjectAlgebra;");
            sb.AppendLine();
            sb.AppendLine("namespace Nyar.PartialEvaluate;");
            sb.AppendLine();

            for (var i = 0; i < methods.Count; i++)
            {
                var method = methods[i];
                GenerateWrapperClass(sb, method, "    ");
                if (i < methods.Count - 1) sb.AppendLine();
            }

            var safeTypeName = SanitizeIdentifier(group.Key);
            context.AddSource($"PE_{safeTypeName}_Wrappers.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    #endregion

    #region 分析

    /// <summary>
    ///     获取类型实现的所有代数接口（I*Algebra&lt;E&gt; 且 E 为 Code 或 Expr&lt;T&gt;）
    /// </summary>
    private static List<AlgebraInterfaceInfo> GetAlgebraInterfaces(INamedTypeSymbol typeSymbol)
    {
        var result = new List<AlgebraInterfaceInfo>();

        foreach (var iface in typeSymbol.AllInterfaces)
        {
            if (!IsAlgebraInterface(iface)) continue;

            var typeArgs = iface.TypeArguments;
            if (typeArgs.Length != 1) continue;

            var carrierType = typeArgs[0];
            var carrierDisplay = carrierType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

            var isCode = IsCodeType(carrierType);
            var isExpr = IsExprType(carrierType);
            var exprTypeArg = isExpr ? GetSingleTypeArg(carrierType) : null;

            if (isCode || isExpr)
                result.Add(new AlgebraInterfaceInfo(
                    iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    iface.Name,
                    isCode ? "Code" : "Expr",
                    isCode ? null : exprTypeArg));
        }

        return result;
    }

    /// <summary>
    ///     判断类型是否继承自 IDialectAlgebra&lt;E&gt;
    /// </summary>
    private static bool IsAlgebraInterface(INamedTypeSymbol iface)
    {
        foreach (var parent in iface.AllInterfaces)
            if (parent.OriginalDefinition.ToDisplayString() == IDialectAlgebraFullName)
                return true;

        if (iface.OriginalDefinition.ToDisplayString() == IDialectAlgebraFullName) return true;

        return false;
    }

    /// <summary>
    ///     判断类型是否为 Code 类型
    /// </summary>
    private static bool IsCodeType(ITypeSymbol type)
    {
        return type.Name == "Code" || type.ToDisplayString().EndsWith(".Code");
    }

    /// <summary>
    ///     判断类型是否为 Expr&lt;T&gt; 类型
    /// </summary>
    private static bool IsExprType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named
            && named.ConstructedFrom?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                is string and ("global::Nyar.ObjectAlgebra.Expr<T>" or "global::Nyar.ObjectAlgebra.Expr<out T>"))
            return true;

        return false;
    }

    /// <summary>
    ///     获取泛型类型的单个类型参数
    /// </summary>
    private static string? GetSingleTypeArg(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol { TypeArguments.Length: 1 } named)
            return named.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

        return null;
    }

    /// <summary>
    ///     分析方法参数，识别 Code/Expr 类型与可直接求值的静态类型
    /// </summary>
    private static PEParamInfo AnalyzePEParam(IParameterSymbol param)
    {
        var type = param.Type;
        var isStatic = IsStaticType(type);
        var isCode = IsCodeType(type);
        var isExpr = IsExprType(type);
        var exprTypeArg = isExpr ? GetSingleTypeArg(type) : null;

        return new PEParamInfo(
            param.Name,
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
            isStatic,
            isCode,
            isExpr,
            exprTypeArg);
    }

    /// <summary>
    ///     判断类型是否为可直接求值的静态类型（基本类型、枚举、值类型）
    /// </summary>
    private static bool IsStaticType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named)
        {
            if (named.IsGenericType) return false;

            if (named.SpecialType != SpecialType.None)
                return named.SpecialType switch
                {
                    SpecialType.System_Int32 => true,
                    SpecialType.System_Int64 => true,
                    SpecialType.System_Int16 => true,
                    SpecialType.System_Byte => true,
                    SpecialType.System_SByte => true,
                    SpecialType.System_UInt32 => true,
                    SpecialType.System_UInt64 => true,
                    SpecialType.System_UInt16 => true,
                    SpecialType.System_Single => true,
                    SpecialType.System_Double => true,
                    SpecialType.System_Decimal => true,
                    SpecialType.System_Boolean => true,
                    SpecialType.System_Char => true,
                    SpecialType.System_String => true,
                    _ => false
                };

            if (named.TypeKind == TypeKind.Enum) return true;

            if (named.IsValueType) return true;
        }

        return false;
    }

    #endregion

    #region 代码生成

    /// <summary>
    ///     为单个 [StaticAware] 方法生成包装器静态类
    /// </summary>
    private static void GenerateWrapperClass(StringBuilder sb, PEMethodInfo method, string indent)
    {
        if (method.AlgebraInterfaces.Count == 0) return;

        var wrapperClassName = $"{method.MethodName}_StaticAware";

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}///     {method.MethodName} 的静态/动态双路径包装器");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}[GeneratedCode(\"Nyar.SourceGenerator\", \"1.0.0\")]");
        sb.AppendLine($"{indent}file static class {wrapperClassName}");
        sb.AppendLine($"{indent}{{");

        for (var i = 0; i < method.AlgebraInterfaces.Count; i++)
        {
            var algInfo = method.AlgebraInterfaces[i];
            GenerateWrapperMethod(sb, method, algInfo, indent + "    ");
            if (i < method.AlgebraInterfaces.Count - 1) sb.AppendLine();
        }

        sb.AppendLine($"{indent}}}");
    }

    /// <summary>
    ///     生成单个代数接口对应的包装器方法
    /// </summary>
    private static void GenerateWrapperMethod(StringBuilder sb, PEMethodInfo method,
        AlgebraInterfaceInfo algInfo, string indent)
    {
        var isCode = algInfo.Variant == "Code";
        var isExpr = algInfo.Variant == "Expr";

        // 构建方法参数列表
        var paramList = new List<string>();
        var argList = new List<string>();
        var codeExprParams = new List<PEParamInfo>();

        foreach (var p in method.Parameters)
            if (p.IsStatic)
            {
                // 静态已知类型参数直接传递
                paramList.Add($"{p.ShortType} {p.Name}");
                argList.Add(p.Name);
            }
            else if (p.IsCode)
            {
                codeExprParams.Add(p);

                if (isCode)
                    paramList.Add($"Code {p.Name}");
                else
                    paramList.Add($"Expr<{algInfo.ExprTypeArg}> {p.Name}");

                argList.Add(p.Name);
            }
            else if (p.IsExpr)
            {
                codeExprParams.Add(p);

                if (isCode)
                    paramList.Add($"Code {p.Name}");
                else
                    paramList.Add($"Expr<{algInfo.ExprTypeArg}> {p.Name}");

                argList.Add(p.Name);
            }
            else
            {
                paramList.Add($"{p.ShortType} {p.Name}");
                argList.Add(p.Name);
            }

        // 代数接口实例参数
        var algTypeName = algInfo.FullDisplay;
        paramList.Add($"{algTypeName} algebra");

        // 返回类型
        var returnType = isCode ? "Code" : $"Expr<{algInfo.ExprTypeArg}>";

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}///     {method.MethodName} 的双路径求值：若所有 Code/Expr 参数为静态已知值则编译期求值，否则走动态路径");
        sb.AppendLine($"{indent}/// </summary>");

        // 如果有类型参数（泛型方法）
        var typeParamsStr = "";
        if (isExpr && method.Parameters.Any(p => p.IsCode || p.IsExpr)) typeParamsStr = $"<{algInfo.ExprTypeArg}>";

        sb.AppendLine(
            $"{indent}public static {returnType} {method.MethodName}{typeParamsStr}({string.Join(", ", paramList)})");
        sb.AppendLine($"{indent}{{");

        // 判断是否有 Code/Expr 参数需要检查 IsStatic
        if (codeExprParams.Count > 0)
        {
            // 生成 IsStatic 检查条件
            var isStaticChecks = codeExprParams.Select(p => $"{p.Name}.IsStatic").ToList();
            var checkCondition = string.Join(" && ", isStaticChecks);

            sb.AppendLine($"{indent}    if ({checkCondition})");
            sb.AppendLine($"{indent}    {{");

            // 静态路径
            if (method.InterpTypeName is not null)
                // 有 StaticInterpretation：提取静态值，调用解释器，包装结果
                EmitStaticInterpretationPath(sb, method, algInfo, codeExprParams, indent + "        ");
            else
                // 无 StaticInterpretation：尝试通过 Code.Literal 或 algebra.Literal 折叠
                EmitDirectStaticPath(sb, method, algInfo, codeExprParams, indent + "        ");

            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
        }

        // 动态路径：委托原始代数方法调用
        var dynamicArgs = BuildDynamicArgs(method, algInfo);
        sb.AppendLine($"{indent}    return algebra.{method.MethodName}({string.Join(", ", dynamicArgs)});");

        sb.AppendLine($"{indent}}}");
    }

    /// <summary>
    ///     生成 StaticInterpretation 静态求值路径
    /// </summary>
    private static void EmitStaticInterpretationPath(StringBuilder sb, PEMethodInfo method,
        AlgebraInterfaceInfo algInfo, List<PEParamInfo> codeExprParams, string indent)
    {
        // 提取静态值并调用解释器
        var interpArgs = new List<string>();
        foreach (var p in codeExprParams)
        {
            // 从 Code/Expr 中提取静态值
            var staticValueExpr = $"{p.Name}.Value";
            interpArgs.Add(staticValueExpr);
        }

        // 添加非 Code/Expr 的静态参数
        foreach (var p in method.Parameters.Where(x => x.IsStatic)) interpArgs.Add(p.Name);

        var interpCall = $"{method.InterpTypeName}.{method.MethodName}({string.Join(", ", interpArgs)})";

        if (algInfo.Variant == "Code")
        {
            sb.AppendLine($"{indent}    // 静态路径：通过 StaticInterpretation 编译期求值");
            sb.AppendLine($"{indent}    var __result = {interpCall};");
            sb.AppendLine($"{indent}    return Code.Literal(__result);");
        }
        else
        {
            sb.AppendLine($"{indent}    // 静态路径：通过 StaticInterpretation 编译期求值");
            sb.AppendLine($"{indent}    var __result = {interpCall};");
            sb.AppendLine($"{indent}    return algebra.Literal(__result);");
        }
    }

    /// <summary>
    ///     生成无 StaticInterpretation 时的直接静态求值路径
    /// </summary>
    private static void EmitDirectStaticPath(StringBuilder sb, PEMethodInfo method,
        AlgebraInterfaceInfo algInfo, List<PEParamInfo> codeExprParams, string indent)
    {
        // 所有参数都是 Code/Expr 类型且为静态，但无解释器：
        // 尝试提取值后通过 Literal 构造常量
        var hasNonCodeExprParams = method.Parameters.Any(p => !p.IsCode && !p.IsExpr && !p.IsStatic);

        if (hasNonCodeExprParams)
        {
            // 存在非 Code/Expr 参数，无法直接折叠，回退到动态路径
            sb.AppendLine($"{indent}    // 所有 Code/Expr 参数为静态，但无 StaticInterpretation 且存在非 Code 参数，回退到动态路径");
            sb.AppendLine(
                $"{indent}    return algebra.{method.MethodName}({string.Join(", ", BuildDynamicArgs(method, algInfo))});");
            return;
        }

        // 所有参数为 Code/Expr，无解释器：直接调用 algebra 方法（依赖 OA 实现的折叠逻辑）
        sb.AppendLine($"{indent}    // 所有 Code/Expr 参数为静态，委托 algebra 处理（无显式 StaticInterpretation）");
        sb.AppendLine(
            $"{indent}    return algebra.{method.MethodName}({string.Join(", ", BuildDynamicArgs(method, algInfo))});");
    }

    /// <summary>
    ///     构建动态路径的方法参数列表
    /// </summary>
    private static List<string> BuildDynamicArgs(PEMethodInfo method, AlgebraInterfaceInfo algInfo)
    {
        var args = new List<string>();

        foreach (var p in method.Parameters)
            if (p.IsStatic)
                // 静态类型值包装为 Code/Expr 常量
                args.Add(WrapLiteral(p, algInfo));
            else
                args.Add(p.Name);

        return args;
    }

    /// <summary>
    ///     将静态类型值包装为对应的字面量表达式
    /// </summary>
    private static string WrapLiteral(PEParamInfo param, AlgebraInterfaceInfo algInfo)
    {
        if (algInfo.Variant == "Code") return $"Code.Literal({param.Name})";

        return $"algebra.Literal({param.Name})";
    }

    #endregion

    #region 数据类

    /// <summary>
    ///     部分求值方法信息
    /// </summary>
    private sealed class PEMethodInfo
    {
        public PEMethodInfo(string methodName, string containingTypeDisplay,
            List<AlgebraInterfaceInfo> algebraInterfaces, List<PEParamInfo> parameters,
            string returnTypeDisplay, string? interpTypeName)
        {
            MethodName = methodName;
            ContainingTypeDisplay = containingTypeDisplay;
            AlgebraInterfaces = algebraInterfaces;
            Parameters = parameters;
            ReturnTypeDisplay = returnTypeDisplay;
            InterpTypeName = interpTypeName;
        }

        /// <summary>
        ///     原始方法名
        /// </summary>
        public string MethodName { get; }

        /// <summary>
        ///     包含类型的完全限定名
        /// </summary>
        public string ContainingTypeDisplay { get; }

        /// <summary>
        ///     方法所在的代数接口列表
        /// </summary>
        public List<AlgebraInterfaceInfo> AlgebraInterfaces { get; }

        /// <summary>
        ///     方法参数信息
        /// </summary>
        public List<PEParamInfo> Parameters { get; }

        /// <summary>
        ///     返回类型显示名
        /// </summary>
        public string ReturnTypeDisplay { get; }

        /// <summary>
        ///     StaticInterpretation 中指定的解释器类型名，未指定时为 null
        /// </summary>
        public string? InterpTypeName { get; }
    }

    /// <summary>
    ///     代数接口信息
    /// </summary>
    private sealed class AlgebraInterfaceInfo
    {
        public AlgebraInterfaceInfo(string fullDisplay, string shortName, string variant, string? exprTypeArg)
        {
            FullDisplay = fullDisplay;
            ShortName = shortName;
            Variant = variant;
            ExprTypeArg = exprTypeArg;
        }

        /// <summary>
        ///     接口完全限定显示名
        /// </summary>
        public string FullDisplay { get; }

        /// <summary>
        ///     接口短名
        /// </summary>
        public string ShortName { get; }

        /// <summary>
        ///     代数载体类型变体："Code" 或 "Expr"
        /// </summary>
        public string Variant { get; }

        /// <summary>
        ///     Expr 变体时的类型参数，Code 变体时为 null
        /// </summary>
        public string? ExprTypeArg { get; }
    }

    /// <summary>
    ///     方法参数信息
    /// </summary>
    private sealed class PEParamInfo
    {
        public PEParamInfo(string name, string fullType, string shortType,
            bool isStatic, bool isCode, bool isExpr, string? exprTypeArg)
        {
            Name = name;
            FullType = fullType;
            ShortType = shortType;
            IsStatic = isStatic;
            IsCode = isCode;
            IsExpr = isExpr;
            ExprTypeArg = exprTypeArg;
        }

        /// <summary>
        ///     参数名
        /// </summary>
        public string Name { get; }

        /// <summary>
        ///     完全限定类型名
        /// </summary>
        public string FullType { get; }

        /// <summary>
        ///     短类型名
        /// </summary>
        public string ShortType { get; }

        /// <summary>
        ///     是否为静态可求值类型（基本类型、枚举、值类型）
        /// </summary>
        public bool IsStatic { get; }

        /// <summary>
        ///     是否为 Code 类型
        /// </summary>
        public bool IsCode { get; }

        /// <summary>
        ///     是否为 Expr&lt;T&gt; 类型
        /// </summary>
        public bool IsExpr { get; }

        /// <summary>
        ///     Expr 变体时的类型参数
        /// </summary>
        public string? ExprTypeArg { get; }
    }

    #endregion
}