using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nyar.Generator;

/// <summary>
///     重写规则源生成器，扫描 [RewriteRule] 标记的静态方法对并生成 IRewriteRule&lt;Oa&gt; 实现类
/// </summary>
[Generator]
public sealed class RewriteRuleGenerator : ISourceGenerator
{
    #region MatchResult 类型生成

    /// <summary>
    ///     生成 MatchResult 记录类型，用于存储模式匹配的变量绑定
    /// </summary>
    private static void GenerateMatchResultType(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     模式匹配结果，存储变量到等价类标识符的绑定映射");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"{GeneratedCodeAttr}");
        sb.AppendLine("    internal sealed record MatchResult");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        ///     变量绑定字典（变量名 → 等价类标识符）");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public IReadOnlyDictionary<string, Id> Variables { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        ///     创建匹配结果");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"variables\">变量绑定字典。</param>");
        sb.AppendLine("        public MatchResult(IReadOnlyDictionary<string, Id> variables)");
        sb.AppendLine("        {");
        sb.AppendLine("            Variables = variables;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        ///     获取指定变量的绑定值");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"name\">变量名。</param>");
        sb.AppendLine("        /// <returns>变量绑定的等价类标识符。</returns>");
        sb.AppendLine("        public Id this[string name] => Variables[name];");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        ///     空匹配结果（无变量的匹配）");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine(
            "        public static readonly MatchResult Empty = new(new Dictionary<string, Id>());");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    #endregion

    #region 工厂类生成

    /// <summary>
    ///     生成工厂 partial class，提供静态方法返回所有生成的规则实例
    /// </summary>
    private static void GenerateFactoryClass(
        GeneratorExecutionContext context,
        RulePairInfo first,
        string safeClassName,
        List<string> ruleClassNames)
    {
        var factorySb = new StringBuilder();
        factorySb.AppendLine("// <auto-generated/>");
        factorySb.AppendLine("#pragma warning disable CS0105");
        factorySb.AppendLine("using System.Collections.Generic;");
        factorySb.AppendLine("using Nyar.IR.Intent;");
        factorySb.AppendLine("using Nyar.IR.Rewrite;");
        factorySb.AppendLine("#pragma warning restore CS0105");
        factorySb.AppendLine();

        var ns = first.Namespace;
        if (string.IsNullOrEmpty(ns))
        {
            factorySb.AppendLine("// 命名空间为空，无法生成工厂 partial class");
            return;
        }

        factorySb.AppendLine($"namespace {ns};");
        factorySb.AppendLine();

        var typeName = first.ContainingTypeName;
        factorySb.AppendLine("/// <summary>");
        factorySb.AppendLine($"///     {typeName} 的生成工厂方法，提供所有由 Source Generator 生成的重写规则实例");
        factorySb.AppendLine("/// </summary>");
        factorySb.AppendLine($"{GeneratedCodeAttr}");
        factorySb.AppendLine($"public static partial class {typeName}");
        factorySb.AppendLine("{");
        factorySb.AppendLine("    /// <summary>");
        factorySb.AppendLine("    ///     获取所有由 [RewriteRule] 属性生成的 IRewriteRule&lt;Oa&gt; 实现类");
        factorySb.AppendLine("    /// </summary>");
        factorySb.AppendLine("    /// <returns>生成的重写规则列表。</returns>");
        factorySb.AppendLine("    public static IReadOnlyList<IRewriteRule<Oa>> GeneratedRules()");
        factorySb.AppendLine("    {");
        factorySb.AppendLine("        return new List<IRewriteRule<Oa>>");
        factorySb.AppendLine("        {");

        for (var i = 0; i < ruleClassNames.Count; i++)
        {
            var sep = i < ruleClassNames.Count - 1 ? "," : "";
            factorySb.AppendLine($"            new {ruleClassNames[i]}(){sep}");
        }

        factorySb.AppendLine("        };");
        factorySb.AppendLine("    }");
        factorySb.AppendLine("}");

        context.AddSource($"Generated_{safeClassName}_Factory.g.cs",
            SourceText.From(factorySb.ToString(), Encoding.UTF8));
    }

    #endregion

    #region 常量

    private const string NewRuleAttrName = "Nyar.IR.Rewrite.RewriteRuleAttribute";
    private const string OldRuleAttrName = "Nyar.Dialect.RewriteRuleAttribute";
    private const string ReplacementAttrName = "Nyar.IR.Rewrite.RewriteReplacementAttribute";
    private const string GuardAttrName = "Nyar.IR.Rewrite.RewriteGuardAttribute";

    private const string GeneratedCodeAttr =
        "[global::System.CodeDom.Compiler.GeneratedCode(\"Nyar.SourceGenerator\", \"1.0.0\")]";

    /// <summary>
    ///     已知二元运算符方法名到核心节点语义的映射。
    /// </summary>
    private static readonly Dictionary<string, string> InfixOperatorMethodMap = new(StringComparer.OrdinalIgnoreCase)
    {
        { "Add", "add" }, { "Sub", "sub" }, { "Mul", "mul" }, { "Div", "div" }, { "Mod", "mod" },
        { "Eq", "eq" }, { "Ne", "ne" }, { "Lt", "lt" }, { "Le", "le" }, { "Gt", "gt" }, { "Ge", "ge" },
        { "And", "and" }, { "Or", "or" }, { "Xor", "xor" }, { "Shl", "shl" }, { "Shr", "shr" },
        { "Band", "band" }, { "Bor", "bor" }
    };

    /// <summary>
    ///     已知一元运算符方法名到核心节点语义的映射。
    /// </summary>
    private static readonly Dictionary<string, string> PrefixOperatorMethodMap = new(StringComparer.OrdinalIgnoreCase)
    {
        { "Neg", "neg" }, { "Not", "not" }, { "Bitnot", "bitnot" }
    };

    /// <summary>
    ///     已知字面量方法名 → OA 节点类型映射
    /// </summary>
    private static readonly Dictionary<string, string> LiteralNodeType = new(StringComparer.OrdinalIgnoreCase)
    {
        { "Int32", "Literal<long>" },
        { "Int64", "Literal<long>" },
        { "Float32", "Literal<double>" },
        { "Float64", "Literal<double>" },
        { "Boolean", "Literal<bool>" },
        { "String", "Literal<string>" },
        { "None", "Literal<object?>" }
    };

    #endregion

    #region OA 类型辅助方法

    /// <summary>
    ///     获取 OA 二元运算匹配类型名，若不在 OA 映射中则返回 null
    /// </summary>
    private static string? GetCoreInfixNodeTypeName(string op)
    {
        return op switch
        {
            "add" => "Add",
            "sub" => "Sub",
            "mul" => "Mul",
            "div" => "Div",
            "eq" or "ne" or "lt" or "le" or "gt" or "ge" => "Cmp",
            "and" => "And",
            "or" => "Or",
            _ => null
        };
    }

    /// <summary>
    ///     获取 OA 一元运算匹配类型名，若不在 OA 映射中则返回 null
    /// </summary>
    private static string? GetCorePrefixNodeTypeName(string op)
    {
        return op switch
        {
            "neg" => "Neg",
            "not" => "Not",
            _ => null
        };
    }

    /// <summary>
    ///     获取比较运算符对应的 CompareOp 表达式
    /// </summary>
    private static string? GetCompareOpExpr(string op)
    {
        return op switch
        {
            "eq" => "CompareOp.eq",
            "ne" => "CompareOp.ne",
            "lt" => "CompareOp.lt",
            "le" => "CompareOp.le",
            "gt" => "CompareOp.gt",
            "ge" => "CompareOp.ge",
            _ => null
        };
    }

    /// <summary>
    ///     获取 OA 二元运算匹配的完整模式字符串
    /// </summary>
    /// <param name="op">运算符字符串。</param>
    /// <param name="leftVar">左操作数变量名（不含 var 前缀）。</param>
    /// <param name="rightVar">右操作数变量名（不含 var 前缀）。</param>
    /// <param name="withVar">是否在模式中加上 var 关键字。</param>
    /// <returns>匹配模式字符串；若不在 OA 映射中则返回 null。</returns>
    private static string? GetCoreInfixMatchPattern(string op, string leftVar, string rightVar, bool withVar)
    {
        var varPrefix = withVar ? "var " : "";
        var typeName = GetCoreInfixNodeTypeName(op);
        if (typeName is null) return null;

        if (typeName == "Cmp")
        {
            var cmpExpr = GetCompareOpExpr(op);
            return $"Cmp {{ op: {cmpExpr}, left: {varPrefix}{leftVar}, right: {varPrefix}{rightVar} }}";
        }

        return $"{typeName} {{ left: {varPrefix}{leftVar}, right: {varPrefix}{rightVar} }}";
    }

    /// <summary>
    ///     获取 OA 一元运算匹配的完整模式字符串
    /// </summary>
    /// <param name="op">运算符字符串。</param>
    /// <param name="operandVar">操作数变量名（不含 var 前缀）。</param>
    /// <param name="withVar">是否在模式中加上 var 关键字。</param>
    /// <returns>匹配模式字符串；若不在 OA 映射中则返回 null。</returns>
    private static string? GetCorePrefixMatchPattern(string op, string operandVar, bool withVar)
    {
        var varPrefix = withVar ? "var " : "";
        var typeName = GetCorePrefixNodeTypeName(op);
        if (typeName is null) return null;

        return $"{typeName} {{ operand: {varPrefix}{operandVar} }}";
    }

    #endregion

    #region 初始化

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var rulePairs = new List<RulePairInfo>();

        foreach (var tree in context.Compilation.SyntaxTrees)
        {
            var semanticModel = context.Compilation.GetSemanticModel(tree);
            CollectRulePairs(context, semanticModel, tree, rulePairs);
        }

        if (rulePairs.Count == 0) return;

        var groupedByClass = rulePairs.GroupBy(r => r.ClassKey);

        foreach (var group in groupedByClass)
        {
            var rules = group.ToList();
            var first = rules[0];

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS0105");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.CodeDom.Compiler;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Collections.Immutable;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using Nyar.EGraph;");
            sb.AppendLine("using Nyar.IR.Intent;");
            sb.AppendLine("using Nyar.IR.Strategy;");
            sb.AppendLine("using Nyar.IR.Rewrite;");
            sb.AppendLine("using Nyar.Dialect.Sonic.Core.Nodes;");
            sb.AppendLine($"using {first.Namespace};");
            sb.AppendLine("#pragma warning restore CS0105");
            sb.AppendLine();

            sb.AppendLine("namespace Nyar.IR.Rewrite;");
            sb.AppendLine();

            // 生成 MatchResult 记录类型（file 作用域，每个生成文件一份）
            GenerateMatchResultType(sb);

            var ruleClassNames = new List<string>();

            for (var i = 0; i < rules.Count; i++)
            {
                var rule = rules[i];
                var className = $"Generated_{SanitizeIdentifier(rule.RuleName)}_Rule";
                ruleClassNames.Add(className);
                GenerateRuleClass(sb, rule, "    ");
                if (i < rules.Count - 1) sb.AppendLine();
            }

            var safeClassName = SanitizeIdentifier(first.ContainingTypeName);

            // TODO: SG 生成的规则代码暂未与当前 EGgraph API 对齐（get_nodes/rebuild 等），
            // 暂时跳过生成，AlgebraicRules.GeneratedRules() 返回空列表作为安全回退。
            // context.AddSource($"Generated_{safeClassName}_Rules.g.cs",
            //     SourceText.From(sb.ToString(), Encoding.UTF8));
            // GenerateFactoryClass(context, first, safeClassName, ruleClassNames);
        }
    }

    #endregion

    #region 扫描

    /// <summary>
    ///     从语法树中收集所有重写规则对（模式+替换+守卫）
    /// </summary>
    private void CollectRulePairs(
        GeneratorExecutionContext context,
        SemanticModel semanticModel,
        SyntaxTree tree,
        List<RulePairInfo> rulePairs)
    {
        var root = tree.GetRoot();
        var allMethods = new List<MethodWithAttributes>();

        foreach (var methodDecl in root.DescendantNodes().OfType<MethodDeclarationSyntax>())
        {
            var methodSymbol = semanticModel.GetDeclaredSymbol(methodDecl);
            if (methodSymbol is null) continue;

            if (!methodSymbol.IsStatic) continue;

            var containingType = methodSymbol.ContainingType;
            if (containingType is null || !containingType.IsStatic) continue;

            var attrClassNames = methodSymbol.GetAttributes()
                .Select(a => a.AttributeClass?.ToDisplayString())
                .Where(n => n is not null)
                .ToList();
            allMethods.Add(new MethodWithAttributes(methodSymbol, attrClassNames!, methodDecl));
        }

        var ruleMethods = allMethods
            .Where(m => HasAttribute(m.AttributeClassNames, NewRuleAttrName) ||
                        HasAttribute(m.AttributeClassNames, OldRuleAttrName))
            .ToList();

        var replacementMethods = allMethods
            .Where(m => HasAttribute(m.AttributeClassNames, ReplacementAttrName))
            .ToList();

        var guardMethods = allMethods
            .Where(m => HasAttribute(m.AttributeClassNames, GuardAttrName))
            .ToList();

        foreach (var ruleMethod in ruleMethods)
        {
            var isNewAttr = ruleMethod.AttributeClassNames.Contains(NewRuleAttrName);
            var isOldAttr = ruleMethod.AttributeClassNames.Contains(OldRuleAttrName);

            var ruleName = ruleMethod.Symbol.Name;
            string? dialect = null;

            if (isNewAttr)
            {
                var attr = ruleMethod.Symbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == NewRuleAttrName);
                if (attr is not null)
                {
                    ruleName = attr.NamedArguments
                                   .FirstOrDefault(kvp =>
                                       string.Equals(kvp.Key, "name", StringComparison.OrdinalIgnoreCase)).Value
                                   .Value as string
                               ?? ruleName;
                    dialect = attr.NamedArguments
                        .FirstOrDefault(kvp => string.Equals(kvp.Key, "Dialect", StringComparison.OrdinalIgnoreCase))
                        .Value.Value as string;
                }
            }
            else if (isOldAttr)
            {
                var attr = ruleMethod.Symbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == OldRuleAttrName);
                if (attr is not null) ruleName = attr.ConstructorArguments.FirstOrDefault().Value as string ?? ruleName;
            }

            var containingType = ruleMethod.Symbol.ContainingType;
            var ns = containingType.ContainingNamespace?.ToDisplayString() ?? string.Empty;
            var typeName = containingType.Name;

            var replacementMethod = FindMatchingReplacement(
                replacementMethods, ruleName, containingType, ruleMethod.Symbol);
            if (replacementMethod is null) continue;

            var guardMethod = FindMatchingGuard(
                guardMethods, ruleName, containingType, ruleMethod.Symbol);

            var patternTree = AnalyzePatternMethod(ruleMethod);
            if (patternTree is null) continue;

            var classKey = $"{ns}|{typeName}";

            rulePairs.Add(new RulePairInfo(
                ruleName,
                dialect,
                ruleMethod.Symbol.Name,
                replacementMethod.Symbol.Name,
                guardMethod?.Symbol.Name,
                ns,
                typeName,
                classKey,
                patternTree,
                ruleMethod.Syntax,
                replacementMethod.Syntax,
                guardMethod?.Syntax));
        }
    }

    private static bool HasAttribute(List<string> attributeClassNames, string fullName)
    {
        return attributeClassNames.Contains(fullName);
    }

    /// <summary>
    ///     查找与模式方法配对的替换方法
    /// </summary>
    private static MethodWithAttributes? FindMatchingReplacement(
        List<MethodWithAttributes> candidates,
        string ruleName,
        INamedTypeSymbol containingType,
        IMethodSymbol ruleMethod)
    {
        foreach (var candidate in candidates)
        {
            if (!SymbolEqualityComparer.Default.Equals(candidate.Symbol.ContainingType, containingType)) continue;

            var replacementAttr = candidate.Symbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == ReplacementAttrName);

            if (replacementAttr is null) continue;

            var patternParam = replacementAttr.NamedArguments
                .FirstOrDefault(kvp => string.Equals(kvp.Key, "pattern", StringComparison.OrdinalIgnoreCase)).Value
                .Value as string;

            if (patternParam is not null)
            {
                if (string.Equals(patternParam, ruleName, StringComparison.Ordinal) ||
                    string.Equals(patternParam, ruleMethod.Name, StringComparison.Ordinal))
                    return candidate;
            }
            else
            {
                // 按命名约定查找：PatternMethod + "Replacement" 或暗含匹配
                if (string.Equals(candidate.Symbol.Name, ruleMethod.Name + "Replacement",
                        StringComparison.OrdinalIgnoreCase))
                    return candidate;
            }
        }

        return null;
    }

    /// <summary>
    ///     查找与模式方法配对的守卫方法
    /// </summary>
    private static MethodWithAttributes? FindMatchingGuard(
        List<MethodWithAttributes> candidates,
        string ruleName,
        INamedTypeSymbol containingType,
        IMethodSymbol ruleMethod)
    {
        foreach (var candidate in candidates)
        {
            if (!SymbolEqualityComparer.Default.Equals(candidate.Symbol.ContainingType, containingType)) continue;

            var guardAttr = candidate.Symbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == GuardAttrName);

            if (guardAttr is null) continue;

            var patternParam = guardAttr.NamedArguments
                .FirstOrDefault(kvp => string.Equals(kvp.Key, "pattern", StringComparison.OrdinalIgnoreCase)).Value
                .Value as string;

            if (patternParam is not null)
            {
                if (string.Equals(patternParam, ruleName, StringComparison.Ordinal) ||
                    string.Equals(patternParam, ruleMethod.Name, StringComparison.Ordinal))
                    return candidate;
            }
            else
            {
                if (string.Equals(candidate.Symbol.Name, ruleMethod.Name + "Guard",
                        StringComparison.OrdinalIgnoreCase))
                    return candidate;
            }
        }

        return null;
    }

    #endregion

    #region 模式分析

    /// <summary>
    ///     模式表达式语法树节点
    /// </summary>
    private sealed class PatternNode
    {
        /// <summary>操作名（方法名，如 Add/Int32）</summary>
        public string OperationName { get; set; } = string.Empty;

        /// <summary>子节点列表</summary>
        public List<PatternNode> Children { get; set; } = [];

        /// <summary>变量名（若此节点为 Var&lt;T&gt; 引用）</summary>
        public string? VarName { get; set; }

        /// <summary>是否为 Var&lt;T&gt; 变量引用</summary>
        public bool IsVarReference => VarName is not null;

        /// <summary>是否为叶子节点（无子节点且非变量）</summary>
        public bool IsLeaf => Children.Count == 0 && !IsVarReference;

        /// <summary>是否为二元运算</summary>
        public bool IsInfixSemantic { get; set; }

        /// <summary>是否为一元运算</summary>
        public bool IsPrefixSemantic { get; set; }

        /// <summary>是否为字面量构造（Int32/Float32 等）</summary>
        public bool IsLiteral { get; set; }

        /// <summary>Oa 运算符字符串（如 add/sub）</summary>
        public string? OperatorString { get; set; }

        /// <summary>字面量对应的 Oa 节点类型名</summary>
        public string? LiteralNodeType { get; set; }

        /// <summary>
        ///     获取此节点及其所有子节点中直接绑定的变量名列表（仅直接 VarReference children）
        /// </summary>
        public List<string> GetDirectVarNames()
        {
            var vars = new List<string>();
            foreach (var child in Children)
                if (child.IsVarReference)
                    vars.Add(child.VarName!);

            return vars;
        }
    }

    /// <summary>
    ///     嵌套模式匹配信息，用于生成匹配内层运算语义的辅助方法
    /// </summary>
    private sealed class NestedPatternInfo
    {
        /// <summary>运算符字符串（如 add/sub）</summary>
        public string OperatorString { get; set; } = string.Empty;

        /// <summary>是否是二元运算</summary>
        public bool IsInfixSemantic { get; set; } = true;

        /// <summary>要绑定的变量名列表（按子节点顺序）</summary>
        public List<string> BoundVarNames { get; set; } = [];

        /// <summary>生成的辅助方法名</summary>
        public string HelperMethodName =>
            IsInfixSemantic
                ? $"MatchInfixSemantic_{OperatorString}_{string.Join("_", BoundVarNames)}"
                : $"MatchPrefixSemantic_{OperatorString}_{string.Join("_", BoundVarNames)}";
    }

    /// <summary>
    ///     分析模式方法体，提取模式表达式树
    /// </summary>
    private PatternNode? AnalyzePatternMethod(MethodWithAttributes ruleMethod)
    {
        var syntax = ruleMethod.Syntax;
        ExpressionSyntax? body = null;

        if (syntax.ExpressionBody is not null)
        {
            body = syntax.ExpressionBody.Expression;
        }
        else
        {
            var returnStmt = syntax.Body?.Statements
                .OfType<ReturnStatementSyntax>().FirstOrDefault();
            if (returnStmt != null) body = returnStmt.Expression;
        }

        if (body is null) return null;

        // 识别方法参数中的 Var<T> 类型
        var varParams = new HashSet<string>(StringComparer.Ordinal);
        foreach (var param in syntax.ParameterList.Parameters)
        {
            var typeName = param.Type?.ToString() ?? string.Empty;
            if (typeName.StartsWith("Var<") || typeName.StartsWith("Nyar.IR.Rewrite.Var<"))
                varParams.Add(param.Identifier.Text);
        }

        return AnalyzeExpression(body, varParams);
    }

    /// <summary>
    ///     递归分析表达式，构建模式树
    /// </summary>
    private PatternNode? AnalyzeExpression(ExpressionSyntax expr, HashSet<string> varParams)
    {
        switch (expr)
        {
            case InvocationExpressionSyntax invocation:
                return AnalyzeInvocation(invocation, varParams);

            case IdentifierNameSyntax identifier:
            {
                var name = identifier.Identifier.Text;
                if (varParams.Contains(name)) return new PatternNode { VarName = name };

                return null;
            }

            case LiteralExpressionSyntax literal:
                return new PatternNode
                {
                    OperationName = "literal",
                    OperatorString = literal.Token.ValueText
                };

            case BinaryExpressionSyntax binaryExpr:
                return AnalyzeBinaryExpression(binaryExpr, varParams);

            case PrefixUnaryExpressionSyntax prefixUnary:
                return AnalyzeUnaryExpression(prefixUnary, varParams);

            case ParenthesizedExpressionSyntax parens:
                return AnalyzeExpression(parens.Expression, varParams);

            case MemberAccessExpressionSyntax memberAccess:
            {
                // 处理 using static 场景：a.Int32(x) 压缩为 Int32(x)
                var simpleName = memberAccess.Name.Identifier.Text;
                if (LiteralNodeType.ContainsKey(simpleName))
                    return AnalyzeSimpleInvocation(simpleName, memberAccess, varParams);

                return null;
            }

            default:
                return null;
        }
    }

    /// <summary>
    ///     分析方法调用表达式（如 a.Add(a.Int32(x), y)）
    /// </summary>
    private PatternNode? AnalyzeInvocation(InvocationExpressionSyntax invocation, HashSet<string> varParams)
    {
        var methodName = GetMethodName(invocation);
        if (methodName is null) return null;

        // 检查是否为已知字面量构造
        if (LiteralNodeType.TryGetValue(methodName, out var literalType))
        {
            var node = new PatternNode
            {
                OperationName = methodName,
                IsLiteral = true,
                LiteralNodeType = literalType
            };

            // 字面量可能有 Var<T> 参数作为值
            foreach (var arg in invocation.ArgumentList.Arguments)
            {
                var child = AnalyzeExpression(arg.Expression, varParams);
                if (child is not null) node.Children.Add(child);
            }

            return node;
        }

        // 检查是否为已知二元运算
        var args = invocation.ArgumentList.Arguments;
        if (InfixOperatorMethodMap.TryGetValue(methodName, out var binaryOp))
        {
            // 支持两种调用风格：
            // 1. 旧风格：Add(left, right) — 两个参数
            // 2. 流畅风格：x.Add(y) — 一个参数，左操作数为接收者
            if (args.Count == 2)
            {
                var left = AnalyzeExpression(args[0].Expression, varParams);
                var right = AnalyzeExpression(args[1].Expression, varParams);

                if (left is null || right is null) return null;

                return new PatternNode
                {
                    OperationName = methodName,
                    IsInfixSemantic = true,
                    OperatorString = binaryOp,
                    Children = [left, right]
                };
            }

            if (args.Count == 1 && invocation.Expression is MemberAccessExpressionSyntax memberAccess)
            {
                var left = AnalyzeExpression(memberAccess.Expression, varParams);
                var right = AnalyzeExpression(args[0].Expression, varParams);

                if (left is null || right is null) return null;

                return new PatternNode
                {
                    OperationName = methodName,
                    IsInfixSemantic = true,
                    OperatorString = binaryOp,
                    Children = [left, right]
                };
            }

            return null;
        }

        // 检查是否为已知一元运算
        if (PrefixOperatorMethodMap.TryGetValue(methodName, out var unaryOp))
        {
            if (args.Count != 1) return null;

            var operand = AnalyzeExpression(args[0].Expression, varParams);
            if (operand is null) return null;

            return new PatternNode
            {
                OperationName = methodName,
                IsPrefixSemantic = true,
                OperatorString = unaryOp,
                Children = [operand]
            };
        }

        // 自定义操作（非标准二元/一元/字面量）
        var customNode = new PatternNode { OperationName = methodName };
        foreach (var arg in args)
        {
            var child = AnalyzeExpression(arg.Expression, varParams);
            if (child is not null)
                customNode.Children.Add(child);
            else
                customNode.Children.Add(new PatternNode { OperationName = "unknown" });
        }

        return customNode;
    }

    /// <summary>
    ///     分析 C# 二元运算符表达式
    /// </summary>
    private PatternNode? AnalyzeBinaryExpression(BinaryExpressionSyntax binaryExpr, HashSet<string> varParams)
    {
        var opName = MapCSharpBinaryOperator(binaryExpr.OperatorToken.Kind());
        if (opName is null) return null;

        var left = AnalyzeExpression(binaryExpr.Left, varParams);
        var right = AnalyzeExpression(binaryExpr.Right, varParams);

        if (left is null || right is null) return null;

        var opString = InfixOperatorMethodMap.TryGetValue(opName, out var mapped) ? mapped : opName.ToLowerInvariant();

        return new PatternNode
        {
            OperationName = opName,
            IsInfixSemantic = true,
            OperatorString = opString,
            Children = [left, right]
        };
    }

    /// <summary>
    ///     分析 C# 一元运算符表达式
    /// </summary>
    private PatternNode? AnalyzeUnaryExpression(PrefixUnaryExpressionSyntax unaryExpr, HashSet<string> varParams)
    {
        var opName = MapCSharpUnaryOperator(unaryExpr.OperatorToken.Kind());
        if (opName is null) return null;

        var operand = AnalyzeExpression(unaryExpr.Operand, varParams);
        if (operand is null) return null;

        var opString = PrefixOperatorMethodMap.TryGetValue(opName, out var mapped) ? mapped : opName.ToLowerInvariant();

        return new PatternNode
        {
            OperationName = opName,
            IsPrefixSemantic = true,
            OperatorString = opString,
            Children = [operand]
        };
    }

    /// <summary>
    ///     分析简化调用（无代数接口前缀的方法调用）
    /// </summary>
    private PatternNode? AnalyzeSimpleInvocation(
        string simpleName, MemberAccessExpressionSyntax memberAccess, HashSet<string> varParams)
    {
        if (LiteralNodeType.TryGetValue(simpleName, out var literalType))
            return new PatternNode
            {
                OperationName = simpleName,
                IsLiteral = true,
                LiteralNodeType = literalType
            };

        return null;
    }

    /// <summary>
    ///     获取方法调用表达式的目标方法名
    /// </summary>
    private static string? GetMethodName(InvocationExpressionSyntax invocation)
    {
        if (invocation.Expression is MemberAccessExpressionSyntax memberAccess)
            return memberAccess.Name.Identifier.Text;

        if (invocation.Expression is MemberBindingExpressionSyntax) return null;

        if (invocation.Expression is IdentifierNameSyntax identifier) return identifier.Identifier.Text;

        return null;
    }

    /// <summary>
    ///     映射 C# 二元运算符 → 方法名
    /// </summary>
    private static string? MapCSharpBinaryOperator(SyntaxKind kind)
    {
        return kind switch
        {
            SyntaxKind.PlusToken => "Add",
            SyntaxKind.MinusToken => "Sub",
            SyntaxKind.AsteriskToken => "Mul",
            SyntaxKind.SlashToken => "Div",
            SyntaxKind.PercentToken => "Mod",
            SyntaxKind.EqualsEqualsToken => "Eq",
            SyntaxKind.ExclamationEqualsToken => "Ne",
            SyntaxKind.LessThanToken => "Lt",
            SyntaxKind.LessThanEqualsToken => "Le",
            SyntaxKind.GreaterThanToken => "Gt",
            SyntaxKind.GreaterThanEqualsToken => "Ge",
            SyntaxKind.AmpersandAmpersandToken => "And",
            SyntaxKind.BarBarToken => "Or",
            SyntaxKind.CaretToken => "Xor",
            SyntaxKind.LessThanLessThanToken => "Shl",
            SyntaxKind.GreaterThanGreaterThanToken => "Shr",
            SyntaxKind.AmpersandToken => "Band",
            SyntaxKind.BarToken => "Bor",
            _ => null
        };
    }

    /// <summary>
    ///     映射 C# 一元运算符 → 方法名
    /// </summary>
    private static string? MapCSharpUnaryOperator(SyntaxKind kind)
    {
        return kind switch
        {
            SyntaxKind.MinusToken => "Neg",
            SyntaxKind.ExclamationToken => "Not",
            SyntaxKind.TildeToken => "Bitnot",
            _ => null
        };
    }

    #endregion

    #region 嵌套模式分析

    /// <summary>
    ///     收集模式树中所有嵌套的非叶子子模式（用于生成匹配辅助方法）
    /// </summary>
    private static List<NestedPatternInfo> CollectNestedPatterns(PatternNode root)
    {
        var result = new List<NestedPatternInfo>();
        CollectNestedPatternsRecursive(root, result);
        return result;
    }

    private static void CollectNestedPatternsRecursive(PatternNode node, List<NestedPatternInfo> result)
    {
        foreach (var child in node.Children)
            if (child.IsInfixSemantic && child.Children.Count == 2)
            {
                var directVars = child.GetDirectVarNames();
                if (directVars.Count > 0)
                    result.Add(new NestedPatternInfo
                    {
                        OperatorString = child.OperatorString!,
                        IsInfixSemantic = true,
                        BoundVarNames = directVars
                    });

                // 嵌套的子节点中可能还有更深层的嵌套
                CollectNestedPatternsRecursive(child, result);
            }
            else if (child.IsPrefixSemantic && child.Children.Count == 1)
            {
                var directVars = child.GetDirectVarNames();
                if (directVars.Count > 0)
                    result.Add(new NestedPatternInfo
                    {
                        OperatorString = child.OperatorString!,
                        IsInfixSemantic = false,
                        BoundVarNames = directVars
                    });

                CollectNestedPatternsRecursive(child, result);
            }
    }

    /// <summary>
    ///     生成嵌套模式匹配辅助方法
    /// </summary>
    private static void GenerateNestedMatchHelper(StringBuilder sb, NestedPatternInfo info, string indent)
    {
        var varParams = string.Join(", ", info.BoundVarNames.Select(v => $"ref Id __var_{v}"));
        var methodName = info.HelperMethodName;

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}///     匹配内层{info.OperatorString}运算并绑定变量 {string.Join(", ", info.BoundVarNames)}");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine(
            $"{indent}private static bool {methodName}(EGraph<Oa> egraph, Id childId, {varParams})");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    foreach (var __inner_node in egraph.get_nodes(childId))");
        sb.AppendLine($"{indent}    {{");

        if (info.IsInfixSemantic)
        {
            var oaPattern = GetCoreInfixMatchPattern(info.OperatorString, "__il", "__ir", true);
            if (oaPattern is not null)
                sb.AppendLine(
                    $"{indent}        if (__inner_node is {oaPattern})");
            else
                sb.AppendLine($"{indent}        if (false)");
        }
        else
        {
            var oaPattern = GetCorePrefixMatchPattern(info.OperatorString, "__iop", true);
            if (oaPattern is not null)
                sb.AppendLine(
                    $"{indent}        if (__inner_node is {oaPattern})");
            else
                sb.AppendLine($"{indent}        if (false)");
        }

        sb.AppendLine($"{indent}        {{");

        for (var i = 0; i < info.BoundVarNames.Count; i++)
        {
            var childExpr = info.IsInfixSemantic
                ? i == 0 ? "__il" : "__ir"
                : "__iop";
            sb.AppendLine(
                $"{indent}            __var_{info.BoundVarNames[i]} = egraph.union_find.find({childExpr});");
        }

        sb.AppendLine($"{indent}            return true;");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}    return false;");
        sb.AppendLine($"{indent}}}");
    }

    #endregion

    #region 代码生成

    /// <summary>
    ///     生成单个重写规则类
    /// </summary>
    private void GenerateRuleClass(StringBuilder sb, RulePairInfo rule, string indent)
    {
        var className = $"Generated_{SanitizeIdentifier(rule.RuleName)}_Rule";
        var safeRuleName = EscapeCSharpString(rule.RuleName);

        // 收集嵌套模式，用于生成匹配辅助方法
        var nestedPatterns = CollectNestedPatterns(rule.PatternTree);

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}///     重写规则：{safeRuleName}");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}{GeneratedCodeAttr}");
        sb.AppendLine($"{indent}internal sealed class {className} : IRewriteRule<Oa>");
        sb.AppendLine($"{indent}{{");

        // 属性
        sb.AppendLine($"{indent}    /// <summary>");
        sb.AppendLine($"{indent}    ///     规则名称");
        sb.AppendLine($"{indent}    /// </summary>");
        sb.AppendLine($"{indent}    public string name => \"{safeRuleName}\";");
        sb.AppendLine();
        sb.AppendLine($"{indent}    /// <summary>");
        sb.AppendLine($"{indent}    ///     规则代价（默认 1）");
        sb.AppendLine($"{indent}    /// </summary>");
        sb.AppendLine($"{indent}    public int Cost => 1;");
        sb.AppendLine();

        // Matches 方法
        GenerateMatchesMethod(sb, rule, nestedPatterns, indent + "    ");
        sb.AppendLine();

        // PatternAndReplacement 方法
        GenerateBuildPairMethod(sb, rule, nestedPatterns, indent + "    ");
        sb.AppendLine();

        // 嵌套模式匹配辅助方法
        foreach (var nested in nestedPatterns)
        {
            GenerateNestedMatchHelper(sb, nested, indent + "    ");
            sb.AppendLine();
        }

        // Apply 方法（接口实现）
        sb.AppendLine($"{indent}    /// <summary>");
        sb.AppendLine($"{indent}    ///     对 E-Graph 应用此重写规则，遍历所有等价类并合并匹配到的等价关系");
        sb.AppendLine($"{indent}    /// </summary>");
        sb.AppendLine($"{indent}    /// <param name=\"egraph\">目标 E-Graph。</param>");
        sb.AppendLine($"{indent}    /// <returns>是否产生了新的等价关系。</returns>");
        sb.AppendLine($"{indent}    public bool apply(EGraph<Oa> egraph)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        var changed = false;");
        sb.AppendLine($"{indent}        var classIds = egraph.classes.Keys.ToList();");
        sb.AppendLine();
        sb.AppendLine($"{indent}        foreach (var classId in classIds)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            var id = new Id(classId);");
        sb.AppendLine($"{indent}            if (egraph.get_class(id) is null) continue;");
        sb.AppendLine();
        sb.AppendLine($"{indent}            var match = Matches(egraph, id);");
        sb.AppendLine($"{indent}            if (match is null) continue;");
        sb.AppendLine();
        sb.AppendLine($"{indent}            var (pattern, replacement) = BuildPatternAndReplacement(egraph, match);");
        sb.AppendLine($"{indent}            if (replacement is null) continue;");
        sb.AppendLine();
        sb.AppendLine($"{indent}            var patternId = egraph.add(pattern);");
        sb.AppendLine($"{indent}            var replacementId = egraph.add(replacement);");
        sb.AppendLine($"{indent}            var root1 = egraph.union_find.find(patternId);");
        sb.AppendLine($"{indent}            var root2 = egraph.union_find.find(replacementId);");
        sb.AppendLine($"{indent}            if (root1 != root2)");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                egraph.union(patternId, replacementId);");
        sb.AppendLine($"{indent}                changed = true;");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}        if (changed)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            egraph.rebuild();");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}        return changed;");
        sb.AppendLine($"{indent}    }}");

        sb.AppendLine($"{indent}}}");
    }

    /// <summary>
    ///     生成 Matches 方法：基于模式表达式匹配指定等价类
    /// </summary>
    private void GenerateMatchesMethod(StringBuilder sb, RulePairInfo rule, List<NestedPatternInfo> nestedPatterns,
        string indent)
    {
        var patternTree = rule.PatternTree;
        var allVars = CollectVarNames(patternTree);

        // 构建变量名到嵌套辅助方法的映射
        var nestedHelperMap = new Dictionary<string, NestedPatternInfo>(StringComparer.Ordinal);
        foreach (var np in nestedPatterns)
        {
            var key = string.Join(",", np.BoundVarNames.OrderBy(v => v, StringComparer.Ordinal));
            nestedHelperMap[key] = np;
        }

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}///     尝试将指定等价类匹配为此规则的模式，返回变量绑定结果");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}/// <param name=\"egraph\">目标 E-Graph。</param>");
        sb.AppendLine($"{indent}/// <param name=\"id\">等价类标识符。</param>");
        sb.AppendLine($"{indent}/// <returns>匹配成功返回变量绑定；否则返回 null。</returns>");
        sb.AppendLine($"{indent}public MatchResult? Matches(EGraph<Oa> egraph, Id id)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var nodes = egraph.get_nodes(id);");
        sb.AppendLine($"{indent}    if (nodes.Count == 0) return null;");
        sb.AppendLine();

        var hasVars = allVars.Count > 0;

        if (!hasVars)
        {
            // 无变量：检查是否有节点匹配模式（始终需要 var 来解构属性）
            sb.AppendLine($"{indent}    foreach (var node in nodes)");
            sb.AppendLine($"{indent}    {{");
            EmitMatchCheck(sb, patternTree, indent + "        ", "node", true);
            sb.AppendLine($"{indent}        return MatchResult.Empty;");
            EmitCloseIfNeeded(sb, patternTree, indent + "        ");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}    return null;");
        }
        else
        {
            // 有变量：检查并捕获变量绑定
            var varList = allVars.ToList();
            varList.Sort(StringComparer.Ordinal);

            sb.AppendLine($"{indent}    foreach (var node in nodes)");
            sb.AppendLine($"{indent}    {{");
            foreach (var v in varList) sb.AppendLine($"{indent}        Id __var_{v} = default;");
            sb.AppendLine();

            var matched =
                EmitMatchCheckWithVars(sb, patternTree, indent + "        ", "node", allVars, nestedHelperMap);

            if (matched)
            {
                var dictEntries = string.Join(", ",
                    varList.Select(v => $"{{ \"{EscapeCSharpString(v)}\", __var_{v} }}"));
                sb.AppendLine(
                    $"{indent}        return new MatchResult(new Dictionary<string, Id> {{ {dictEntries} }});");
                EmitCloseIfNeededForVarMatch(sb, patternTree, indent + "        ");
            }

            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}    return null;");
        }

        sb.AppendLine($"{indent}}}");
    }

    /// <summary>
    ///     生成无变量模式匹配检查（直接返回 bool 效果）
    /// </summary>
    private void EmitMatchCheck(StringBuilder sb, PatternNode node, string indent, string nodeExpr,
        bool hasLetBinding)
    {
        if (node.IsInfixSemantic && node.Children.Count == 2)
        {
            var left = node.Children[0];
            var right = node.Children[1];
            var varPrefix = hasLetBinding ? "var " : "";

            var oaPattern = GetCoreInfixMatchPattern(node.OperatorString!, "__l", "__r", hasLetBinding);
            if (oaPattern is not null)
                sb.Append($"{indent}if ({nodeExpr} is {oaPattern}");
            else
                sb.Append($"{indent}if (false");

            var additionalChecks = new List<string>();
            if (!left.IsVarReference && !left.IsLeaf) additionalChecks.Add(GenerateChildCheck("__l", left));

            if (!right.IsVarReference && !right.IsLeaf) additionalChecks.Add(GenerateChildCheck("__r", right));

            if (additionalChecks.Count > 0) sb.Append($" && {string.Join(" && ", additionalChecks)}");

            sb.AppendLine(")");
            sb.AppendLine($"{indent}{{");
        }
        else if (node.IsPrefixSemantic && node.Children.Count == 1)
        {
            var operand = node.Children[0];
            var varPrefix = hasLetBinding ? "var " : "";

            var oaPattern = GetCorePrefixMatchPattern(node.OperatorString!, "__op", hasLetBinding);
            if (oaPattern is not null)
                sb.Append($"{indent}if ({nodeExpr} is {oaPattern}");
            else
                sb.Append($"{indent}if (false");

            if (!operand.IsVarReference && !operand.IsLeaf) sb.Append($" && {GenerateChildCheck("__op", operand)}");

            sb.AppendLine(")");
            sb.AppendLine($"{indent}{{");
        }
        else if (node.IsLiteral)
        {
            sb.AppendLine($"{indent}if ({nodeExpr} is {node.LiteralNodeType})");
            sb.AppendLine($"{indent}{{");
        }
        else if (node.IsVarReference)
        {
            sb.AppendLine($"{indent}// var: {node.VarName}");
        }
        else
        {
            sb.AppendLine(
                $"{indent}if ({nodeExpr} is StrategyNode.Extension {{ Name: \"{EscapeCSharpString(node.OperationName)}\" }})");
            sb.AppendLine($"{indent}{{");
        }
    }

    /// <summary>
    ///     生成带变量捕获的模式匹配检查
    /// </summary>
    /// <returns>是否成功匹配</returns>
    private bool EmitMatchCheckWithVars(StringBuilder sb, PatternNode node, string indent, string nodeExpr,
        HashSet<string> allVars, Dictionary<string, NestedPatternInfo> nestedHelperMap)
    {
        if (node.IsInfixSemantic && node.Children.Count == 2)
        {
            var left = node.Children[0];
            var right = node.Children[1];
            var bindingStmts = new List<string>();

            var oaPattern = GetCoreInfixMatchPattern(node.OperatorString!, "__l", "__r", true);
            if (oaPattern is not null)
            {
                sb.Append($"{indent}if ({nodeExpr} is {oaPattern}");
            }
            else
            {
                sb.Append($"{indent}if (false");
            }

            var conditions = new List<string>();

            if (left.IsVarReference)
            {
                conditions.Add(
                    $"TryGetVar(egraph, __l, \"{EscapeCSharpString(left.VarName!)}\", ref __var_{left.VarName})");
            }
            else if (!left.IsLeaf)
            {
                var leftHelperCall = GenerateNestedHelperCall("__l", left, nestedHelperMap);
                if (leftHelperCall is not null)
                    conditions.Add(leftHelperCall);
                else
                    conditions.Add(GenerateChildCheck("__l", left));

                CollectLiteralVarBindings(left, "__l", bindingStmts);
            }

            if (right.IsVarReference)
            {
                conditions.Add(
                    $"TryGetVar(egraph, __r, \"{EscapeCSharpString(right.VarName!)}\", ref __var_{right.VarName})");
            }
            else if (!right.IsLeaf)
            {
                var rightHelperCall = GenerateNestedHelperCall("__r", right, nestedHelperMap);
                if (rightHelperCall is not null)
                    conditions.Add(rightHelperCall);
                else
                    conditions.Add(GenerateChildCheck("__r", right));

                CollectLiteralVarBindings(right, "__r", bindingStmts);
            }

            foreach (var check in conditions) sb.Append($" && {check}");

            sb.AppendLine(")");
            sb.AppendLine($"{indent}{{");
            EmitBindingStatements(sb, bindingStmts, indent + "    ");
            return true;
        }

        if (node.IsPrefixSemantic && node.Children.Count == 1)
        {
            var operand = node.Children[0];
            var bindingStmts = new List<string>();

            var oaPattern = GetCorePrefixMatchPattern(node.OperatorString!, "__op", true);
            if (oaPattern is not null)
                sb.Append($"{indent}if ({nodeExpr} is {oaPattern}");
            else
                sb.Append($"{indent}if (false");

            if (operand.IsVarReference)
            {
                sb.Append(
                    $" && TryGetVar(egraph, __op, \"{EscapeCSharpString(operand.VarName!)}\", ref __var_{operand.VarName})");
            }
            else if (!operand.IsLeaf)
            {
                sb.Append($" && {GenerateChildCheck("__op", operand)}");
                CollectLiteralVarBindings(operand, "__op", bindingStmts);
            }

            sb.AppendLine(")");
            sb.AppendLine($"{indent}{{");
            EmitBindingStatements(sb, bindingStmts, indent + "    ");
            return true;
        }

        if (node.IsLiteral)
        {
            // 根模式为字面量：匹配等价类中的节点，变量绑定到该等价类 Id
            sb.AppendLine($"{indent}if ({nodeExpr} is {node.LiteralNodeType})");
            sb.AppendLine($"{indent}{{");

            if (node.Children.Count == 1 && node.Children[0].IsVarReference)
            {
                var varName = node.Children[0].VarName!;
                sb.AppendLine($"{indent}    __var_{varName} = egraph.union_find.find(id);");
            }

            return true;
        }

        if (node.IsVarReference)
        {
            sb.AppendLine(
                $"{indent}if (TryGetVar(egraph, id, \"{EscapeCSharpString(node.VarName!)}\", ref __var_{node.VarName}))");
            sb.AppendLine($"{indent}{{");
            return true;
        }

        // 自定义操作
        sb.Append(
            $"{indent}if ({nodeExpr} is StrategyNode.Extension {{ Name: \"{EscapeCSharpString(node.OperationName)}\", Children: var __children }})");
        sb.AppendLine();
        sb.AppendLine($"{indent}{{");

        // 提取自定义操作的子节点变量
        for (var i = 0; i < node.Children.Count; i++)
        {
            var child = node.Children[i];
            if (child.IsVarReference)
            {
                sb.AppendLine($"{indent}    if (__children.Length > {i})");
                sb.AppendLine(
                    $"{indent}        __var_{child.VarName} = egraph.union_find.find(__children[{i}]);");
            }
            else if (child.IsLiteral && child.Children.Any(c => c.IsVarReference))
            {
                // 字面量子节点：检查类型后绑定变量到子节点 Id
                sb.AppendLine($"{indent}    if (__children.Length > {i})");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine(
                    $"{indent}        var __childId = egraph.union_find.find(__children[{i}]);");
                sb.AppendLine(
                    $"{indent}        if ({GenerateChildCheck("__childId", child)})");
                sb.AppendLine($"{indent}        {{");
                foreach (var c in child.Children)
                    if (c.IsVarReference)
                        sb.AppendLine(
                            $"{indent}            __var_{c.VarName} = __childId;");

                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
            }
        }

        return true;
    }

    /// <summary>
    ///     收集字面量中包含的变量，生成绑定语句（将变量绑定到子节点 Id）
    /// </summary>
    private static void CollectLiteralVarBindings(PatternNode node, string childIdExpr, List<string> bindingStmts)
    {
        if (node.IsLiteral)
        {
            foreach (var child in node.Children)
                if (child.IsVarReference)
                    bindingStmts.Add(
                        $"__var_{child.VarName} = egraph.union_find.find({childIdExpr});");
        }
        else if (node.IsInfixSemantic || node.IsPrefixSemantic)
        {
            // 嵌套的二元/一元运算：变量捕获不在此层处理，
            // 通过 GenerateChildCheck 利用 ChildMatchesBinaryOp/ChildMatchesUnaryOp 在 e-class 级别检查
        }
    }

    /// <summary>
    ///     输出变量绑定语句
    /// </summary>
    private static void EmitBindingStatements(StringBuilder sb, List<string> bindingStmts, string indent)
    {
        foreach (var stmt in bindingStmts) sb.AppendLine($"{indent}{stmt};");
    }

    /// <summary>
    ///     关闭 EmitMatchCheck 的 if 块
    /// </summary>
    private static void EmitCloseIfNeeded(StringBuilder sb, PatternNode node, string indent)
    {
        // 仅对生成 if 块的节点类型关闭
        if (node.IsInfixSemantic || node.IsPrefixSemantic || node.IsLiteral || node.OperationName != "unknown")
            sb.AppendLine($"{indent}    }}");
    }

    /// <summary>
    ///     关闭带变量的匹配检查的 if 块
    /// </summary>
    private void EmitCloseIfNeededForVarMatch(StringBuilder sb, PatternNode node, string indent)
    {
        sb.AppendLine($"{indent}    }}");
    }

    /// <summary>
    ///     生成子节点类型匹配检查表达式
    /// </summary>
    private static string GenerateChildCheck(string childIdExpr, PatternNode child)
    {
        if (child.IsLiteral)
            return $"ChildMatchesNodeType(egraph, {childIdExpr}, \"{EscapeCSharpString(child.LiteralNodeType!)}\")";

        if (child.IsInfixSemantic)
            return
                $"ChildMatchesInfixSemantic(egraph, {childIdExpr}, \"{EscapeCSharpString(child.OperatorString!)}\")";

        if (child.IsPrefixSemantic)
            return
                $"ChildMatchesPrefixSemantic(egraph, {childIdExpr}, \"{EscapeCSharpString(child.OperatorString!)}\")";

        // 自定义操作
        return
            $"ChildMatchesExtension(egraph, {childIdExpr}, \"{EscapeCSharpString(child.OperationName)}\")";
    }

    /// <summary>
    ///     为嵌套非叶子子模式生成辅助方法调用表达式
    /// </summary>
    /// <param name="childIdExpr">子等价类 Id 表达式。</param>
    /// <param name="child">子模式节点。</param>
    /// <param name="nestedHelperMap">嵌套模式到辅助方法的映射。</param>
    /// <returns>辅助方法调用表达式；若无匹配项则返回 null。</returns>
    private static string? GenerateNestedHelperCall(string childIdExpr, PatternNode child,
        Dictionary<string, NestedPatternInfo> nestedHelperMap)
    {
        if (!child.IsInfixSemantic && !child.IsPrefixSemantic) return null;

        var directVars = child.GetDirectVarNames();
        if (directVars.Count == 0) return null;

        var key = string.Join(",", directVars.OrderBy(v => v, StringComparer.Ordinal));
        if (!nestedHelperMap.TryGetValue(key, out var info)) return null;

        var refArgs = string.Join(", ",
            directVars.Select(v => $"ref __var_{v}"));
        return $"{info.HelperMethodName}(egraph, {childIdExpr}, {refArgs})";
    }

    /// <summary>
    ///     生成 BuildPatternAndReplacement 方法
    /// </summary>
    private void GenerateBuildPairMethod(StringBuilder sb, RulePairInfo rule, List<NestedPatternInfo> nestedPatterns,
        string indent)
    {
        var patternTree = rule.PatternTree;
        var allVars = CollectVarNames(patternTree);
        var varList = allVars.ToList();
        varList.Sort(StringComparer.Ordinal);

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}///     根据匹配结果构建模式和替换节点对");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}/// <param name=\"egraph\">目标 E-Graph。</param>");
        sb.AppendLine($"{indent}/// <param name=\"match\">匹配结果。</param>");
        sb.AppendLine($"{indent}/// <returns>(模式节点, 替换节点) 元组；若守卫检查失败则替换为 null。</returns>");
        sb.AppendLine(
            $"{indent}private (Oa Pattern, Oa? Replacement) BuildPatternAndReplacement(EGraph<Oa> egraph, MatchResult match)");
        sb.AppendLine($"{indent}{{");

        // 提取变量
        foreach (var varName in varList)
            sb.AppendLine(
                $"{indent}    var __var_{varName} = match[\"{EscapeCSharpString(varName)}\"];");

        sb.AppendLine();

        // 构建模式节点 — 对嵌套模式使用 egraph.add() 获取内层 Id
        var hasNesting = nestedPatterns.Count > 0;
        if (hasNesting)
        {
            // 嵌套模式：先生成内层节点的 Id，再构建外层 Oa
            var patCounter = new[] { 0 };
            var patternExpr = EmitNestedPatternConstruction(sb, patternTree, indent + "    ", ref patCounter, true);
            sb.AppendLine($"{indent}    var __pattern = {patternExpr};");
        }
        else
        {
            var patternExpr = GenerateFlatPatternExpression(patternTree);
            sb.AppendLine($"{indent}    var __pattern = {patternExpr};");
        }

        sb.AppendLine();

        // 守卫检查
        if (rule.GuardMethodName is not null)
        {
            var guardArgs = string.Join(", ", varList.Select(v => $"__var_{v}"));
            sb.AppendLine(
                $"{indent}    if (!{rule.ContainingTypeName}.{rule.GuardMethodName}(egraph, {guardArgs}))");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        return (__pattern, null);");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
        }

        // 构建替换节点（调用静态替换方法）
        if (varList.Count == 0)
        {
            sb.AppendLine(
                $"{indent}    var __replacement = {rule.ContainingTypeName}.{rule.ReplacementMethodName}(egraph);");
        }
        else
        {
            var replacementArgs = string.Join(", ", varList.Select(v => $"__var_{v}"));
            sb.AppendLine(
                $"{indent}    var __replacement = {rule.ContainingTypeName}.{rule.ReplacementMethodName}(egraph, {replacementArgs});");
        }

        sb.AppendLine($"{indent}    return (__pattern, __replacement);");
        sb.AppendLine($"{indent}}}");

        // 生成辅助方法
        GenerateHelperMethods(sb, indent);
    }

    /// <summary>
    ///     为嵌套模式构造生成代码：从变量绑定构建内层 Oa 节点并返回内层 Id 表达式。
    ///     同时向 sb 输出生成子节点的语句。
    /// </summary>
    /// <param name="isRoot">是否处理根节点（根节点返回 Oa 表达式；子节点返回 Id）。</param>
    private static string EmitNestedPatternConstruction(StringBuilder sb, PatternNode node, string indent,
        ref int[] counter, bool isRoot = false)
    {
        if (node.IsVarReference) return $"__var_{node.VarName}";

        if (node.IsInfixSemantic && node.Children.Count == 2)
        {
            var left = node.Children[0];
            var right = node.Children[1];

            var leftExpr = EmitNestedPatternConstruction(sb, left, indent, ref counter);
            var rightExpr = EmitNestedPatternConstruction(sb, right, indent, ref counter);

            var nodeExpr = BuildOaBinaryOp(node.OperatorString!, leftExpr, rightExpr);

            if (isRoot) return nodeExpr;

            var tmpId = $"__pat_{counter[0]++}";
            sb.AppendLine($"{indent}var {tmpId} = egraph.add({nodeExpr});");
            return tmpId;
        }

        if (node.IsPrefixSemantic && node.Children.Count == 1)
        {
            var operandExpr = EmitNestedPatternConstruction(sb, node.Children[0], indent, ref counter);
            var nodeExpr = BuildOaUnaryOp(node.OperatorString!, operandExpr);

            if (isRoot) return nodeExpr;

            var tmpId = $"__pat_{counter[0]++}";
            sb.AppendLine($"{indent}var {tmpId} = egraph.add({nodeExpr});");
            return tmpId;
        }

        return "new Nyar.Dialect.Sonic.Core.Nodes.Literal<object?>(null)";
    }

    /// <summary>
    ///     为模式构造获取子节点表达式：变量引用直接用 Id，嵌套节点先 add 再返回 Id
    /// </summary>
    private static string GetChildExprForConstruction(StringBuilder sb, PatternNode child, string indent,
        ref int[] counter)
    {
        if (child.IsVarReference) return $"__var_{child.VarName}";

        if (child.IsInfixSemantic && child.Children.Count == 2)
        {
            var leftExpr = GetChildExprForConstruction(sb, child.Children[0], indent, ref counter);
            var rightExpr = GetChildExprForConstruction(sb, child.Children[1], indent, ref counter);
            var nodeExpr = BuildOaBinaryOp(child.OperatorString!, leftExpr, rightExpr);
            var tmpId = $"__pat_{counter[0]++}";
            sb.AppendLine($"{indent}var {tmpId} = egraph.add({nodeExpr});");
            return tmpId;
        }

        if (child.IsPrefixSemantic && child.Children.Count == 1)
        {
            var operandExpr = GetChildExprForConstruction(sb, child.Children[0], indent, ref counter);
            var nodeExpr = BuildOaUnaryOp(child.OperatorString!, operandExpr);
            var tmpId = $"__pat_{counter[0]++}";
            sb.AppendLine($"{indent}var {tmpId} = egraph.add({nodeExpr});");
            return tmpId;
        }

        return "new Nyar.Dialect.Sonic.Core.Nodes.Literal<object?>(null)";
    }

    /// <summary>
    ///     生成扁平模式表达式（仅用于无嵌套子模式的简单规则）
    /// </summary>
    private static string GenerateFlatPatternExpression(PatternNode node)
    {
        if (node.IsVarReference) return $"__var_{node.VarName}";

        if (node.IsInfixSemantic && node.Children.Count == 2)
        {
            var left = GenerateFlatPatternExpression(node.Children[0]);
            var right = GenerateFlatPatternExpression(node.Children[1]);
            return BuildOaBinaryOp(node.OperatorString!, left, right);
        }

        if (node.IsPrefixSemantic && node.Children.Count == 1)
        {
            var operand = GenerateFlatPatternExpression(node.Children[0]);
            return BuildOaUnaryOp(node.OperatorString!, operand);
        }

        if (node.IsLiteral)
        {
            if (node.Children.Count == 1 && node.Children[0].IsVarReference)
            {
                var varName = node.Children[0].VarName;
                return $"__var_{varName}";
            }

            return "new Nyar.Dialect.Sonic.Core.Nodes.Literal<long>(0)";
        }

        if (node.Children.Count > 0)
        {
            var children = string.Join(", ",
                node.Children.Select(c => GenerateFlatPatternExpression(c)));
            return $"new StrategyNode.Extension(\"{EscapeCSharpString(node.OperationName)}\", [{children}])";
        }

        return
            $"new StrategyNode.Extension(\"{EscapeCSharpString(node.OperationName)}\", ImmutableArray<Id>.Empty)";
    }

    /// <summary>
    ///     根据二元运算符字符串构建 OA 节点构造表达式
    /// </summary>
    private static string BuildOaBinaryOp(string op, string leftExpr, string rightExpr)
    {
        return op switch
        {
            "add" => $"new Nyar.Dialect.Sonic.Core.Nodes.Add({leftExpr}, {rightExpr})",
            "sub" => $"new Nyar.Dialect.Sonic.Core.Nodes.Sub({leftExpr}, {rightExpr})",
            "mul" => $"new Nyar.Dialect.Sonic.Core.Nodes.Mul({leftExpr}, {rightExpr})",
            "div" => $"new Nyar.Dialect.Sonic.Core.Nodes.Div({leftExpr}, {rightExpr})",
            "and" => $"new Nyar.Dialect.Sonic.Core.Nodes.And({leftExpr}, {rightExpr})",
            "or" => $"new Nyar.Dialect.Sonic.Core.Nodes.Or({leftExpr}, {rightExpr})",
            "eq" => $"new Nyar.Dialect.Sonic.Core.Nodes.Cmp(CompareOp.eq, {leftExpr}, {rightExpr})",
            "ne" => $"new Nyar.Dialect.Sonic.Core.Nodes.Cmp(CompareOp.ne, {leftExpr}, {rightExpr})",
            "lt" => $"new Nyar.Dialect.Sonic.Core.Nodes.Cmp(CompareOp.lt, {leftExpr}, {rightExpr})",
            "le" => $"new Nyar.Dialect.Sonic.Core.Nodes.Cmp(CompareOp.le, {leftExpr}, {rightExpr})",
            "gt" => $"new Nyar.Dialect.Sonic.Core.Nodes.Cmp(CompareOp.gt, {leftExpr}, {rightExpr})",
            "ge" => $"new Nyar.Dialect.Sonic.Core.Nodes.Cmp(CompareOp.ge, {leftExpr}, {rightExpr})",
            _ => $"throw new global::System.NotSupportedException($\"不支持的二元运算符: {{({op})}}\")"
        };
    }

    /// <summary>
    ///     根据一元运算符字符串构建 OA 节点构造表达式
    /// </summary>
    private static string BuildOaUnaryOp(string op, string operandExpr)
    {
        return op switch
        {
            "neg" => $"new Nyar.Dialect.Sonic.Core.Nodes.Neg({operandExpr})",
            "not" => $"new Nyar.Dialect.Sonic.Core.Nodes.Not({operandExpr})",
            _ => $"throw new global::System.NotSupportedException($\"不支持的一元运算符: {{({op})}}\")"
        };
    }

    /// <summary>
    ///     生成辅助方法（TryGetVar、ChildMatchesNodeType 等）
    /// </summary>
    private void GenerateHelperMethods(StringBuilder sb, string indent)
    {
        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}///     尝试获取变量绑定的等价类标识符");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine(
            $"{indent}private static bool TryGetVar(EGraph<Oa> egraph, Id childId, string varName, ref Id varId)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    varId = egraph.union_find.find(childId);");
        sb.AppendLine($"{indent}    return true;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}///     检查子等价类中是否存在指定节点类型的节点");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine(
            $"{indent}private static bool ChildMatchesNodeType(EGraph<Oa> egraph, Id childId, string typeName)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var childNodes = egraph.get_nodes(childId);");
        sb.AppendLine($"{indent}    return typeName switch");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        \"Literal<long>\" => childNodes.Any(n => n is Literal<long>),");
        sb.AppendLine($"{indent}        \"Literal<double>\" => childNodes.Any(n => n is Literal<double>),");
        sb.AppendLine($"{indent}        \"Literal<bool>\" => childNodes.Any(n => n is Literal<bool>),");
        sb.AppendLine($"{indent}        \"Literal<string>\" => childNodes.Any(n => n is Literal<string>),");
        sb.AppendLine($"{indent}        \"Literal<object?>\" => childNodes.Any(n => n is Literal<object?>),");
        sb.AppendLine($"{indent}        _ => childNodes.Any(n => n.GetType().Name == typeName),");
        sb.AppendLine($"{indent}    }};");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}///     检查子等价类中是否存在指定二元运算符的节点");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine(
            $"{indent}private static bool ChildMatchesInfixSemantic(EGraph<Oa> egraph, Id childId, string op)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var childNodes = egraph.get_nodes(childId);");
        sb.AppendLine($"{indent}    return op switch");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        \"add\" => childNodes.Any(n => n is Add),");
        sb.AppendLine($"{indent}        \"sub\" => childNodes.Any(n => n is Sub),");
        sb.AppendLine($"{indent}        \"mul\" => childNodes.Any(n => n is Mul),");
        sb.AppendLine($"{indent}        \"div\" => childNodes.Any(n => n is Div),");
        sb.AppendLine($"{indent}        \"eq\" => childNodes.Any(n => n is Cmp {{ op: CompareOp.eq }}),");
        sb.AppendLine($"{indent}        \"ne\" => childNodes.Any(n => n is Cmp {{ op: CompareOp.ne }}),");
        sb.AppendLine($"{indent}        \"lt\" => childNodes.Any(n => n is Cmp {{ op: CompareOp.lt }}),");
        sb.AppendLine($"{indent}        \"le\" => childNodes.Any(n => n is Cmp {{ op: CompareOp.le }}),");
        sb.AppendLine($"{indent}        \"gt\" => childNodes.Any(n => n is Cmp {{ op: CompareOp.gt }}),");
        sb.AppendLine($"{indent}        \"ge\" => childNodes.Any(n => n is Cmp {{ op: CompareOp.ge }}),");
        sb.AppendLine($"{indent}        \"and\" => childNodes.Any(n => n is And),");
        sb.AppendLine($"{indent}        \"or\" => childNodes.Any(n => n is Or),");
        sb.AppendLine($"{indent}        _ => false,");
        sb.AppendLine($"{indent}    }};");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}///     检查子等价类中是否存在指定一元运算符的节点");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine(
            $"{indent}private static bool ChildMatchesPrefixSemantic(EGraph<Oa> egraph, Id childId, string op)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var childNodes = egraph.get_nodes(childId);");
        sb.AppendLine($"{indent}    return op switch");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        \"neg\" => childNodes.Any(n => n is Neg),");
        sb.AppendLine($"{indent}        \"not\" => childNodes.Any(n => n is Not),");
        sb.AppendLine($"{indent}        _ => false,");
        sb.AppendLine($"{indent}    }};");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}///     检查子等价类中是否存在指定名称的扩展节点");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine(
            $"{indent}private static bool ChildMatchesExtension(EGraph<Oa> egraph, Id childId, string name)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var childNodes = egraph.get_nodes(childId);");
        sb.AppendLine(
            $"{indent}    return childNodes.Any(n => n is StrategyNode.Extension {{ Name: var __n }} && __n == name);");
        sb.AppendLine($"{indent}}}");
    }

    #endregion

    #region 辅助方法

    /// <summary>
    ///     收集模式树中所有变量名
    /// </summary>
    private static HashSet<string> CollectVarNames(PatternNode node)
    {
        var vars = new HashSet<string>(StringComparer.Ordinal);
        CollectVarNamesRecursive(node, vars);
        return vars;
    }

    private static void CollectVarNamesRecursive(PatternNode node, HashSet<string> vars)
    {
        if (node.IsVarReference) vars.Add(node.VarName!);

        foreach (var child in node.Children) CollectVarNamesRecursive(child, vars);
    }

    /// <summary>
    ///     清理标识符中不允许的字符
    /// </summary>
    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder();
        foreach (var ch in name)
            if (char.IsLetterOrDigit(ch) || ch == '_')
                sb.Append(ch);
            else
                sb.Append('_');

        if (sb.Length == 0) return "_";

        if (char.IsDigit(sb[0])) sb.Insert(0, '_');

        return sb.ToString();
    }

    /// <summary>
    ///     转义 C# 字符串字面量
    /// </summary>
    private static string EscapeCSharpString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    #endregion

    #region 数据类

    private sealed class MethodWithAttributes
    {
        public MethodWithAttributes(IMethodSymbol symbol, List<string> attributeClassNames,
            MethodDeclarationSyntax syntax)
        {
            Symbol = symbol;
            AttributeClassNames = attributeClassNames;
            Syntax = syntax;
        }

        public IMethodSymbol Symbol { get; }
        public List<string> AttributeClassNames { get; }
        public MethodDeclarationSyntax Syntax { get; }
    }

    private sealed class RulePairInfo
    {
        public RulePairInfo(
            string ruleName,
            string? dialect,
            string patternMethodName,
            string replacementMethodName,
            string? guardMethodName,
            string ns,
            string containingTypeName,
            string classKey,
            PatternNode patternTree,
            MethodDeclarationSyntax patternSyntax,
            MethodDeclarationSyntax replacementSyntax,
            MethodDeclarationSyntax? guardSyntax)
        {
            RuleName = ruleName;
            Dialect = dialect;
            PatternMethodName = patternMethodName;
            ReplacementMethodName = replacementMethodName;
            GuardMethodName = guardMethodName;
            Namespace = ns;
            ContainingTypeName = containingTypeName;
            ClassKey = classKey;
            PatternTree = patternTree;
            PatternSyntax = patternSyntax;
            ReplacementSyntax = replacementSyntax;
            GuardSyntax = guardSyntax;
        }

        public string RuleName { get; }
        public string? Dialect { get; }
        public string PatternMethodName { get; }
        public string ReplacementMethodName { get; }
        public string? GuardMethodName { get; }
        public string Namespace { get; }
        public string ContainingTypeName { get; }
        public string ClassKey { get; }
        public PatternNode PatternTree { get; }
        public MethodDeclarationSyntax PatternSyntax { get; }
        public MethodDeclarationSyntax ReplacementSyntax { get; }
        public MethodDeclarationSyntax? GuardSyntax { get; }
    }

    #endregion
}
