<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <RootNamespace>Hermes.Plugin.TypeScript</RootNamespace>
    <AssemblyName>Hermes.Plugin.TypeScript</AssemblyName>
    <PackageId>Hermes.Plugin.TypeScript</PackageId>
        <Authors>NyarVM</Authors>
    <Description>Hermes TypeScript 代码生成插件</Description>
        <PackageTags>hermes;typescript;plugin;code-generation</PackageTags>
          <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>
    <ItemGroup>
    <ProjectReference Include="..\..\Sonic.Standard.Schema.csproj"/>
    <ProjectReference Include="..\..\..\Nyar\Nyar.csproj"/>
  </ItemGroup>
</Project>
